% -------------------------------------------------------------------
%  Generated by MATLAB on 13-Jun-2019 09:33:24
%  MATLAB version: 9.3.0.713579 (R2017b)
% -------------------------------------------------------------------
saveVarsMat = load('arrangedGaitVariableData.mat');

arrangedData = saveVarsMat.arrangedData; % <101x60x68 double> too many elements

clear saveVarsMat;
