function prepareTTests

    masterData = load('arrangedData.mat','arrangedData');
    
    Acr2PelFrontalLeftX = masterData.arrangedData(:,:,1);
    Acr2PelTransLeftX = masterData.arrangedData(:,:,2);
    Acr2UTFrontalLeftX = masterData.arrangedData(:,:,3);
    Acr2UTTransLeftX = masterData.arrangedData(:,:,4);
    LLPelvisLeftX = masterData.arrangedData(:,:,5);
    LLPelvisLeftY = masterData.arrangedData(:,:,6);
    LLPelvisLeftZ = masterData.arrangedData(:,:,7);
    LTLLLeftX = masterData.arrangedData(:,:,8);
    LTLLLeftY = masterData.arrangedData(:,:,9);
    LTLLLeftZ = masterData.arrangedData(:,:,10);
    LTPelvisLeftX = masterData.arrangedData(:,:,11);
    LTPelvisLeftY = masterData.arrangedData(:,:,12);
    LTPelvisLeftZ = masterData.arrangedData(:,:,13);
    LTULLeftX = masterData.arrangedData(:,:,14);
    LTULLeftY = masterData.arrangedData(:,:,15);
    LTULLeftZ = masterData.arrangedData(:,:,16);
    ULLLLeftX = masterData.arrangedData(:,:,17);
    ULLLLeftY = masterData.arrangedData(:,:,18);
    ULLLLeftZ = masterData.arrangedData(:,:,19);
    ULPelvisLeftX = masterData.arrangedData(:,:,20);
    ULPelvisLeftY = masterData.arrangedData(:,:,21);
    ULPelvisLeftZ = masterData.arrangedData(:,:,22);
    UTLLLeftX = masterData.arrangedData(:,:,23);
    UTLLLeftY = masterData.arrangedData(:,:,24);
    UTLLLeftZ = masterData.arrangedData(:,:,25);
    UTLTLeftX = masterData.arrangedData(:,:,26);
    UTLTLeftY = masterData.arrangedData(:,:,27);
    UTLTLeftZ = masterData.arrangedData(:,:,28);
    UTPelvisLeftX = masterData.arrangedData(:,:,29);
    UTPelvisLeftY = masterData.arrangedData(:,:,30);
    UTPelvisLeftZ = masterData.arrangedData(:,:,31);
    UTULLeftX = masterData.arrangedData(:,:,32);
    UTULLeftY = masterData.arrangedData(:,:,33);
    UTULLeftZ = masterData.arrangedData(:,:,34);

    Acr2PelFrontalRightX = masterData.arrangedData(:,:,35);
    Acr2PelTransRightX = masterData.arrangedData(:,:,36);
    Acr2UTFrontalRightX = masterData.arrangedData(:,:,37);
    Acr2UTTransRightX = masterData.arrangedData(:,:,38);
    LLPelvisRightX = masterData.arrangedData(:,:,39);
    LLPelvisRightY = masterData.arrangedData(:,:,40);
    LLPelvisRightZ = masterData.arrangedData(:,:,41);
    LTLLRightX = masterData.arrangedData(:,:,42);
    LTLLRightY = masterData.arrangedData(:,:,43);
    LTLLRightZ = masterData.arrangedData(:,:,44);
    LTPelvisRightX = masterData.arrangedData(:,:,45);
    LTPelvisRightY = masterData.arrangedData(:,:,46);
    LTPelvisRightZ = masterData.arrangedData(:,:,47);
    LTULRightX = masterData.arrangedData(:,:,48);
    LTULRightY = masterData.arrangedData(:,:,49);
    LTULRightZ = masterData.arrangedData(:,:,50);
    ULLLRightX = masterData.arrangedData(:,:,51);
    ULLLRightY = masterData.arrangedData(:,:,52);
    ULLLRightZ = masterData.arrangedData(:,:,53);
    ULPelvisRightX = masterData.arrangedData(:,:,54);
    ULPelvisRightY = masterData.arrangedData(:,:,55);
    ULPelvisRightZ = masterData.arrangedData(:,:,56);
    UTLLRightX = masterData.arrangedData(:,:,57);
    UTLLRightY = masterData.arrangedData(:,:,58);
    UTLLRightZ = masterData.arrangedData(:,:,59);
    UTLTRightX = masterData.arrangedData(:,:,60);
    UTLTRightY = masterData.arrangedData(:,:,61);
    UTLTRightZ = masterData.arrangedData(:,:,62);
    UTPelvisRightX = masterData.arrangedData(:,:,63);
    UTPelvisRightY = masterData.arrangedData(:,:,64);
    UTPelvisRightZ = masterData.arrangedData(:,:,65);
    UTULRightX = masterData.arrangedData(:,:,66);
    UTULRightY = masterData.arrangedData(:,:,67);
    UTULRightZ = masterData.arrangedData(:,:,68);

    datasetAcr2PelFrontalLeftX = cell2struct(num2cell(Acr2PelFrontalLeftX, 1), compose('Subject%d', 1:size(Acr2PelFrontalLeftX, 2)), 2);
    datasetAcr2PelTransLeftX = cell2struct(num2cell(Acr2PelTransLeftX, 1), compose('Subject%d', 1:size(Acr2PelTransLeftX, 2)), 2);
    datasetAcr2UTFrontalLeftX = cell2struct(num2cell(Acr2UTFrontalLeftX, 1), compose('Subject%d', 1:size(Acr2UTFrontalLeftX, 2)), 2);
    datasetAcr2UTTransLeftX = cell2struct(num2cell(Acr2UTTransLeftX, 1), compose('Subject%d', 1:size(Acr2UTTransLeftX, 2)), 2);
    datasetLLPelvisLeftX = cell2struct(num2cell(LLPelvisLeftX, 1), compose('Subject%d', 1:size(LLPelvisLeftX, 2)), 2);
    datasetLLPelvisLeftY = cell2struct(num2cell(LLPelvisLeftY, 1), compose('Subject%d', 1:size(LLPelvisLeftY, 2)), 2);
    datasetLLPelvisLeftZ = cell2struct(num2cell(LLPelvisLeftZ, 1), compose('Subject%d', 1:size(LLPelvisLeftZ, 2)), 2);
    datasetLTLLLeftX = cell2struct(num2cell(LTLLLeftX, 1), compose('Subject%d', 1:size(LTLLLeftX, 2)), 2);
    datasetLTLLLeftY = cell2struct(num2cell(LTLLLeftY, 1), compose('Subject%d', 1:size(LTLLLeftY, 2)), 2);
    datasetLTLLLeftZ = cell2struct(num2cell(LTLLLeftZ, 1), compose('Subject%d', 1:size(LTLLLeftZ, 2)), 2);
    datasetLTPelvisLeftX = cell2struct(num2cell(LTPelvisLeftX, 1), compose('Subject%d', 1:size(LTPelvisLeftX, 2)), 2);
    datasetLTPelvisLeftY = cell2struct(num2cell(LTPelvisLeftY, 1), compose('Subject%d', 1:size(LTPelvisLeftY, 2)), 2);
    datasetLTPelvisLeftZ = cell2struct(num2cell(LTPelvisLeftZ, 1), compose('Subject%d', 1:size(LTPelvisLeftZ, 2)), 2);
    datasetLTULLeftX = cell2struct(num2cell(LTULLeftX, 1), compose('Subject%d', 1:size(LTULLeftX, 2)), 2);
    datasetLTULLeftY = cell2struct(num2cell(LTULLeftY, 1), compose('Subject%d', 1:size(LTULLeftY, 2)), 2);
    datasetLTULLeftZ = cell2struct(num2cell(LTULLeftZ, 1), compose('Subject%d', 1:size(LTULLeftZ, 2)), 2);
    datasetULLLLeftX = cell2struct(num2cell(ULLLLeftX, 1), compose('Subject%d', 1:size(ULLLLeftX, 2)), 2);
    datasetULLLLeftY = cell2struct(num2cell(ULLLLeftY, 1), compose('Subject%d', 1:size(ULLLLeftY, 2)), 2);
    datasetULLLLeftZ = cell2struct(num2cell(ULLLLeftZ, 1), compose('Subject%d', 1:size(ULLLLeftZ, 2)), 2);
    datasetULPelvisLeftX = cell2struct(num2cell(ULPelvisLeftX, 1), compose('Subject%d', 1:size(ULPelvisLeftX, 2)), 2);
    datasetULPelvisLeftY = cell2struct(num2cell(ULPelvisLeftY, 1), compose('Subject%d', 1:size(ULPelvisLeftY, 2)), 2);
    datasetULPelvisLeftZ = cell2struct(num2cell(ULPelvisLeftZ, 1), compose('Subject%d', 1:size(ULPelvisLeftZ, 2)), 2);
    datasetUTLLLeftX = cell2struct(num2cell(UTLLLeftX, 1), compose('Subject%d', 1:size(UTLLLeftX, 2)), 2);
    datasetUTLLLeftY = cell2struct(num2cell(UTLLLeftY, 1), compose('Subject%d', 1:size(UTLLLeftY, 2)), 2);
    datasetUTLLLeftZ = cell2struct(num2cell(UTLLLeftZ, 1), compose('Subject%d', 1:size(UTLLLeftZ, 2)), 2);
    datasetUTLTLeftX = cell2struct(num2cell(UTLTLeftX, 1), compose('Subject%d', 1:size(UTLTLeftX, 2)), 2);
    datasetUTLTLeftY = cell2struct(num2cell(UTLTLeftY, 1), compose('Subject%d', 1:size(UTLTLeftY, 2)), 2);
    datasetUTLTLeftZ = cell2struct(num2cell(UTLTLeftZ, 1), compose('Subject%d', 1:size(UTLTLeftZ, 2)), 2);
    datasetUTPelvisLeftX = cell2struct(num2cell(UTPelvisLeftX, 1), compose('Subject%d', 1:size(UTPelvisLeftX, 2)), 2);
    datasetUTPelvisLeftY = cell2struct(num2cell(UTPelvisLeftY, 1), compose('Subject%d', 1:size(UTPelvisLeftY, 2)), 2);
    datasetUTPelvisLeftZ = cell2struct(num2cell(UTPelvisLeftZ, 1), compose('Subject%d', 1:size(UTPelvisLeftZ, 2)), 2);
    datasetUTULLeftX = cell2struct(num2cell(UTULLeftX, 1), compose('Subject%d', 1:size(UTULLeftX, 2)), 2);
    datasetUTULLeftY = cell2struct(num2cell(UTULLeftY, 1), compose('Subject%d', 1:size(UTULLeftY, 2)), 2);
    datasetUTULLeftZ = cell2struct(num2cell(UTULLeftZ, 1), compose('Subject%d', 1:size(UTULLeftZ, 2)), 2);
    
    datasetAcr2PelFrontalRightX = cell2struct(num2cell(Acr2PelFrontalRightX, 1), compose('Subject%d', 1:size(Acr2PelFrontalRightX, 2)), 2);
    datasetAcr2PelTransRightX = cell2struct(num2cell(Acr2PelTransRightX, 1), compose('Subject%d', 1:size(Acr2PelTransRightX, 2)), 2);
    datasetAcr2UTFrontalRightX = cell2struct(num2cell(Acr2UTFrontalRightX, 1), compose('Subject%d', 1:size(Acr2UTFrontalRightX, 2)), 2);
    datasetAcr2UTTransRightX = cell2struct(num2cell(Acr2UTTransRightX, 1), compose('Subject%d', 1:size(Acr2UTTransRightX, 2)), 2);
    datasetLLPelvisRightX = cell2struct(num2cell(LLPelvisRightX, 1), compose('Subject%d', 1:size(LLPelvisRightX, 2)), 2);
    datasetLLPelvisRightY = cell2struct(num2cell(LLPelvisRightY, 1), compose('Subject%d', 1:size(LLPelvisRightY, 2)), 2);
    datasetLLPelvisRightZ = cell2struct(num2cell(LLPelvisRightZ, 1), compose('Subject%d', 1:size(LLPelvisRightZ, 2)), 2);
    datasetLTLLRightX = cell2struct(num2cell(LTLLRightX, 1), compose('Subject%d', 1:size(LTLLRightX, 2)), 2);
    datasetLTLLRightY = cell2struct(num2cell(LTLLRightY, 1), compose('Subject%d', 1:size(LTLLRightY, 2)), 2);
    datasetLTLLRightZ = cell2struct(num2cell(LTLLRightZ, 1), compose('Subject%d', 1:size(LTLLRightZ, 2)), 2);
    datasetLTPelvisRightX = cell2struct(num2cell(LTPelvisRightX, 1), compose('Subject%d', 1:size(LTPelvisRightX, 2)), 2);
    datasetLTPelvisRightY = cell2struct(num2cell(LTPelvisRightY, 1), compose('Subject%d', 1:size(LTPelvisRightY, 2)), 2);
    datasetLTPelvisRightZ = cell2struct(num2cell(LTPelvisRightZ, 1), compose('Subject%d', 1:size(LTPelvisRightZ, 2)), 2);
    datasetLTULRightX = cell2struct(num2cell(LTULRightX, 1), compose('Subject%d', 1:size(LTULRightX, 2)), 2);
    datasetLTULRightY = cell2struct(num2cell(LTULRightY, 1), compose('Subject%d', 1:size(LTULRightY, 2)), 2);
    datasetLTULRightZ = cell2struct(num2cell(LTULRightZ, 1), compose('Subject%d', 1:size(LTULRightZ, 2)), 2);
    datasetULLLRightX = cell2struct(num2cell(ULLLRightX, 1), compose('Subject%d', 1:size(ULLLRightX, 2)), 2);
    datasetULLLRightY = cell2struct(num2cell(ULLLRightY, 1), compose('Subject%d', 1:size(ULLLRightY, 2)), 2);
    datasetULLLRightZ = cell2struct(num2cell(ULLLRightZ, 1), compose('Subject%d', 1:size(ULLLRightZ, 2)), 2);
    datasetULPelvisRightX = cell2struct(num2cell(ULPelvisRightX, 1), compose('Subject%d', 1:size(ULPelvisRightX, 2)), 2);
    datasetULPelvisRightY = cell2struct(num2cell(ULPelvisRightY, 1), compose('Subject%d', 1:size(ULPelvisRightY, 2)), 2);
    datasetULPelvisRightZ = cell2struct(num2cell(ULPelvisRightZ, 1), compose('Subject%d', 1:size(ULPelvisRightZ, 2)), 2);
    datasetUTLLRightX = cell2struct(num2cell(UTLLRightX, 1), compose('Subject%d', 1:size(UTLLRightX, 2)), 2);
    datasetUTLLRightY = cell2struct(num2cell(UTLLRightY, 1), compose('Subject%d', 1:size(UTLLRightY, 2)), 2);
    datasetUTLLRightZ = cell2struct(num2cell(UTLLRightZ, 1), compose('Subject%d', 1:size(UTLLRightZ, 2)), 2);
    datasetUTLTRightX = cell2struct(num2cell(UTLTRightX, 1), compose('Subject%d', 1:size(UTLTRightX, 2)), 2);
    datasetUTLTRightY = cell2struct(num2cell(UTLTRightY, 1), compose('Subject%d', 1:size(UTLTRightY, 2)), 2);
    datasetUTLTRightZ = cell2struct(num2cell(UTLTRightZ, 1), compose('Subject%d', 1:size(UTLTRightZ, 2)), 2);
    datasetUTPelvisRightX = cell2struct(num2cell(UTPelvisRightX, 1), compose('Subject%d', 1:size(UTPelvisRightX, 2)), 2);
    datasetUTPelvisRightY = cell2struct(num2cell(UTPelvisRightY, 1), compose('Subject%d', 1:size(UTPelvisRightY, 2)), 2);
    datasetUTPelvisRightZ = cell2struct(num2cell(UTPelvisRightZ, 1), compose('Subject%d', 1:size(UTPelvisRightZ, 2)), 2);
    datasetUTULRightX = cell2struct(num2cell(UTULRightX, 1), compose('Subject%d', 1:size(UTULRightX, 2)), 2);
    datasetUTULRightY = cell2struct(num2cell(UTULRightY, 1), compose('Subject%d', 1:size(UTULRightY, 2)), 2);
    datasetUTULRightZ = cell2struct(num2cell(UTULRightZ, 1), compose('Subject%d', 1:size(UTULRightZ, 2)), 2);
    
    save datasetAcr2PelFrontalLeftX;
    save datasetAcr2PelTransLeftX;
    save datasetAcr2UTFrontalLeftX;
    save datasetAcr2UTTransLeftX;
    save datasetLLPelvisLeftX;
    save datasetLLPelvisLeftY;
    save datasetLLPelvisLeftZ;
    save datasetLTLLLeftX;
    save datasetLTLLLeftY;
    save datasetLTLLLeftZ;
    save datasetLTPelvisLeftX;
    save datasetLTPelvisLeftY;
    save datasetLTPelvisLeftZ;
    save datasetLTULLeftX;
    save datasetLTULLeftY;
    save datasetLTULLeftZ;
    save datasetULLLLeftX;
    save datasetULLLLeftY;
    save datasetULLLLeftZ;
    save datasetULPelvisLeftX;
    save datasetULPelvisLeftY;
    save datasetULPelvisLeftZ;
    save datasetUTLLLeftX;
    save datasetUTLLLeftY;
    save datasetUTLLLeftZ;
    save datasetUTLTLeftX;
    save datasetUTLTLeftY;
    save datasetUTLTLeftZ;
    save datasetUTPelvisLeftX;
    save datasetUTPelvisLeftY;
    save datasetUTPelvisLeftZ;
    save datasetUTULLeftX;
    save datasetUTULLeftY;
    save datasetUTULLeftZ;
    
    save datasetAcr2PelFrontalRightX;
    save datasetAcr2PelTransRightX;
    save datasetAcr2UTFrontalRightX;
    save datasetAcr2UTTransRightX;
    save datasetLLPelvisRightX;
    save datasetLLPelvisRightY;
    save datasetLLPelvisRightZ;
    save datasetLTLLRightX;
    save datasetLTLLRightY;
    save datasetLTLLRightZ;
    save datasetLTPelvisRightX;
    save datasetLTPelvisRightY;
    save datasetLTPelvisRightZ;
    save datasetLTULRightX;
    save datasetLTULRightY;
    save datasetLTULRightZ;
    save datasetULLLRightX;
    save datasetULLLRightY;
    save datasetULLLRightZ;
    save datasetULPelvisRightX;
    save datasetULPelvisRightY;
    save datasetULPelvisRightZ;
    save datasetUTLLRightX;
    save datasetUTLLRightY;
    save datasetUTLLRightZ;
    save datasetUTLTRightX;
    save datasetUTLTRightY;
    save datasetUTLTRightZ;
    save datasetUTPelvisRightX;
    save datasetUTPelvisRightY;
    save datasetUTPelvisRightZ;
    save datasetUTULRightX;
    save datasetUTULRightY;
    save datasetUTULRightZ;

end