function statTest

    %Female LBP (27 sub): 4 7 8 9 10 11 18 19 20 21 24 25 28 30 32 34 35 36 37 39 42
    %43 44 46 47 48 50
    %Female NLBP (21 sub): 2 3 6 12 15 16 22 23 26 31 33 38 40 41 45 51 52 55
    %56 57 58
    %z axial, y sagittal, x frontal
    data = load('datasetLLPelvisLeftX.mat','datasetLLPelvisLeftX');
    [YP,YNP] = deal([data.datasetLLPelvisLeftX.Subject4 data.datasetLLPelvisLeftX.Subject7 ...
        data.datasetLLPelvisLeftX.Subject8 data.datasetLLPelvisLeftX.Subject9 ...
        data.datasetLLPelvisLeftX.Subject10 data.datasetLLPelvisLeftX.Subject11 ...
        data.datasetLLPelvisLeftX.Subject18 data.datasetLLPelvisLeftX.Subject19 ...
        data.datasetLLPelvisLeftX.Subject20 data.datasetLLPelvisLeftX.Subject21 ...
        data.datasetLLPelvisLeftX.Subject24 data.datasetLLPelvisLeftX.Subject25 ...
        data.datasetLLPelvisLeftX.Subject28 data.datasetLLPelvisLeftX.Subject30 ...
        data.datasetLLPelvisLeftX.Subject32 data.datasetLLPelvisLeftX.Subject34 ...
        data.datasetLLPelvisLeftX.Subject35 data.datasetLLPelvisLeftX.Subject36 ...
        data.datasetLLPelvisLeftX.Subject37 data.datasetLLPelvisLeftX.Subject39 ...
        data.datasetLLPelvisLeftX.Subject42 data.datasetLLPelvisLeftX.Subject43 ...
        data.datasetLLPelvisLeftX.Subject44 data.datasetLLPelvisLeftX.Subject46 ...
        data.datasetLLPelvisLeftX.Subject47 data.datasetLLPelvisLeftX.Subject48 ...
        data.datasetLLPelvisLeftX.Subject50 ], ...
        [data.datasetLLPelvisLeftX.Subject2 data.datasetLLPelvisLeftX.Subject3 ...
        data.datasetLLPelvisLeftX.Subject6 data.datasetLLPelvisLeftX.Subject12 ...
        data.datasetLLPelvisLeftX.Subject15 data.datasetLLPelvisLeftX.Subject16 ...
        data.datasetLLPelvisLeftX.Subject22 data.datasetLLPelvisLeftX.Subject23 ...
        data.datasetLLPelvisLeftX.Subject26 data.datasetLLPelvisLeftX.Subject31 ...
        data.datasetLLPelvisLeftX.Subject33 data.datasetLLPelvisLeftX.Subject38 ...
        data.datasetLLPelvisLeftX.Subject40 data.datasetLLPelvisLeftX.Subject41 ...
        data.datasetLLPelvisLeftX.Subject45 data.datasetLLPelvisLeftX.Subject51 ...
        data.datasetLLPelvisLeftX.Subject52 data.datasetLLPelvisLeftX.Subject55 ...
        data.datasetLLPelvisLeftX.Subject56 data.datasetLLPelvisLeftX.Subject57 ...
        data.datasetLLPelvisLeftX.Subject58 ]);
    spm       = spm1d.stats.ttest2(YP', YNP');
    spmi      = spm.inference(0.05, 'two_tailed', false, 'interp',true);
    disp(spmi);

    close all
    spmi.plot();
    spmi.plot_threshold_label();
    spmi.plot_p_values();
    
end