function statTestWalkingCombined

    %Acr2UTTrans
    
    %AllSubjectsRightX
    data = load('datasetAcr2UTTransRightX.mat','datasetAcr2UTTransRightX');
    [YP,YNP] = deal([data.datasetAcr2UTTransRightX.Subject1 data.datasetAcr2UTTransRightX.Subject4 ...
        data.datasetAcr2UTTransRightX.Subject5 data.datasetAcr2UTTransRightX.Subject7 ...
        data.datasetAcr2UTTransRightX.Subject8 data.datasetAcr2UTTransRightX.Subject9 ...
        data.datasetAcr2UTTransRightX.Subject10 data.datasetAcr2UTTransRightX.Subject11 ...
        data.datasetAcr2UTTransRightX.Subject13 data.datasetAcr2UTTransRightX.Subject14 ...
        data.datasetAcr2UTTransRightX.Subject17 ...
        data.datasetAcr2UTTransRightX.Subject18 data.datasetAcr2UTTransRightX.Subject19 ...
        data.datasetAcr2UTTransRightX.Subject20 data.datasetAcr2UTTransRightX.Subject21 ...
        data.datasetAcr2UTTransRightX.Subject24 data.datasetAcr2UTTransRightX.Subject25 ...
        data.datasetAcr2UTTransRightX.Subject27 data.datasetAcr2UTTransRightX.Subject28 ...
        data.datasetAcr2UTTransRightX.Subject29 data.datasetAcr2UTTransRightX.Subject30 ...
        data.datasetAcr2UTTransRightX.Subject32 data.datasetAcr2UTTransRightX.Subject34 ...
        data.datasetAcr2UTTransRightX.Subject35 data.datasetAcr2UTTransRightX.Subject36 ...
        data.datasetAcr2UTTransRightX.Subject37 data.datasetAcr2UTTransRightX.Subject39 ...
        data.datasetAcr2UTTransRightX.Subject42 data.datasetAcr2UTTransRightX.Subject43 ...
        data.datasetAcr2UTTransRightX.Subject44 data.datasetAcr2UTTransRightX.Subject46 ...
        data.datasetAcr2UTTransRightX.Subject47 data.datasetAcr2UTTransRightX.Subject48 ...
        data.datasetAcr2UTTransRightX.Subject49 data.datasetAcr2UTTransRightX.Subject50...
        data.datasetAcr2UTTransRightX.Subject54 ], ...
        [data.datasetAcr2UTTransRightX.Subject2 data.datasetAcr2UTTransRightX.Subject3 ...
        data.datasetAcr2UTTransRightX.Subject6 data.datasetAcr2UTTransRightX.Subject12 ...
        data.datasetAcr2UTTransRightX.Subject15 data.datasetAcr2UTTransRightX.Subject16 ...
        data.datasetAcr2UTTransRightX.Subject22 data.datasetAcr2UTTransRightX.Subject23 ...
        data.datasetAcr2UTTransRightX.Subject26 data.datasetAcr2UTTransRightX.Subject31 ...
        data.datasetAcr2UTTransRightX.Subject33 data.datasetAcr2UTTransRightX.Subject38 ...
        data.datasetAcr2UTTransRightX.Subject40 data.datasetAcr2UTTransRightX.Subject41 ...
        data.datasetAcr2UTTransRightX.Subject45 data.datasetAcr2UTTransRightX.Subject51 ...
        data.datasetAcr2UTTransRightX.Subject52 data.datasetAcr2UTTransRightX.Subject53 data.datasetAcr2UTTransRightX.Subject55 ...
        data.datasetAcr2UTTransRightX.Subject56 data.datasetAcr2UTTransRightX.Subject57 ...
        data.datasetAcr2UTTransRightX.Subject58 data.datasetAcr2UTTransRightX.Subject59 data.datasetAcr2UTTransRightX.Subject60 ]);
    spm       = spm1d.stats.ttest2(YP', YNP');
    spmi      = spm.inference(0.05, 'two_tailed', true, 'interp',true);
    disp(spmi);
    close all
    subplot(1,2,1);
    spmi.plot();
    title('Two-Sample T-Test');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Variance','FontSize',12,'FontWeight','bold');
    spmi.plot_threshold_label();
    spmi.plot_p_values();  
    subplot(1,2,2);
    YPmean = mean (YP');
    YPstd = std (YP');
    numYPPts = length (YPmean);
    YNPmean = mean (YNP');
    YNPstd = std (YNP');
    numYNPPts = length (YNPmean);
    p1 = plot (1:numYPPts, YPmean, 'b','LineWidth',2);
    hold on
	plot (1:numYPPts, YPmean + YPstd, 'b--');
	plot (1:numYPPts, YPmean - YPstd, 'b--');
    p2 = plot (1:numYNPPts, YNPmean, 'r','LineWidth',2);
	plot (1:numYNPPts, YNPmean + YNPstd, 'r--');
    plot (1:numYNPPts, YNPmean - YNPstd, 'r--');
    xlim ([1 numYPPts]);
    legend([p1 p2],'Pain','No Pain', 'Location','northwest')
    title('Mean and SD');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Angle','FontSize',12,'FontWeight','bold');    
    savefig('Acr2UTTransX_Right_AllSubjects');
    saveas(gcf,'Acr2UTTransX_Right_AllSubjects.png');
    
%     %AllSubjectsRightY
%     data = load('datasetAcr2UTTransRightY.mat','datasetAcr2UTTransRightY');
%     [YP,YNP] = deal([data.datasetAcr2UTTransRightY.Subject1 data.datasetAcr2UTTransRightY.Subject4 ...
%         data.datasetAcr2UTTransRightY.Subject5 data.datasetAcr2UTTransRightY.Subject7 ...
%         data.datasetAcr2UTTransRightY.Subject8 data.datasetAcr2UTTransRightY.Subject9 ...
%         data.datasetAcr2UTTransRightY.Subject10 data.datasetAcr2UTTransRightY.Subject11 ...
%         data.datasetAcr2UTTransRightY.Subject13 data.datasetAcr2UTTransRightY.Subject14 ...
%         data.datasetAcr2UTTransRightY.Subject17 ...
%         data.datasetAcr2UTTransRightY.Subject18 data.datasetAcr2UTTransRightY.Subject19 ...
%         data.datasetAcr2UTTransRightY.Subject20 data.datasetAcr2UTTransRightY.Subject21 ...
%         data.datasetAcr2UTTransRightY.Subject24 data.datasetAcr2UTTransRightY.Subject25 ...
%         data.datasetAcr2UTTransRightY.Subject27 data.datasetAcr2UTTransRightY.Subject28 ...
%         data.datasetAcr2UTTransRightY.Subject29 data.datasetAcr2UTTransRightY.Subject30 ...
%         data.datasetAcr2UTTransRightY.Subject32 data.datasetAcr2UTTransRightY.Subject34 ...
%         data.datasetAcr2UTTransRightY.Subject35 data.datasetAcr2UTTransRightY.Subject36 ...
%         data.datasetAcr2UTTransRightY.Subject37 data.datasetAcr2UTTransRightY.Subject39 ...
%         data.datasetAcr2UTTransRightY.Subject42 data.datasetAcr2UTTransRightY.Subject43 ...
%         data.datasetAcr2UTTransRightY.Subject44 data.datasetAcr2UTTransRightY.Subject46 ...
%         data.datasetAcr2UTTransRightY.Subject47 data.datasetAcr2UTTransRightY.Subject48 ...
%         data.datasetAcr2UTTransRightY.Subject49 data.datasetAcr2UTTransRightY.Subject50...
%         data.datasetAcr2UTTransRightY.Subject54 ], ...
%         [data.datasetAcr2UTTransRightY.Subject2 data.datasetAcr2UTTransRightY.Subject3 ...
%         data.datasetAcr2UTTransRightY.Subject6 data.datasetAcr2UTTransRightY.Subject12 ...
%         data.datasetAcr2UTTransRightY.Subject15 data.datasetAcr2UTTransRightY.Subject16 ...
%         data.datasetAcr2UTTransRightY.Subject22 data.datasetAcr2UTTransRightY.Subject23 ...
%         data.datasetAcr2UTTransRightY.Subject26 data.datasetAcr2UTTransRightY.Subject31 ...
%         data.datasetAcr2UTTransRightY.Subject33 data.datasetAcr2UTTransRightY.Subject38 ...
%         data.datasetAcr2UTTransRightY.Subject40 data.datasetAcr2UTTransRightY.Subject41 ...
%         data.datasetAcr2UTTransRightY.Subject45 data.datasetAcr2UTTransRightY.Subject51 ...
%         data.datasetAcr2UTTransRightY.Subject52 data.datasetAcr2UTTransRightY.Subject53 data.datasetAcr2UTTransRightY.Subject55 ...
%         data.datasetAcr2UTTransRightY.Subject56 data.datasetAcr2UTTransRightY.Subject57 ...
%         data.datasetAcr2UTTransRightY.Subject58 data.datasetAcr2UTTransRightY.Subject59 data.datasetAcr2UTTransRightY.Subject60 ]);
%     spm       = spm1d.stats.ttest2(YP', YNP');
%     spmi      = spm.inference(0.05, 'two_tailed', true, 'interp',true);
%     disp(spmi);
%     close all
%     subplot(1,2,1);
%     spmi.plot();
%     title('Two-Sample T-Test');
%     xlabel('Time (%)','FontSize',12,'FontWeight','bold');
%     ylabel('Variance','FontSize',12,'FontWeight','bold');
%     spmi.plot_threshold_label();
%     spmi.plot_p_values();  
%     subplot(1,2,2);
%     YPmean = mean (YP');
%     YPstd = std (YP');
%     numYPPts = length (YPmean);
%     YNPmean = mean (YNP');
%     YNPstd = std (YNP');
%     numYNPPts = length (YNPmean);
%     p1 = plot (1:numYPPts, YPmean, 'b','LineWidth',2);
%     hold on
% 	plot (1:numYPPts, YPmean + YPstd, 'b--');
% 	plot (1:numYPPts, YPmean - YPstd, 'b--');
%     p2 = plot (1:numYNPPts, YNPmean, 'r','LineWidth',2);
% 	plot (1:numYNPPts, YNPmean + YNPstd, 'r--');
%     plot (1:numYNPPts, YNPmean - YNPstd, 'r--');
%     xlim ([1 numYPPts]);
%     legend([p1 p2],'Pain','No Pain', 'Location','northwest')
%     title('Mean and SD');
%     xlabel('Time (%)','FontSize',12,'FontWeight','bold');
%     ylabel('Angle','FontSize',12,'FontWeight','bold');    
%     savefig('Acr2UTTransY_Right_AllSubjects');
%     saveas(gcf,'Acr2UTTransY_Right_AllSubjects.png');
% 
%     %AllSubjectsRightZ
%     data = load('datasetAcr2UTTransRightZ.mat','datasetAcr2UTTransRightZ');
%     [YP,YNP] = deal([data.datasetAcr2UTTransRightZ.Subject1 data.datasetAcr2UTTransRightZ.Subject4 ...
%         data.datasetAcr2UTTransRightZ.Subject5 data.datasetAcr2UTTransRightZ.Subject7 ...
%         data.datasetAcr2UTTransRightZ.Subject8 data.datasetAcr2UTTransRightZ.Subject9 ...
%         data.datasetAcr2UTTransRightZ.Subject10 data.datasetAcr2UTTransRightZ.Subject11 ...
%         data.datasetAcr2UTTransRightZ.Subject13 data.datasetAcr2UTTransRightZ.Subject14 ...
%         data.datasetAcr2UTTransRightZ.Subject17 ...
%         data.datasetAcr2UTTransRightZ.Subject18 data.datasetAcr2UTTransRightZ.Subject19 ...
%         data.datasetAcr2UTTransRightZ.Subject20 data.datasetAcr2UTTransRightZ.Subject21 ...
%         data.datasetAcr2UTTransRightZ.Subject24 data.datasetAcr2UTTransRightZ.Subject25 ...
%         data.datasetAcr2UTTransRightZ.Subject27 data.datasetAcr2UTTransRightZ.Subject28 ...
%         data.datasetAcr2UTTransRightZ.Subject29 data.datasetAcr2UTTransRightZ.Subject30 ...
%         data.datasetAcr2UTTransRightZ.Subject32 data.datasetAcr2UTTransRightZ.Subject34 ...
%         data.datasetAcr2UTTransRightZ.Subject35 data.datasetAcr2UTTransRightZ.Subject36 ...
%         data.datasetAcr2UTTransRightZ.Subject37 data.datasetAcr2UTTransRightZ.Subject39 ...
%         data.datasetAcr2UTTransRightZ.Subject42 data.datasetAcr2UTTransRightZ.Subject43 ...
%         data.datasetAcr2UTTransRightZ.Subject44 data.datasetAcr2UTTransRightZ.Subject46 ...
%         data.datasetAcr2UTTransRightZ.Subject47 data.datasetAcr2UTTransRightZ.Subject48 ...
%         data.datasetAcr2UTTransRightZ.Subject49 data.datasetAcr2UTTransRightZ.Subject50...
%         data.datasetAcr2UTTransRightZ.Subject54 ], ...
%         [data.datasetAcr2UTTransRightZ.Subject2 data.datasetAcr2UTTransRightZ.Subject3 ...
%         data.datasetAcr2UTTransRightZ.Subject6 data.datasetAcr2UTTransRightZ.Subject12 ...
%         data.datasetAcr2UTTransRightZ.Subject15 data.datasetAcr2UTTransRightZ.Subject16 ...
%         data.datasetAcr2UTTransRightZ.Subject22 data.datasetAcr2UTTransRightZ.Subject23 ...
%         data.datasetAcr2UTTransRightZ.Subject26 data.datasetAcr2UTTransRightZ.Subject31 ...
%         data.datasetAcr2UTTransRightZ.Subject33 data.datasetAcr2UTTransRightZ.Subject38 ...
%         data.datasetAcr2UTTransRightZ.Subject40 data.datasetAcr2UTTransRightZ.Subject41 ...
%         data.datasetAcr2UTTransRightZ.Subject45 data.datasetAcr2UTTransRightZ.Subject51 ...
%         data.datasetAcr2UTTransRightZ.Subject52 data.datasetAcr2UTTransRightZ.Subject53 data.datasetAcr2UTTransRightZ.Subject55 ...
%         data.datasetAcr2UTTransRightZ.Subject56 data.datasetAcr2UTTransRightZ.Subject57 ...
%         data.datasetAcr2UTTransRightZ.Subject58 data.datasetAcr2UTTransRightZ.Subject59 data.datasetAcr2UTTransRightZ.Subject60 ]);
%     spm       = spm1d.stats.ttest2(YP', YNP');
%     spmi      = spm.inference(0.05, 'two_tailed', true, 'interp',true);
%     disp(spmi);
%     close all
%     subplot(1,2,1);
%     spmi.plot();
%     title('Two-Sample T-Test');
%     xlabel('Time (%)','FontSize',12,'FontWeight','bold');
%     ylabel('Variance','FontSize',12,'FontWeight','bold');
%     spmi.plot_threshold_label();
%     spmi.plot_p_values();  
%     subplot(1,2,2);
%     YPmean = mean (YP');
%     YPstd = std (YP');
%     numYPPts = length (YPmean);
%     YNPmean = mean (YNP');
%     YNPstd = std (YNP');
%     numYNPPts = length (YNPmean);
%     p1 = plot (1:numYPPts, YPmean, 'b','LineWidth',2);
%     hold on
% 	plot (1:numYPPts, YPmean + YPstd, 'b--');
% 	plot (1:numYPPts, YPmean - YPstd, 'b--');
%     p2 = plot (1:numYNPPts, YNPmean, 'r','LineWidth',2);
% 	plot (1:numYNPPts, YNPmean + YNPstd, 'r--');
%     plot (1:numYNPPts, YNPmean - YNPstd, 'r--');
%     xlim ([1 numYPPts]);
%     legend([p1 p2],'Pain','No Pain', 'Location','northwest')
%     title('Mean and SD');
%     xlabel('Time (%)','FontSize',12,'FontWeight','bold');
%     ylabel('Angle','FontSize',12,'FontWeight','bold');    
%     savefig('Acr2UTTransZ_Right_AllSubjects');
%     saveas(gcf,'Acr2UTTransZ_Right_AllSubjects.png');
    
    %AllSubjectsLeftX
    data = load('datasetAcr2UTTransLeftX.mat','datasetAcr2UTTransLeftX');
    [YP,YNP] = deal([data.datasetAcr2UTTransLeftX.Subject1 data.datasetAcr2UTTransLeftX.Subject4 ...
        data.datasetAcr2UTTransLeftX.Subject5 data.datasetAcr2UTTransLeftX.Subject7 ...
        data.datasetAcr2UTTransLeftX.Subject8 data.datasetAcr2UTTransLeftX.Subject9 ...
        data.datasetAcr2UTTransLeftX.Subject10 data.datasetAcr2UTTransLeftX.Subject11 ...
        data.datasetAcr2UTTransLeftX.Subject13 data.datasetAcr2UTTransLeftX.Subject14 ...
        data.datasetAcr2UTTransLeftX.Subject17 ...
        data.datasetAcr2UTTransLeftX.Subject18 data.datasetAcr2UTTransLeftX.Subject19 ...
        data.datasetAcr2UTTransLeftX.Subject20 data.datasetAcr2UTTransLeftX.Subject21 ...
        data.datasetAcr2UTTransLeftX.Subject24 data.datasetAcr2UTTransLeftX.Subject25 ...
        data.datasetAcr2UTTransLeftX.Subject27 data.datasetAcr2UTTransLeftX.Subject28 ...
        data.datasetAcr2UTTransLeftX.Subject29 data.datasetAcr2UTTransLeftX.Subject30 ...
        data.datasetAcr2UTTransLeftX.Subject32 data.datasetAcr2UTTransLeftX.Subject34 ...
        data.datasetAcr2UTTransLeftX.Subject35 data.datasetAcr2UTTransLeftX.Subject36 ...
        data.datasetAcr2UTTransLeftX.Subject37 data.datasetAcr2UTTransLeftX.Subject39 ...
        data.datasetAcr2UTTransLeftX.Subject42 data.datasetAcr2UTTransLeftX.Subject43 ...
        data.datasetAcr2UTTransLeftX.Subject44 data.datasetAcr2UTTransLeftX.Subject46 ...
        data.datasetAcr2UTTransLeftX.Subject47 data.datasetAcr2UTTransLeftX.Subject48 ...
        data.datasetAcr2UTTransLeftX.Subject49 data.datasetAcr2UTTransLeftX.Subject50...
        data.datasetAcr2UTTransLeftX.Subject54 ], ...
        [data.datasetAcr2UTTransLeftX.Subject2 data.datasetAcr2UTTransLeftX.Subject3 ...
        data.datasetAcr2UTTransLeftX.Subject6 data.datasetAcr2UTTransLeftX.Subject12 ...
        data.datasetAcr2UTTransLeftX.Subject15 data.datasetAcr2UTTransLeftX.Subject16 ...
        data.datasetAcr2UTTransLeftX.Subject22 data.datasetAcr2UTTransLeftX.Subject23 ...
        data.datasetAcr2UTTransLeftX.Subject26 data.datasetAcr2UTTransLeftX.Subject31 ...
        data.datasetAcr2UTTransLeftX.Subject33 data.datasetAcr2UTTransLeftX.Subject38 ...
        data.datasetAcr2UTTransLeftX.Subject40 data.datasetAcr2UTTransLeftX.Subject41 ...
        data.datasetAcr2UTTransLeftX.Subject45 data.datasetAcr2UTTransLeftX.Subject51 ...
        data.datasetAcr2UTTransLeftX.Subject52 data.datasetAcr2UTTransLeftX.Subject53 data.datasetAcr2UTTransLeftX.Subject55 ...
        data.datasetAcr2UTTransLeftX.Subject56 data.datasetAcr2UTTransLeftX.Subject57 ...
        data.datasetAcr2UTTransLeftX.Subject58 data.datasetAcr2UTTransLeftX.Subject59 data.datasetAcr2UTTransLeftX.Subject60 ]);
    spm       = spm1d.stats.ttest2(YP', YNP');
    spmi      = spm.inference(0.05, 'two_tailed', true, 'interp',true);
    disp(spmi);
    close all
    subplot(1,2,1);
    spmi.plot();
    title('Two-Sample T-Test');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Variance','FontSize',12,'FontWeight','bold');
    spmi.plot_threshold_label();
    spmi.plot_p_values();  
    subplot(1,2,2);
    YPmean = mean (YP');
    YPstd = std (YP');
    numYPPts = length (YPmean);
    YNPmean = mean (YNP');
    YNPstd = std (YNP');
    numYNPPts = length (YNPmean);
    p1 = plot (1:numYPPts, YPmean, 'b','LineWidth',2);
    hold on
	plot (1:numYPPts, YPmean + YPstd, 'b--');
	plot (1:numYPPts, YPmean - YPstd, 'b--');
    p2 = plot (1:numYNPPts, YNPmean, 'r','LineWidth',2);
	plot (1:numYNPPts, YNPmean + YNPstd, 'r--');
    plot (1:numYNPPts, YNPmean - YNPstd, 'r--');
    xlim ([1 numYPPts]);
    legend([p1 p2],'Pain','No Pain', 'Location','northwest')
    title('Mean and SD');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Angle','FontSize',12,'FontWeight','bold');    
    savefig('Acr2UTTransX_Left_AllSubjects');
    saveas(gcf,'Acr2UTTransX_Left_AllSubjects.png');
    
%     %AllSubjectsLeftY
%     data = load('datasetAcr2UTTransLeftY.mat','datasetAcr2UTTransLeftY');
%     [YP,YNP] = deal([data.datasetAcr2UTTransLeftY.Subject1 data.datasetAcr2UTTransLeftY.Subject4 ...
%         data.datasetAcr2UTTransLeftY.Subject5 data.datasetAcr2UTTransLeftY.Subject7 ...
%         data.datasetAcr2UTTransLeftY.Subject8 data.datasetAcr2UTTransLeftY.Subject9 ...
%         data.datasetAcr2UTTransLeftY.Subject10 data.datasetAcr2UTTransLeftY.Subject11 ...
%         data.datasetAcr2UTTransLeftY.Subject13 data.datasetAcr2UTTransLeftY.Subject14 ...
%         data.datasetAcr2UTTransLeftY.Subject17 ...
%         data.datasetAcr2UTTransLeftY.Subject18 data.datasetAcr2UTTransLeftY.Subject19 ...
%         data.datasetAcr2UTTransLeftY.Subject20 data.datasetAcr2UTTransLeftY.Subject21 ...
%         data.datasetAcr2UTTransLeftY.Subject24 data.datasetAcr2UTTransLeftY.Subject25 ...
%         data.datasetAcr2UTTransLeftY.Subject27 data.datasetAcr2UTTransLeftY.Subject28 ...
%         data.datasetAcr2UTTransLeftY.Subject29 data.datasetAcr2UTTransLeftY.Subject30 ...
%         data.datasetAcr2UTTransLeftY.Subject32 data.datasetAcr2UTTransLeftY.Subject34 ...
%         data.datasetAcr2UTTransLeftY.Subject35 data.datasetAcr2UTTransLeftY.Subject36 ...
%         data.datasetAcr2UTTransLeftY.Subject37 data.datasetAcr2UTTransLeftY.Subject39 ...
%         data.datasetAcr2UTTransLeftY.Subject42 data.datasetAcr2UTTransLeftY.Subject43 ...
%         data.datasetAcr2UTTransLeftY.Subject44 data.datasetAcr2UTTransLeftY.Subject46 ...
%         data.datasetAcr2UTTransLeftY.Subject47 data.datasetAcr2UTTransLeftY.Subject48 ...
%         data.datasetAcr2UTTransLeftY.Subject49 data.datasetAcr2UTTransLeftY.Subject50...
%         data.datasetAcr2UTTransLeftY.Subject54 ], ...
%         [data.datasetAcr2UTTransLeftY.Subject2 data.datasetAcr2UTTransLeftY.Subject3 ...
%         data.datasetAcr2UTTransLeftY.Subject6 data.datasetAcr2UTTransLeftY.Subject12 ...
%         data.datasetAcr2UTTransLeftY.Subject15 data.datasetAcr2UTTransLeftY.Subject16 ...
%         data.datasetAcr2UTTransLeftY.Subject22 data.datasetAcr2UTTransLeftY.Subject23 ...
%         data.datasetAcr2UTTransLeftY.Subject26 data.datasetAcr2UTTransLeftY.Subject31 ...
%         data.datasetAcr2UTTransLeftY.Subject33 data.datasetAcr2UTTransLeftY.Subject38 ...
%         data.datasetAcr2UTTransLeftY.Subject40 data.datasetAcr2UTTransLeftY.Subject41 ...
%         data.datasetAcr2UTTransLeftY.Subject45 data.datasetAcr2UTTransLeftY.Subject51 ...
%         data.datasetAcr2UTTransLeftY.Subject52 data.datasetAcr2UTTransLeftY.Subject53 data.datasetAcr2UTTransLeftY.Subject55 ...
%         data.datasetAcr2UTTransLeftY.Subject56 data.datasetAcr2UTTransLeftY.Subject57 ...
%         data.datasetAcr2UTTransLeftY.Subject58 data.datasetAcr2UTTransLeftY.Subject59 data.datasetAcr2UTTransLeftY.Subject60 ]);
%     spm       = spm1d.stats.ttest2(YP', YNP');
%     spmi      = spm.inference(0.05, 'two_tailed', true, 'interp',true);
%     disp(spmi);
%     close all
%     subplot(1,2,1);
%     spmi.plot();
%     title('Two-Sample T-Test');
%     xlabel('Time (%)','FontSize',12,'FontWeight','bold');
%     ylabel('Variance','FontSize',12,'FontWeight','bold');
%     spmi.plot_threshold_label();
%     spmi.plot_p_values();  
%     subplot(1,2,2);
%     YPmean = mean (YP');
%     YPstd = std (YP');
%     numYPPts = length (YPmean);
%     YNPmean = mean (YNP');
%     YNPstd = std (YNP');
%     numYNPPts = length (YNPmean);
%     p1 = plot (1:numYPPts, YPmean, 'b','LineWidth',2);
%     hold on
% 	plot (1:numYPPts, YPmean + YPstd, 'b--');
% 	plot (1:numYPPts, YPmean - YPstd, 'b--');
%     p2 = plot (1:numYNPPts, YNPmean, 'r','LineWidth',2);
% 	plot (1:numYNPPts, YNPmean + YNPstd, 'r--');
%     plot (1:numYNPPts, YNPmean - YNPstd, 'r--');
%     xlim ([1 numYPPts]);
%     legend([p1 p2],'Pain','No Pain', 'Location','northwest')
%     title('Mean and SD');
%     xlabel('Time (%)','FontSize',12,'FontWeight','bold');
%     ylabel('Angle','FontSize',12,'FontWeight','bold');    
%     savefig('Acr2UTTransY_Left_AllSubjects');
%     saveas(gcf,'Acr2UTTransY_Left_AllSubjects.png');
% 
%     %AllSubjectsLeftZ
%     data = load('datasetAcr2UTTransLeftZ.mat','datasetAcr2UTTransLeftZ');
%     [YP,YNP] = deal([data.datasetAcr2UTTransLeftZ.Subject1 data.datasetAcr2UTTransLeftZ.Subject4 ...
%         data.datasetAcr2UTTransLeftZ.Subject5 data.datasetAcr2UTTransLeftZ.Subject7 ...
%         data.datasetAcr2UTTransLeftZ.Subject8 data.datasetAcr2UTTransLeftZ.Subject9 ...
%         data.datasetAcr2UTTransLeftZ.Subject10 data.datasetAcr2UTTransLeftZ.Subject11 ...
%         data.datasetAcr2UTTransLeftZ.Subject13 data.datasetAcr2UTTransLeftZ.Subject14 ...
%         data.datasetAcr2UTTransLeftZ.Subject17 ...
%         data.datasetAcr2UTTransLeftZ.Subject18 data.datasetAcr2UTTransLeftZ.Subject19 ...
%         data.datasetAcr2UTTransLeftZ.Subject20 data.datasetAcr2UTTransLeftZ.Subject21 ...
%         data.datasetAcr2UTTransLeftZ.Subject24 data.datasetAcr2UTTransLeftZ.Subject25 ...
%         data.datasetAcr2UTTransLeftZ.Subject27 data.datasetAcr2UTTransLeftZ.Subject28 ...
%         data.datasetAcr2UTTransLeftZ.Subject29 data.datasetAcr2UTTransLeftZ.Subject30 ...
%         data.datasetAcr2UTTransLeftZ.Subject32 data.datasetAcr2UTTransLeftZ.Subject34 ...
%         data.datasetAcr2UTTransLeftZ.Subject35 data.datasetAcr2UTTransLeftZ.Subject36 ...
%         data.datasetAcr2UTTransLeftZ.Subject37 data.datasetAcr2UTTransLeftZ.Subject39 ...
%         data.datasetAcr2UTTransLeftZ.Subject42 data.datasetAcr2UTTransLeftZ.Subject43 ...
%         data.datasetAcr2UTTransLeftZ.Subject44 data.datasetAcr2UTTransLeftZ.Subject46 ...
%         data.datasetAcr2UTTransLeftZ.Subject47 data.datasetAcr2UTTransLeftZ.Subject48 ...
%         data.datasetAcr2UTTransLeftZ.Subject49 data.datasetAcr2UTTransLeftZ.Subject50...
%         data.datasetAcr2UTTransLeftZ.Subject54 ], ...
%         [data.datasetAcr2UTTransLeftZ.Subject2 data.datasetAcr2UTTransLeftZ.Subject3 ...
%         data.datasetAcr2UTTransLeftZ.Subject6 data.datasetAcr2UTTransLeftZ.Subject12 ...
%         data.datasetAcr2UTTransLeftZ.Subject15 data.datasetAcr2UTTransLeftZ.Subject16 ...
%         data.datasetAcr2UTTransLeftZ.Subject22 data.datasetAcr2UTTransLeftZ.Subject23 ...
%         data.datasetAcr2UTTransLeftZ.Subject26 data.datasetAcr2UTTransLeftZ.Subject31 ...
%         data.datasetAcr2UTTransLeftZ.Subject33 data.datasetAcr2UTTransLeftZ.Subject38 ...
%         data.datasetAcr2UTTransLeftZ.Subject40 data.datasetAcr2UTTransLeftZ.Subject41 ...
%         data.datasetAcr2UTTransLeftZ.Subject45 data.datasetAcr2UTTransLeftZ.Subject51 ...
%         data.datasetAcr2UTTransLeftZ.Subject52 data.datasetAcr2UTTransLeftZ.Subject53 data.datasetAcr2UTTransLeftZ.Subject55 ...
%         data.datasetAcr2UTTransLeftZ.Subject56 data.datasetAcr2UTTransLeftZ.Subject57 ...
%         data.datasetAcr2UTTransLeftZ.Subject58 data.datasetAcr2UTTransLeftZ.Subject59 data.datasetAcr2UTTransLeftZ.Subject60 ]);
%     spm       = spm1d.stats.ttest2(YP', YNP');
%     spmi      = spm.inference(0.05, 'two_tailed', true, 'interp',true);
%     disp(spmi);
%     close all
%     subplot(1,2,1);
%     spmi.plot();
%     title('Two-Sample T-Test');
%     xlabel('Time (%)','FontSize',12,'FontWeight','bold');
%     ylabel('Variance','FontSize',12,'FontWeight','bold');
%     spmi.plot_threshold_label();
%     spmi.plot_p_values();  
%     subplot(1,2,2);
%     YPmean = mean (YP');
%     YPstd = std (YP');
%     numYPPts = length (YPmean);
%     YNPmean = mean (YNP');
%     YNPstd = std (YNP');
%     numYNPPts = length (YNPmean);
%     p1 = plot (1:numYPPts, YPmean, 'b','LineWidth',2);
%     hold on
% 	plot (1:numYPPts, YPmean + YPstd, 'b--');
% 	plot (1:numYPPts, YPmean - YPstd, 'b--');
%     p2 = plot (1:numYNPPts, YNPmean, 'r','LineWidth',2);
% 	plot (1:numYNPPts, YNPmean + YNPstd, 'r--');
%     plot (1:numYNPPts, YNPmean - YNPstd, 'r--');
%     xlim ([1 numYPPts]);
%     legend([p1 p2],'Pain','No Pain', 'Location','northwest')
%     title('Mean and SD');
%     xlabel('Time (%)','FontSize',12,'FontWeight','bold');
%     ylabel('Angle','FontSize',12,'FontWeight','bold');    
%     savefig('Acr2UTTransZ_Left_AllSubjects');
%     saveas(gcf,'Acr2UTTransZ_Left_AllSubjects.png');
    
    %FemaleLeftX
    data = load('datasetAcr2UTTransLeftX.mat','datasetAcr2UTTransLeftX');
    [YP,YNP] = deal([data.datasetAcr2UTTransLeftX.Subject4 data.datasetAcr2UTTransLeftX.Subject7 ...
        data.datasetAcr2UTTransLeftX.Subject8 data.datasetAcr2UTTransLeftX.Subject9 ...
        data.datasetAcr2UTTransLeftX.Subject10 data.datasetAcr2UTTransLeftX.Subject11 ...
        data.datasetAcr2UTTransLeftX.Subject18 data.datasetAcr2UTTransLeftX.Subject19 ...
        data.datasetAcr2UTTransLeftX.Subject20 data.datasetAcr2UTTransLeftX.Subject21 ...
        data.datasetAcr2UTTransLeftX.Subject24 data.datasetAcr2UTTransLeftX.Subject25 ...
        data.datasetAcr2UTTransLeftX.Subject28 data.datasetAcr2UTTransLeftX.Subject30 ...
        data.datasetAcr2UTTransLeftX.Subject32 data.datasetAcr2UTTransLeftX.Subject34 ...
        data.datasetAcr2UTTransLeftX.Subject35 data.datasetAcr2UTTransLeftX.Subject36 ...
        data.datasetAcr2UTTransLeftX.Subject37 data.datasetAcr2UTTransLeftX.Subject39 ...
        data.datasetAcr2UTTransLeftX.Subject42 data.datasetAcr2UTTransLeftX.Subject43 ...
        data.datasetAcr2UTTransLeftX.Subject44 data.datasetAcr2UTTransLeftX.Subject46 ...
        data.datasetAcr2UTTransLeftX.Subject47 data.datasetAcr2UTTransLeftX.Subject48 ...
        data.datasetAcr2UTTransLeftX.Subject50 ], ...
        [data.datasetAcr2UTTransLeftX.Subject2 data.datasetAcr2UTTransLeftX.Subject3 ...
        data.datasetAcr2UTTransLeftX.Subject6 data.datasetAcr2UTTransLeftX.Subject12 ...
        data.datasetAcr2UTTransLeftX.Subject15 data.datasetAcr2UTTransLeftX.Subject16 ...
        data.datasetAcr2UTTransLeftX.Subject22 data.datasetAcr2UTTransLeftX.Subject23 ...
        data.datasetAcr2UTTransLeftX.Subject26 data.datasetAcr2UTTransLeftX.Subject31 ...
        data.datasetAcr2UTTransLeftX.Subject33 data.datasetAcr2UTTransLeftX.Subject38 ...
        data.datasetAcr2UTTransLeftX.Subject40 data.datasetAcr2UTTransLeftX.Subject41 ...
        data.datasetAcr2UTTransLeftX.Subject45 data.datasetAcr2UTTransLeftX.Subject51 ...
        data.datasetAcr2UTTransLeftX.Subject52 data.datasetAcr2UTTransLeftX.Subject55 ...
        data.datasetAcr2UTTransLeftX.Subject56 data.datasetAcr2UTTransLeftX.Subject57 ...
        data.datasetAcr2UTTransLeftX.Subject58 ]);
    spm       = spm1d.stats.ttest2(YP', YNP');
    spmi      = spm.inference(0.05, 'two_tailed', true, 'interp',true);
    disp(spmi);
    close all
    subplot(1,2,1);
    spmi.plot();
    title('Two-Sample T-Test');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Variance','FontSize',12,'FontWeight','bold');
    spmi.plot_threshold_label();
    spmi.plot_p_values();  
    subplot(1,2,2);
    YPmean = mean (YP');
    YPstd = std (YP');
    numYPPts = length (YPmean);
    YNPmean = mean (YNP');
    YNPstd = std (YNP');
    numYNPPts = length (YNPmean);
    p1 = plot (1:numYPPts, YPmean, 'b','LineWidth',2);
    hold on
	plot (1:numYPPts, YPmean + YPstd, 'b--');
	plot (1:numYPPts, YPmean - YPstd, 'b--');
    p2 = plot (1:numYNPPts, YNPmean, 'r','LineWidth',2);
	plot (1:numYNPPts, YNPmean + YNPstd, 'r--');
    plot (1:numYNPPts, YNPmean - YNPstd, 'r--');
    xlim ([1 numYPPts]);
    legend([p1 p2],'Pain','No Pain', 'Location','northwest')
    title('Mean and SD');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Angle','FontSize',12,'FontWeight','bold');    
    savefig('Acr2UTTransX_Left_Females');
    saveas(gcf,'Acr2UTTransX_Left_Females.png');
    
%     %FemaleLeftY
%     data = load('datasetAcr2UTTransLeftY.mat','datasetAcr2UTTransLeftY');
%     [YP,YNP] = deal([data.datasetAcr2UTTransLeftY.Subject4 data.datasetAcr2UTTransLeftY.Subject7 ...
%         data.datasetAcr2UTTransLeftY.Subject8 data.datasetAcr2UTTransLeftY.Subject9 ...
%         data.datasetAcr2UTTransLeftY.Subject10 data.datasetAcr2UTTransLeftY.Subject11 ...
%         data.datasetAcr2UTTransLeftY.Subject18 data.datasetAcr2UTTransLeftY.Subject19 ...
%         data.datasetAcr2UTTransLeftY.Subject20 data.datasetAcr2UTTransLeftY.Subject21 ...
%         data.datasetAcr2UTTransLeftY.Subject24 data.datasetAcr2UTTransLeftY.Subject25 ...
%         data.datasetAcr2UTTransLeftY.Subject28 data.datasetAcr2UTTransLeftY.Subject30 ...
%         data.datasetAcr2UTTransLeftY.Subject32 data.datasetAcr2UTTransLeftY.Subject34 ...
%         data.datasetAcr2UTTransLeftY.Subject35 data.datasetAcr2UTTransLeftY.Subject36 ...
%         data.datasetAcr2UTTransLeftY.Subject37 data.datasetAcr2UTTransLeftY.Subject39 ...
%         data.datasetAcr2UTTransLeftY.Subject42 data.datasetAcr2UTTransLeftY.Subject43 ...
%         data.datasetAcr2UTTransLeftY.Subject44 data.datasetAcr2UTTransLeftY.Subject46 ...
%         data.datasetAcr2UTTransLeftY.Subject47 data.datasetAcr2UTTransLeftY.Subject48 ...
%         data.datasetAcr2UTTransLeftY.Subject50 ], ...
%         [data.datasetAcr2UTTransLeftY.Subject2 data.datasetAcr2UTTransLeftY.Subject3 ...
%         data.datasetAcr2UTTransLeftY.Subject6 data.datasetAcr2UTTransLeftY.Subject12 ...
%         data.datasetAcr2UTTransLeftY.Subject15 data.datasetAcr2UTTransLeftY.Subject16 ...
%         data.datasetAcr2UTTransLeftY.Subject22 data.datasetAcr2UTTransLeftY.Subject23 ...
%         data.datasetAcr2UTTransLeftY.Subject26 data.datasetAcr2UTTransLeftY.Subject31 ...
%         data.datasetAcr2UTTransLeftY.Subject33 data.datasetAcr2UTTransLeftY.Subject38 ...
%         data.datasetAcr2UTTransLeftY.Subject40 data.datasetAcr2UTTransLeftY.Subject41 ...
%         data.datasetAcr2UTTransLeftY.Subject45 data.datasetAcr2UTTransLeftY.Subject51 ...
%         data.datasetAcr2UTTransLeftY.Subject52 data.datasetAcr2UTTransLeftY.Subject55 ...
%         data.datasetAcr2UTTransLeftY.Subject56 data.datasetAcr2UTTransLeftY.Subject57 ...
%         data.datasetAcr2UTTransLeftY.Subject58 ]);
%     spm       = spm1d.stats.ttest2(YP', YNP');
%     spmi      = spm.inference(0.05, 'two_tailed', true, 'interp',true);
%     disp(spmi);
%     close all
%     subplot(1,2,1);
%     spmi.plot();
%     title('Two-Sample T-Test');
%     xlabel('Time (%)','FontSize',12,'FontWeight','bold');
%     ylabel('Variance','FontSize',12,'FontWeight','bold');
%     spmi.plot_threshold_label();
%     spmi.plot_p_values();  
%     subplot(1,2,2);
%     YPmean = mean (YP');
%     YPstd = std (YP');
%     numYPPts = length (YPmean);
%     YNPmean = mean (YNP');
%     YNPstd = std (YNP');
%     numYNPPts = length (YNPmean);
%     p1 = plot (1:numYPPts, YPmean, 'b','LineWidth',2);
%     hold on
% 	plot (1:numYPPts, YPmean + YPstd, 'b--');
% 	plot (1:numYPPts, YPmean - YPstd, 'b--');
%     p2 = plot (1:numYNPPts, YNPmean, 'r','LineWidth',2);
% 	plot (1:numYNPPts, YNPmean + YNPstd, 'r--');
%     plot (1:numYNPPts, YNPmean - YNPstd, 'r--');
%     xlim ([1 numYPPts]);
%     legend([p1 p2],'Pain','No Pain', 'Location','northwest')
%     title('Mean and SD');
%     xlabel('Time (%)','FontSize',12,'FontWeight','bold');
%     ylabel('Angle','FontSize',12,'FontWeight','bold');    
%     savefig('Acr2UTTransY_Left_Females');
%     saveas(gcf,'Acr2UTTransY_Left_Females.png');
%     
%     %FemaleLeftZ
%     data = load('datasetAcr2UTTransLeftZ.mat','datasetAcr2UTTransLeftZ');
%     [YP,YNP] = deal([data.datasetAcr2UTTransLeftZ.Subject4 data.datasetAcr2UTTransLeftZ.Subject7 ...
%         data.datasetAcr2UTTransLeftZ.Subject8 data.datasetAcr2UTTransLeftZ.Subject9 ...
%         data.datasetAcr2UTTransLeftZ.Subject10 data.datasetAcr2UTTransLeftZ.Subject11 ...
%         data.datasetAcr2UTTransLeftZ.Subject18 data.datasetAcr2UTTransLeftZ.Subject19 ...
%         data.datasetAcr2UTTransLeftZ.Subject20 data.datasetAcr2UTTransLeftZ.Subject21 ...
%         data.datasetAcr2UTTransLeftZ.Subject24 data.datasetAcr2UTTransLeftZ.Subject25 ...
%         data.datasetAcr2UTTransLeftZ.Subject28 data.datasetAcr2UTTransLeftZ.Subject30 ...
%         data.datasetAcr2UTTransLeftZ.Subject32 data.datasetAcr2UTTransLeftZ.Subject34 ...
%         data.datasetAcr2UTTransLeftZ.Subject35 data.datasetAcr2UTTransLeftZ.Subject36 ...
%         data.datasetAcr2UTTransLeftZ.Subject37 data.datasetAcr2UTTransLeftZ.Subject39 ...
%         data.datasetAcr2UTTransLeftZ.Subject42 data.datasetAcr2UTTransLeftZ.Subject43 ...
%         data.datasetAcr2UTTransLeftZ.Subject44 data.datasetAcr2UTTransLeftZ.Subject46 ...
%         data.datasetAcr2UTTransLeftZ.Subject47 data.datasetAcr2UTTransLeftZ.Subject48 ...
%         data.datasetAcr2UTTransLeftZ.Subject50 ], ...
%         [data.datasetAcr2UTTransLeftZ.Subject2 data.datasetAcr2UTTransLeftZ.Subject3 ...
%         data.datasetAcr2UTTransLeftZ.Subject6 data.datasetAcr2UTTransLeftZ.Subject12 ...
%         data.datasetAcr2UTTransLeftZ.Subject15 data.datasetAcr2UTTransLeftZ.Subject16 ...
%         data.datasetAcr2UTTransLeftZ.Subject22 data.datasetAcr2UTTransLeftZ.Subject23 ...
%         data.datasetAcr2UTTransLeftZ.Subject26 data.datasetAcr2UTTransLeftZ.Subject31 ...
%         data.datasetAcr2UTTransLeftZ.Subject33 data.datasetAcr2UTTransLeftZ.Subject38 ...
%         data.datasetAcr2UTTransLeftZ.Subject40 data.datasetAcr2UTTransLeftZ.Subject41 ...
%         data.datasetAcr2UTTransLeftZ.Subject45 data.datasetAcr2UTTransLeftZ.Subject51 ...
%         data.datasetAcr2UTTransLeftZ.Subject52 data.datasetAcr2UTTransLeftZ.Subject55 ...
%         data.datasetAcr2UTTransLeftZ.Subject56 data.datasetAcr2UTTransLeftZ.Subject57 ...
%         data.datasetAcr2UTTransLeftZ.Subject58 ]);
%     spm       = spm1d.stats.ttest2(YP', YNP');
%     spmi      = spm.inference(0.05, 'two_tailed', true, 'interp',true);
%     disp(spmi);
%     close all
%     subplot(1,2,1);
%     spmi.plot();
%     title('Two-Sample T-Test');
%     xlabel('Time (%)','FontSize',12,'FontWeight','bold');
%     ylabel('Variance','FontSize',12,'FontWeight','bold');
%     spmi.plot_threshold_label();
%     spmi.plot_p_values();  
%     subplot(1,2,2);
%     YPmean = mean (YP');
%     YPstd = std (YP');
%     numYPPts = length (YPmean);
%     YNPmean = mean (YNP');
%     YNPstd = std (YNP');
%     numYNPPts = length (YNPmean);
%     p1 = plot (1:numYPPts, YPmean, 'b','LineWidth',2);
%     hold on
% 	plot (1:numYPPts, YPmean + YPstd, 'b--');
% 	plot (1:numYPPts, YPmean - YPstd, 'b--');
%     p2 = plot (1:numYNPPts, YNPmean, 'r','LineWidth',2);
% 	plot (1:numYNPPts, YNPmean + YNPstd, 'r--');
%     plot (1:numYNPPts, YNPmean - YNPstd, 'r--');
%     xlim ([1 numYPPts]);
%     legend([p1 p2],'Pain','No Pain', 'Location','northwest')
%     title('Mean and SD');
%     xlabel('Time (%)','FontSize',12,'FontWeight','bold');
%     ylabel('Angle','FontSize',12,'FontWeight','bold');    
%     savefig('Acr2UTTransZ_Left_Females');
%     saveas(gcf,'Acr2UTTransZ_Left_Females.png');
    
    %FemaleRightX
    data = load('datasetAcr2UTTransRightX.mat','datasetAcr2UTTransRightX');
    [YP,YNP] = deal([data.datasetAcr2UTTransRightX.Subject4 data.datasetAcr2UTTransRightX.Subject7 ...
        data.datasetAcr2UTTransRightX.Subject8 data.datasetAcr2UTTransRightX.Subject9 ...
        data.datasetAcr2UTTransRightX.Subject10 data.datasetAcr2UTTransRightX.Subject11 ...
        data.datasetAcr2UTTransRightX.Subject18 data.datasetAcr2UTTransRightX.Subject19 ...
        data.datasetAcr2UTTransRightX.Subject20 data.datasetAcr2UTTransRightX.Subject21 ...
        data.datasetAcr2UTTransRightX.Subject24 data.datasetAcr2UTTransRightX.Subject25 ...
        data.datasetAcr2UTTransRightX.Subject28 data.datasetAcr2UTTransRightX.Subject30 ...
        data.datasetAcr2UTTransRightX.Subject32 data.datasetAcr2UTTransRightX.Subject34 ...
        data.datasetAcr2UTTransRightX.Subject35 data.datasetAcr2UTTransRightX.Subject36 ...
        data.datasetAcr2UTTransRightX.Subject37 data.datasetAcr2UTTransRightX.Subject39 ...
        data.datasetAcr2UTTransRightX.Subject42 data.datasetAcr2UTTransRightX.Subject43 ...
        data.datasetAcr2UTTransRightX.Subject44 data.datasetAcr2UTTransRightX.Subject46 ...
        data.datasetAcr2UTTransRightX.Subject47 data.datasetAcr2UTTransRightX.Subject48 ...
        data.datasetAcr2UTTransRightX.Subject50 ], ...
        [data.datasetAcr2UTTransRightX.Subject2 data.datasetAcr2UTTransRightX.Subject3 ...
        data.datasetAcr2UTTransRightX.Subject6 data.datasetAcr2UTTransRightX.Subject12 ...
        data.datasetAcr2UTTransRightX.Subject15 data.datasetAcr2UTTransRightX.Subject16 ...
        data.datasetAcr2UTTransRightX.Subject22 data.datasetAcr2UTTransRightX.Subject23 ...
        data.datasetAcr2UTTransRightX.Subject26 data.datasetAcr2UTTransRightX.Subject31 ...
        data.datasetAcr2UTTransRightX.Subject33 data.datasetAcr2UTTransRightX.Subject38 ...
        data.datasetAcr2UTTransRightX.Subject40 data.datasetAcr2UTTransRightX.Subject41 ...
        data.datasetAcr2UTTransRightX.Subject45 data.datasetAcr2UTTransRightX.Subject51 ...
        data.datasetAcr2UTTransRightX.Subject52 data.datasetAcr2UTTransRightX.Subject55 ...
        data.datasetAcr2UTTransRightX.Subject56 data.datasetAcr2UTTransRightX.Subject57 ...
        data.datasetAcr2UTTransRightX.Subject58 ]);
    spm       = spm1d.stats.ttest2(YP', YNP');
    spmi      = spm.inference(0.05, 'two_tailed', true, 'interp',true);
    disp(spmi);
    close all
    subplot(1,2,1);
    spmi.plot();
    title('Two-Sample T-Test');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Variance','FontSize',12,'FontWeight','bold');
    spmi.plot_threshold_label();
    spmi.plot_p_values();  
    subplot(1,2,2);
    YPmean = mean (YP');
    YPstd = std (YP');
    numYPPts = length (YPmean);
    YNPmean = mean (YNP');
    YNPstd = std (YNP');
    numYNPPts = length (YNPmean);
    p1 = plot (1:numYPPts, YPmean, 'b','LineWidth',2);
    hold on
	plot (1:numYPPts, YPmean + YPstd, 'b--');
	plot (1:numYPPts, YPmean - YPstd, 'b--');
    p2 = plot (1:numYNPPts, YNPmean, 'r','LineWidth',2);
	plot (1:numYNPPts, YNPmean + YNPstd, 'r--');
    plot (1:numYNPPts, YNPmean - YNPstd, 'r--');
    xlim ([1 numYPPts]);
    legend([p1 p2],'Pain','No Pain', 'Location','northwest')
    title('Mean and SD');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Angle','FontSize',12,'FontWeight','bold');    
    savefig('Acr2UTTransX_Right_Females');
    saveas(gcf,'Acr2UTTransX_Right_Females.png');
    
%     %FemaleRightY
%     data = load('datasetAcr2UTTransRightY.mat','datasetAcr2UTTransRightY');
%     [YP,YNP] = deal([data.datasetAcr2UTTransRightY.Subject4 data.datasetAcr2UTTransRightY.Subject7 ...
%         data.datasetAcr2UTTransRightY.Subject8 data.datasetAcr2UTTransRightY.Subject9 ...
%         data.datasetAcr2UTTransRightY.Subject10 data.datasetAcr2UTTransRightY.Subject11 ...
%         data.datasetAcr2UTTransRightY.Subject18 data.datasetAcr2UTTransRightY.Subject19 ...
%         data.datasetAcr2UTTransRightY.Subject20 data.datasetAcr2UTTransRightY.Subject21 ...
%         data.datasetAcr2UTTransRightY.Subject24 data.datasetAcr2UTTransRightY.Subject25 ...
%         data.datasetAcr2UTTransRightY.Subject28 data.datasetAcr2UTTransRightY.Subject30 ...
%         data.datasetAcr2UTTransRightY.Subject32 data.datasetAcr2UTTransRightY.Subject34 ...
%         data.datasetAcr2UTTransRightY.Subject35 data.datasetAcr2UTTransRightY.Subject36 ...
%         data.datasetAcr2UTTransRightY.Subject37 data.datasetAcr2UTTransRightY.Subject39 ...
%         data.datasetAcr2UTTransRightY.Subject42 data.datasetAcr2UTTransRightY.Subject43 ...
%         data.datasetAcr2UTTransRightY.Subject44 data.datasetAcr2UTTransRightY.Subject46 ...
%         data.datasetAcr2UTTransRightY.Subject47 data.datasetAcr2UTTransRightY.Subject48 ...
%         data.datasetAcr2UTTransRightY.Subject50 ], ...
%         [data.datasetAcr2UTTransRightY.Subject2 data.datasetAcr2UTTransRightY.Subject3 ...
%         data.datasetAcr2UTTransRightY.Subject6 data.datasetAcr2UTTransRightY.Subject12 ...
%         data.datasetAcr2UTTransRightY.Subject15 data.datasetAcr2UTTransRightY.Subject16 ...
%         data.datasetAcr2UTTransRightY.Subject22 data.datasetAcr2UTTransRightY.Subject23 ...
%         data.datasetAcr2UTTransRightY.Subject26 data.datasetAcr2UTTransRightY.Subject31 ...
%         data.datasetAcr2UTTransRightY.Subject33 data.datasetAcr2UTTransRightY.Subject38 ...
%         data.datasetAcr2UTTransRightY.Subject40 data.datasetAcr2UTTransRightY.Subject41 ...
%         data.datasetAcr2UTTransRightY.Subject45 data.datasetAcr2UTTransRightY.Subject51 ...
%         data.datasetAcr2UTTransRightY.Subject52 data.datasetAcr2UTTransRightY.Subject55 ...
%         data.datasetAcr2UTTransRightY.Subject56 data.datasetAcr2UTTransRightY.Subject57 ...
%         data.datasetAcr2UTTransRightY.Subject58 ]);
%     spm       = spm1d.stats.ttest2(YP', YNP');
%     spmi      = spm.inference(0.05, 'two_tailed', true, 'interp',true);
%     disp(spmi);
%     close all
%     subplot(1,2,1);
%     spmi.plot();
%     title('Two-Sample T-Test');
%     xlabel('Time (%)','FontSize',12,'FontWeight','bold');
%     ylabel('Variance','FontSize',12,'FontWeight','bold');
%     spmi.plot_threshold_label();
%     spmi.plot_p_values();  
%     subplot(1,2,2);
%     YPmean = mean (YP');
%     YPstd = std (YP');
%     numYPPts = length (YPmean);
%     YNPmean = mean (YNP');
%     YNPstd = std (YNP');
%     numYNPPts = length (YNPmean);
%     p1 = plot (1:numYPPts, YPmean, 'b','LineWidth',2);
%     hold on
% 	plot (1:numYPPts, YPmean + YPstd, 'b--');
% 	plot (1:numYPPts, YPmean - YPstd, 'b--');
%     p2 = plot (1:numYNPPts, YNPmean, 'r','LineWidth',2);
% 	plot (1:numYNPPts, YNPmean + YNPstd, 'r--');
%     plot (1:numYNPPts, YNPmean - YNPstd, 'r--');
%     xlim ([1 numYPPts]);
%     legend([p1 p2],'Pain','No Pain', 'Location','northwest')
%     title('Mean and SD');
%     xlabel('Time (%)','FontSize',12,'FontWeight','bold');
%     ylabel('Angle','FontSize',12,'FontWeight','bold');    
%     savefig('Acr2UTTransY_Right_Females');
%     saveas(gcf,'Acr2UTTransY_Right_Females.png');
%     
%     %FemaleRightZ
%     data = load('datasetAcr2UTTransRightZ.mat','datasetAcr2UTTransRightZ');
%     [YP,YNP] = deal([data.datasetAcr2UTTransRightZ.Subject4 data.datasetAcr2UTTransRightZ.Subject7 ...
%         data.datasetAcr2UTTransRightZ.Subject8 data.datasetAcr2UTTransRightZ.Subject9 ...
%         data.datasetAcr2UTTransRightZ.Subject10 data.datasetAcr2UTTransRightZ.Subject11 ...
%         data.datasetAcr2UTTransRightZ.Subject18 data.datasetAcr2UTTransRightZ.Subject19 ...
%         data.datasetAcr2UTTransRightZ.Subject20 data.datasetAcr2UTTransRightZ.Subject21 ...
%         data.datasetAcr2UTTransRightZ.Subject24 data.datasetAcr2UTTransRightZ.Subject25 ...
%         data.datasetAcr2UTTransRightZ.Subject28 data.datasetAcr2UTTransRightZ.Subject30 ...
%         data.datasetAcr2UTTransRightZ.Subject32 data.datasetAcr2UTTransRightZ.Subject34 ...
%         data.datasetAcr2UTTransRightZ.Subject35 data.datasetAcr2UTTransRightZ.Subject36 ...
%         data.datasetAcr2UTTransRightZ.Subject37 data.datasetAcr2UTTransRightZ.Subject39 ...
%         data.datasetAcr2UTTransRightZ.Subject42 data.datasetAcr2UTTransRightZ.Subject43 ...
%         data.datasetAcr2UTTransRightZ.Subject44 data.datasetAcr2UTTransRightZ.Subject46 ...
%         data.datasetAcr2UTTransRightZ.Subject47 data.datasetAcr2UTTransRightZ.Subject48 ...
%         data.datasetAcr2UTTransRightZ.Subject50 ], ...
%         [data.datasetAcr2UTTransRightZ.Subject2 data.datasetAcr2UTTransRightZ.Subject3 ...
%         data.datasetAcr2UTTransRightZ.Subject6 data.datasetAcr2UTTransRightZ.Subject12 ...
%         data.datasetAcr2UTTransRightZ.Subject15 data.datasetAcr2UTTransRightZ.Subject16 ...
%         data.datasetAcr2UTTransRightZ.Subject22 data.datasetAcr2UTTransRightZ.Subject23 ...
%         data.datasetAcr2UTTransRightZ.Subject26 data.datasetAcr2UTTransRightZ.Subject31 ...
%         data.datasetAcr2UTTransRightZ.Subject33 data.datasetAcr2UTTransRightZ.Subject38 ...
%         data.datasetAcr2UTTransRightZ.Subject40 data.datasetAcr2UTTransRightZ.Subject41 ...
%         data.datasetAcr2UTTransRightZ.Subject45 data.datasetAcr2UTTransRightZ.Subject51 ...
%         data.datasetAcr2UTTransRightZ.Subject52 data.datasetAcr2UTTransRightZ.Subject55 ...
%         data.datasetAcr2UTTransRightZ.Subject56 data.datasetAcr2UTTransRightZ.Subject57 ...
%         data.datasetAcr2UTTransRightZ.Subject58 ]);
%     spm       = spm1d.stats.ttest2(YP', YNP');
%     spmi      = spm.inference(0.05, 'two_tailed', true, 'interp',true);
%     disp(spmi);
%     close all
%     subplot(1,2,1);
%     spmi.plot();
%     title('Two-Sample T-Test');
%     xlabel('Time (%)','FontSize',12,'FontWeight','bold');
%     ylabel('Variance','FontSize',12,'FontWeight','bold');
%     spmi.plot_threshold_label();
%     spmi.plot_p_values();  
%     subplot(1,2,2);
%     YPmean = mean (YP');
%     YPstd = std (YP');
%     numYPPts = length (YPmean);
%     YNPmean = mean (YNP');
%     YNPstd = std (YNP');
%     numYNPPts = length (YNPmean);
%     p1 = plot (1:numYPPts, YPmean, 'b','LineWidth',2);
%     hold on
% 	plot (1:numYPPts, YPmean + YPstd, 'b--');
% 	plot (1:numYPPts, YPmean - YPstd, 'b--');
%     p2 = plot (1:numYNPPts, YNPmean, 'r','LineWidth',2);
% 	plot (1:numYNPPts, YNPmean + YNPstd, 'r--');
%     plot (1:numYNPPts, YNPmean - YNPstd, 'r--');
%     xlim ([1 numYPPts]);
%     legend([p1 p2],'Pain','No Pain', 'Location','northwest')
%     title('Mean and SD');
%     xlabel('Time (%)','FontSize',12,'FontWeight','bold');
%     ylabel('Angle','FontSize',12,'FontWeight','bold');    
%     savefig('Acr2UTTransZ_Right_Females');
%     saveas(gcf,'Acr2UTTransZ_Right_Females.png');
    
end