function prepareFMTTests

    masterData = load('arrangedArabLData.mat','arrangedArabLData');
    
    LLLabX_ArabL = masterData.arrangedArabLData(:,:,1);
    LLLabY_ArabL = masterData.arrangedArabLData(:,:,2);
    LLLabZ_ArabL = masterData.arrangedArabLData(:,:,3);
    LLPelX_ArabL = masterData.arrangedArabLData(:,:,4);
    LLPelY_ArabL = masterData.arrangedArabLData(:,:,5);
    LLPelZ_ArabL = masterData.arrangedArabLData(:,:,6);
    LTLabX_ArabL = masterData.arrangedArabLData(:,:,7);
    LTLabY_ArabL = masterData.arrangedArabLData(:,:,8);
    LTLabZ_ArabL = masterData.arrangedArabLData(:,:,9);
    LTLLX_ArabL = masterData.arrangedArabLData(:,:,10);
    LTLLY_ArabL = masterData.arrangedArabLData(:,:,11);
    LTLLZ_ArabL = masterData.arrangedArabLData(:,:,12);
    LTPelX_ArabL = masterData.arrangedArabLData(:,:,13);
    LTPelY_ArabL = masterData.arrangedArabLData(:,:,14);
    LTPelZ_ArabL = masterData.arrangedArabLData(:,:,15);
    LTULX_ArabL = masterData.arrangedArabLData(:,:,16);
    LTULY_ArabL = masterData.arrangedArabLData(:,:,17);
    LTULZ_ArabL = masterData.arrangedArabLData(:,:,18);
    PelLabX_ArabL = masterData.arrangedArabLData(:,:,19);
    PelLabY_ArabL = masterData.arrangedArabLData(:,:,20);
    PelLabZ_ArabL = masterData.arrangedArabLData(:,:,21);
    TrunkLabX_ArabL = masterData.arrangedArabLData(:,:,22);
    TrunkLabY_ArabL = masterData.arrangedArabLData(:,:,23);
    TrunkLabZ_ArabL = masterData.arrangedArabLData(:,:,24);
    ULLabX_ArabL = masterData.arrangedArabLData(:,:,25);
    ULLabY_ArabL = masterData.arrangedArabLData(:,:,26);
    ULLabZ_ArabL = masterData.arrangedArabLData(:,:,27);
    ULLLX_ArabL = masterData.arrangedArabLData(:,:,28);
    ULLLY_ArabL = masterData.arrangedArabLData(:,:,29);
    ULLLZ_ArabL = masterData.arrangedArabLData(:,:,30);
    ULPelX_ArabL = masterData.arrangedArabLData(:,:,31);
    ULPelY_ArabL = masterData.arrangedArabLData(:,:,32);
    ULPelZ_ArabL = masterData.arrangedArabLData(:,:,33);
    UTLabX_ArabL = masterData.arrangedArabLData(:,:,34);
    UTLabY_ArabL = masterData.arrangedArabLData(:,:,35);
    UTLabZ_ArabL = masterData.arrangedArabLData(:,:,36);
    UTLLX_ArabL = masterData.arrangedArabLData(:,:,37);
    UTLLY_ArabL = masterData.arrangedArabLData(:,:,38);
    UTLLZ_ArabL = masterData.arrangedArabLData(:,:,39);
    UTLTX_ArabL = masterData.arrangedArabLData(:,:,40);
    UTLTY_ArabL = masterData.arrangedArabLData(:,:,41);
    UTLTZ_ArabL = masterData.arrangedArabLData(:,:,42);
    UTPelX_ArabL = masterData.arrangedArabLData(:,:,43);
    UTPelY_ArabL = masterData.arrangedArabLData(:,:,44);
    UTPelZ_ArabL = masterData.arrangedArabLData(:,:,45);
    UTULX_ArabL = masterData.arrangedArabLData(:,:,46);
    UTULY_ArabL = masterData.arrangedArabLData(:,:,47);
    UTULZ_ArabL = masterData.arrangedArabLData(:,:,48);

    datasetLLLabX_ArabL = cell2struct(num2cell(LLLabX_ArabL, 1), compose('Subject%d', 1:size(LLLabX_ArabL, 2)), 2);
    datasetLLLabY_ArabL = cell2struct(num2cell(LLLabY_ArabL, 1), compose('Subject%d', 1:size(LLLabY_ArabL, 2)), 2);
    datasetLLLabZ_ArabL = cell2struct(num2cell(LLLabZ_ArabL, 1), compose('Subject%d', 1:size(LLLabZ_ArabL, 2)), 2);
    datasetLLPelX_ArabL = cell2struct(num2cell(LLPelX_ArabL, 1), compose('Subject%d', 1:size(LLPelX_ArabL, 2)), 2);
    datasetLLPelY_ArabL = cell2struct(num2cell(LLPelY_ArabL, 1), compose('Subject%d', 1:size(LLPelY_ArabL, 2)), 2);
    datasetLLPelZ_ArabL = cell2struct(num2cell(LLPelZ_ArabL, 1), compose('Subject%d', 1:size(LLPelZ_ArabL, 2)), 2);
    datasetLTLabX_ArabL = cell2struct(num2cell(LTLabX_ArabL, 1), compose('Subject%d', 1:size(LTLabX_ArabL, 2)), 2);
    datasetLTLabY_ArabL = cell2struct(num2cell(LTLabY_ArabL, 1), compose('Subject%d', 1:size(LTLabY_ArabL, 2)), 2);
    datasetLTLabZ_ArabL = cell2struct(num2cell(LTLabZ_ArabL, 1), compose('Subject%d', 1:size(LTLabZ_ArabL, 2)), 2);
    datasetLTLLX_ArabL = cell2struct(num2cell(LTLLX_ArabL, 1), compose('Subject%d', 1:size(LTLLX_ArabL, 2)), 2);
    datasetLTLLY_ArabL = cell2struct(num2cell(LTLLY_ArabL, 1), compose('Subject%d', 1:size(LTLLY_ArabL, 2)), 2);
    datasetLTLLZ_ArabL = cell2struct(num2cell(LTLLZ_ArabL, 1), compose('Subject%d', 1:size(LTLLZ_ArabL, 2)), 2);
    datasetLTPelX_ArabL = cell2struct(num2cell(LTPelX_ArabL, 1), compose('Subject%d', 1:size(LTPelX_ArabL, 2)), 2);
    datasetLTPelY_ArabL = cell2struct(num2cell(LTPelY_ArabL, 1), compose('Subject%d', 1:size(LTPelY_ArabL, 2)), 2);
    datasetLTPelZ_ArabL = cell2struct(num2cell(LTPelZ_ArabL, 1), compose('Subject%d', 1:size(LTPelZ_ArabL, 2)), 2);
    datasetLTULX_ArabL = cell2struct(num2cell(LTULX_ArabL, 1), compose('Subject%d', 1:size(LTULX_ArabL, 2)), 2);
    datasetLTULY_ArabL = cell2struct(num2cell(LTULY_ArabL, 1), compose('Subject%d', 1:size(LTULY_ArabL, 2)), 2);    
    datasetLTULZ_ArabL = cell2struct(num2cell(LTULZ_ArabL, 1), compose('Subject%d', 1:size(LTULZ_ArabL, 2)), 2);
    datasetPelLabX_ArabL = cell2struct(num2cell(PelLabX_ArabL, 1), compose('Subject%d', 1:size(PelLabX_ArabL, 2)), 2);
    datasetPelLabY_ArabL = cell2struct(num2cell(PelLabY_ArabL, 1), compose('Subject%d', 1:size(PelLabY_ArabL, 2)), 2);
    datasetPelLabZ_ArabL = cell2struct(num2cell(PelLabZ_ArabL, 1), compose('Subject%d', 1:size(PelLabZ_ArabL, 2)), 2);
    datasetTrunkLabX_ArabL = cell2struct(num2cell(TrunkLabX_ArabL, 1), compose('Subject%d', 1:size(TrunkLabX_ArabL, 2)), 2);    
    datasetTrunkLabY_ArabL = cell2struct(num2cell(TrunkLabY_ArabL, 1), compose('Subject%d', 1:size(TrunkLabY_ArabL, 2)), 2);
    datasetTrunkLabZ_ArabL = cell2struct(num2cell(TrunkLabZ_ArabL, 1), compose('Subject%d', 1:size(TrunkLabZ_ArabL, 2)), 2);
    datasetULLabX_ArabL = cell2struct(num2cell(ULLabX_ArabL, 1), compose('Subject%d', 1:size(ULLabX_ArabL, 2)), 2);
    datasetULLabY_ArabL = cell2struct(num2cell(ULLabY_ArabL, 1), compose('Subject%d', 1:size(ULLabY_ArabL, 2)), 2);
    datasetULLabZ_ArabL = cell2struct(num2cell(ULLabZ_ArabL, 1), compose('Subject%d', 1:size(ULLabZ_ArabL, 2)), 2);
    datasetULLLX_ArabL = cell2struct(num2cell(ULLLX_ArabL, 1), compose('Subject%d', 1:size(ULLLX_ArabL, 2)), 2);
    datasetULLLY_ArabL = cell2struct(num2cell(ULLLY_ArabL, 1), compose('Subject%d', 1:size(ULLLY_ArabL, 2)), 2);
    datasetULLLZ_ArabL = cell2struct(num2cell(ULLLZ_ArabL, 1), compose('Subject%d', 1:size(ULLLZ_ArabL, 2)), 2);
    datasetULPelX_ArabL = cell2struct(num2cell(ULPelX_ArabL, 1), compose('Subject%d', 1:size(ULPelX_ArabL, 2)), 2);
    datasetULPelY_ArabL = cell2struct(num2cell(ULPelY_ArabL, 1), compose('Subject%d', 1:size(ULPelY_ArabL, 2)), 2);
    datasetULPelZ_ArabL = cell2struct(num2cell(ULPelZ_ArabL, 1), compose('Subject%d', 1:size(ULPelZ_ArabL, 2)), 2);
    datasetUTLabX_ArabL = cell2struct(num2cell(UTLabX_ArabL, 1), compose('Subject%d', 1:size(UTLabX_ArabL, 2)), 2);
    datasetUTLabY_ArabL = cell2struct(num2cell(UTLabY_ArabL, 1), compose('Subject%d', 1:size(UTLabY_ArabL, 2)), 2);
    datasetUTLabZ_ArabL = cell2struct(num2cell(UTLabZ_ArabL, 1), compose('Subject%d', 1:size(UTLabZ_ArabL, 2)), 2);
    datasetUTLLX_ArabL = cell2struct(num2cell(UTLLX_ArabL, 1), compose('Subject%d', 1:size(UTLLX_ArabL, 2)), 2);
    datasetUTLLY_ArabL = cell2struct(num2cell(UTLLY_ArabL, 1), compose('Subject%d', 1:size(UTLLY_ArabL, 2)), 2);
    datasetUTLLZ_ArabL = cell2struct(num2cell(UTLLZ_ArabL, 1), compose('Subject%d', 1:size(UTLLZ_ArabL, 2)), 2);
    datasetUTLTX_ArabL = cell2struct(num2cell(UTLTX_ArabL, 1), compose('Subject%d', 1:size(UTLTX_ArabL, 2)), 2);
    datasetUTLTY_ArabL = cell2struct(num2cell(UTLTY_ArabL, 1), compose('Subject%d', 1:size(UTLTY_ArabL, 2)), 2);
    datasetUTLTZ_ArabL = cell2struct(num2cell(UTLTZ_ArabL, 1), compose('Subject%d', 1:size(UTLTZ_ArabL, 2)), 2);
    datasetUTPelX_ArabL = cell2struct(num2cell(UTPelX_ArabL, 1), compose('Subject%d', 1:size(UTPelX_ArabL, 2)), 2);
    datasetUTPelY_ArabL = cell2struct(num2cell(UTPelY_ArabL, 1), compose('Subject%d', 1:size(UTPelY_ArabL, 2)), 2);
    datasetUTPelZ_ArabL = cell2struct(num2cell(UTPelZ_ArabL, 1), compose('Subject%d', 1:size(UTPelZ_ArabL, 2)), 2);
    datasetUTULX_ArabL = cell2struct(num2cell(UTULX_ArabL, 1), compose('Subject%d', 1:size(UTULX_ArabL, 2)), 2);
    datasetUTULY_ArabL = cell2struct(num2cell(UTULY_ArabL, 1), compose('Subject%d', 1:size(UTULY_ArabL, 2)), 2);
    datasetUTULZ_ArabL = cell2struct(num2cell(UTULZ_ArabL, 1), compose('Subject%d', 1:size(UTULZ_ArabL, 2)), 2);
    
    masterData1 = load('arrangedArabRData.mat','arrangedArabRData');
    
    LLLabX_ArabR = masterData1.arrangedArabRData(:,:,1);
    LLLabY_ArabR = masterData1.arrangedArabRData(:,:,2);
    LLLabZ_ArabR = masterData1.arrangedArabRData(:,:,3);
    LLPelX_ArabR = masterData1.arrangedArabRData(:,:,4);
    LLPelY_ArabR = masterData1.arrangedArabRData(:,:,5);
    LLPelZ_ArabR = masterData1.arrangedArabRData(:,:,6);
    LTLabX_ArabR = masterData1.arrangedArabRData(:,:,7);
    LTLabY_ArabR = masterData1.arrangedArabRData(:,:,8);
    LTLabZ_ArabR = masterData1.arrangedArabRData(:,:,9);
    LTLLX_ArabR = masterData1.arrangedArabRData(:,:,10);
    LTLLY_ArabR = masterData1.arrangedArabRData(:,:,11);
    LTLLZ_ArabR = masterData1.arrangedArabRData(:,:,12);
    LTPelX_ArabR = masterData1.arrangedArabRData(:,:,13);
    LTPelY_ArabR = masterData1.arrangedArabRData(:,:,14);
    LTPelZ_ArabR = masterData1.arrangedArabRData(:,:,15);
    LTULX_ArabR = masterData1.arrangedArabRData(:,:,16);
    LTULY_ArabR = masterData1.arrangedArabRData(:,:,17);
    LTULZ_ArabR = masterData1.arrangedArabRData(:,:,18);
    PelLabX_ArabR = masterData1.arrangedArabRData(:,:,19);
    PelLabY_ArabR = masterData1.arrangedArabRData(:,:,20);
    PelLabZ_ArabR = masterData1.arrangedArabRData(:,:,21);
    TrunkLabX_ArabR = masterData1.arrangedArabRData(:,:,22);
    TrunkLabY_ArabR = masterData1.arrangedArabRData(:,:,23);
    TrunkLabZ_ArabR = masterData1.arrangedArabRData(:,:,24);
    ULLabX_ArabR = masterData1.arrangedArabRData(:,:,25);
    ULLabY_ArabR = masterData1.arrangedArabRData(:,:,26);
    ULLabZ_ArabR = masterData1.arrangedArabRData(:,:,27);
    ULLLX_ArabR = masterData1.arrangedArabRData(:,:,28);
    ULLLY_ArabR = masterData1.arrangedArabRData(:,:,29);
    ULLLZ_ArabR = masterData1.arrangedArabRData(:,:,30);
    ULPelX_ArabR = masterData1.arrangedArabRData(:,:,31);
    ULPelY_ArabR = masterData1.arrangedArabRData(:,:,32);
    ULPelZ_ArabR = masterData1.arrangedArabRData(:,:,33);
    UTLabX_ArabR = masterData1.arrangedArabRData(:,:,34);
    UTLabY_ArabR = masterData1.arrangedArabRData(:,:,35);
    UTLabZ_ArabR = masterData1.arrangedArabRData(:,:,36);
    UTLLX_ArabR = masterData1.arrangedArabRData(:,:,37);
    UTLLY_ArabR = masterData1.arrangedArabRData(:,:,38);
    UTLLZ_ArabR = masterData1.arrangedArabRData(:,:,39);
    UTLTX_ArabR = masterData1.arrangedArabRData(:,:,40);
    UTLTY_ArabR = masterData1.arrangedArabRData(:,:,41);
    UTLTZ_ArabR = masterData1.arrangedArabRData(:,:,42);
    UTPelX_ArabR = masterData1.arrangedArabRData(:,:,43);
    UTPelY_ArabR = masterData1.arrangedArabRData(:,:,44);
    UTPelZ_ArabR = masterData1.arrangedArabRData(:,:,45);
    UTULX_ArabR = masterData1.arrangedArabRData(:,:,46);
    UTULY_ArabR = masterData1.arrangedArabRData(:,:,47);
    UTULZ_ArabR = masterData1.arrangedArabRData(:,:,48);

    datasetLLLabX_ArabR = cell2struct(num2cell(LLLabX_ArabR, 1), compose('Subject%d', 1:size(LLLabX_ArabR, 2)), 2);
    datasetLLLabY_ArabR = cell2struct(num2cell(LLLabY_ArabR, 1), compose('Subject%d', 1:size(LLLabY_ArabR, 2)), 2);
    datasetLLLabZ_ArabR = cell2struct(num2cell(LLLabZ_ArabR, 1), compose('Subject%d', 1:size(LLLabZ_ArabR, 2)), 2);
    datasetLLPelX_ArabR = cell2struct(num2cell(LLPelX_ArabR, 1), compose('Subject%d', 1:size(LLPelX_ArabR, 2)), 2);
    datasetLLPelY_ArabR = cell2struct(num2cell(LLPelY_ArabR, 1), compose('Subject%d', 1:size(LLPelY_ArabR, 2)), 2);
    datasetLLPelZ_ArabR = cell2struct(num2cell(LLPelZ_ArabR, 1), compose('Subject%d', 1:size(LLPelZ_ArabR, 2)), 2);
    datasetLTLabX_ArabR = cell2struct(num2cell(LTLabX_ArabR, 1), compose('Subject%d', 1:size(LTLabX_ArabR, 2)), 2);
    datasetLTLabY_ArabR = cell2struct(num2cell(LTLabY_ArabR, 1), compose('Subject%d', 1:size(LTLabY_ArabR, 2)), 2);
    datasetLTLabZ_ArabR = cell2struct(num2cell(LTLabZ_ArabR, 1), compose('Subject%d', 1:size(LTLabZ_ArabR, 2)), 2);
    datasetLTLLX_ArabR = cell2struct(num2cell(LTLLX_ArabR, 1), compose('Subject%d', 1:size(LTLLX_ArabR, 2)), 2);
    datasetLTLLY_ArabR = cell2struct(num2cell(LTLLY_ArabR, 1), compose('Subject%d', 1:size(LTLLY_ArabR, 2)), 2);
    datasetLTLLZ_ArabR = cell2struct(num2cell(LTLLZ_ArabR, 1), compose('Subject%d', 1:size(LTLLZ_ArabR, 2)), 2);
    datasetLTPelX_ArabR = cell2struct(num2cell(LTPelX_ArabR, 1), compose('Subject%d', 1:size(LTPelX_ArabR, 2)), 2);
    datasetLTPelY_ArabR = cell2struct(num2cell(LTPelY_ArabR, 1), compose('Subject%d', 1:size(LTPelY_ArabR, 2)), 2);
    datasetLTPelZ_ArabR = cell2struct(num2cell(LTPelZ_ArabR, 1), compose('Subject%d', 1:size(LTPelZ_ArabR, 2)), 2);
    datasetLTULX_ArabR = cell2struct(num2cell(LTULX_ArabR, 1), compose('Subject%d', 1:size(LTULX_ArabR, 2)), 2);
    datasetLTULY_ArabR = cell2struct(num2cell(LTULY_ArabR, 1), compose('Subject%d', 1:size(LTULY_ArabR, 2)), 2);    
    datasetLTULZ_ArabR = cell2struct(num2cell(LTULZ_ArabR, 1), compose('Subject%d', 1:size(LTULZ_ArabR, 2)), 2);
    datasetPelLabX_ArabR = cell2struct(num2cell(PelLabX_ArabR, 1), compose('Subject%d', 1:size(PelLabX_ArabR, 2)), 2);
    datasetPelLabY_ArabR = cell2struct(num2cell(PelLabY_ArabR, 1), compose('Subject%d', 1:size(PelLabY_ArabR, 2)), 2);
    datasetPelLabZ_ArabR = cell2struct(num2cell(PelLabZ_ArabR, 1), compose('Subject%d', 1:size(PelLabZ_ArabR, 2)), 2);
    datasetTrunkLabX_ArabR = cell2struct(num2cell(TrunkLabX_ArabR, 1), compose('Subject%d', 1:size(TrunkLabX_ArabR, 2)), 2);    
    datasetTrunkLabY_ArabR = cell2struct(num2cell(TrunkLabY_ArabR, 1), compose('Subject%d', 1:size(TrunkLabY_ArabR, 2)), 2);
    datasetTrunkLabZ_ArabR = cell2struct(num2cell(TrunkLabZ_ArabR, 1), compose('Subject%d', 1:size(TrunkLabZ_ArabR, 2)), 2);
    datasetULLabX_ArabR = cell2struct(num2cell(ULLabX_ArabR, 1), compose('Subject%d', 1:size(ULLabX_ArabR, 2)), 2);
    datasetULLabY_ArabR = cell2struct(num2cell(ULLabY_ArabR, 1), compose('Subject%d', 1:size(ULLabY_ArabR, 2)), 2);
    datasetULLabZ_ArabR = cell2struct(num2cell(ULLabZ_ArabR, 1), compose('Subject%d', 1:size(ULLabZ_ArabR, 2)), 2);
    datasetULLLX_ArabR = cell2struct(num2cell(ULLLX_ArabR, 1), compose('Subject%d', 1:size(ULLLX_ArabR, 2)), 2);
    datasetULLLY_ArabR = cell2struct(num2cell(ULLLY_ArabR, 1), compose('Subject%d', 1:size(ULLLY_ArabR, 2)), 2);
    datasetULLLZ_ArabR = cell2struct(num2cell(ULLLZ_ArabR, 1), compose('Subject%d', 1:size(ULLLZ_ArabR, 2)), 2);
    datasetULPelX_ArabR = cell2struct(num2cell(ULPelX_ArabR, 1), compose('Subject%d', 1:size(ULPelX_ArabR, 2)), 2);
    datasetULPelY_ArabR = cell2struct(num2cell(ULPelY_ArabR, 1), compose('Subject%d', 1:size(ULPelY_ArabR, 2)), 2);
    datasetULPelZ_ArabR = cell2struct(num2cell(ULPelZ_ArabR, 1), compose('Subject%d', 1:size(ULPelZ_ArabR, 2)), 2);
    datasetUTLabX_ArabR = cell2struct(num2cell(UTLabX_ArabR, 1), compose('Subject%d', 1:size(UTLabX_ArabR, 2)), 2);
    datasetUTLabY_ArabR = cell2struct(num2cell(UTLabY_ArabR, 1), compose('Subject%d', 1:size(UTLabY_ArabR, 2)), 2);
    datasetUTLabZ_ArabR = cell2struct(num2cell(UTLabZ_ArabR, 1), compose('Subject%d', 1:size(UTLabZ_ArabR, 2)), 2);
    datasetUTLLX_ArabR = cell2struct(num2cell(UTLLX_ArabR, 1), compose('Subject%d', 1:size(UTLLX_ArabR, 2)), 2);
    datasetUTLLY_ArabR = cell2struct(num2cell(UTLLY_ArabR, 1), compose('Subject%d', 1:size(UTLLY_ArabR, 2)), 2);
    datasetUTLLZ_ArabR = cell2struct(num2cell(UTLLZ_ArabR, 1), compose('Subject%d', 1:size(UTLLZ_ArabR, 2)), 2);
    datasetUTLTX_ArabR = cell2struct(num2cell(UTLTX_ArabR, 1), compose('Subject%d', 1:size(UTLTX_ArabR, 2)), 2);
    datasetUTLTY_ArabR = cell2struct(num2cell(UTLTY_ArabR, 1), compose('Subject%d', 1:size(UTLTY_ArabR, 2)), 2);
    datasetUTLTZ_ArabR = cell2struct(num2cell(UTLTZ_ArabR, 1), compose('Subject%d', 1:size(UTLTZ_ArabR, 2)), 2);
    datasetUTPelX_ArabR = cell2struct(num2cell(UTPelX_ArabR, 1), compose('Subject%d', 1:size(UTPelX_ArabR, 2)), 2);
    datasetUTPelY_ArabR = cell2struct(num2cell(UTPelY_ArabR, 1), compose('Subject%d', 1:size(UTPelY_ArabR, 2)), 2);
    datasetUTPelZ_ArabR = cell2struct(num2cell(UTPelZ_ArabR, 1), compose('Subject%d', 1:size(UTPelZ_ArabR, 2)), 2);
    datasetUTULX_ArabR = cell2struct(num2cell(UTULX_ArabR, 1), compose('Subject%d', 1:size(UTULX_ArabR, 2)), 2);
    datasetUTULY_ArabR = cell2struct(num2cell(UTULY_ArabR, 1), compose('Subject%d', 1:size(UTULY_ArabR, 2)), 2);
    datasetUTULZ_ArabR = cell2struct(num2cell(UTULZ_ArabR, 1), compose('Subject%d', 1:size(UTULZ_ArabR, 2)), 2);
    
    masterData2 = load('arrangedFMSLData.mat','arrangedFMSLData');
    
    LLLabX_FMSL = masterData2.arrangedFMSLData(:,:,1);
    LLLabY_FMSL = masterData2.arrangedFMSLData(:,:,2);
    LLLabZ_FMSL = masterData2.arrangedFMSLData(:,:,3);
    LLPelX_FMSL = masterData2.arrangedFMSLData(:,:,4);
    LLPelY_FMSL = masterData2.arrangedFMSLData(:,:,5);
    LLPelZ_FMSL = masterData2.arrangedFMSLData(:,:,6);
    LTLabX_FMSL = masterData2.arrangedFMSLData(:,:,7);
    LTLabY_FMSL = masterData2.arrangedFMSLData(:,:,8);
    LTLabZ_FMSL = masterData2.arrangedFMSLData(:,:,9);
    LTLLX_FMSL = masterData2.arrangedFMSLData(:,:,10);
    LTLLY_FMSL = masterData2.arrangedFMSLData(:,:,11);
    LTLLZ_FMSL = masterData2.arrangedFMSLData(:,:,12);
    LTPelX_FMSL = masterData2.arrangedFMSLData(:,:,13);
    LTPelY_FMSL = masterData2.arrangedFMSLData(:,:,14);
    LTPelZ_FMSL = masterData2.arrangedFMSLData(:,:,15);
    LTULX_FMSL = masterData2.arrangedFMSLData(:,:,16);
    LTULY_FMSL = masterData2.arrangedFMSLData(:,:,17);
    LTULZ_FMSL = masterData2.arrangedFMSLData(:,:,18);
    PelLabX_FMSL = masterData2.arrangedFMSLData(:,:,19);
    PelLabY_FMSL = masterData2.arrangedFMSLData(:,:,20);
    PelLabZ_FMSL = masterData2.arrangedFMSLData(:,:,21);
    TrunkLabX_FMSL = masterData2.arrangedFMSLData(:,:,22);
    TrunkLabY_FMSL = masterData2.arrangedFMSLData(:,:,23);
    TrunkLabZ_FMSL = masterData2.arrangedFMSLData(:,:,24);
    ULLabX_FMSL = masterData2.arrangedFMSLData(:,:,25);
    ULLabY_FMSL = masterData2.arrangedFMSLData(:,:,26);
    ULLabZ_FMSL = masterData2.arrangedFMSLData(:,:,27);
    ULLLX_FMSL = masterData2.arrangedFMSLData(:,:,28);
    ULLLY_FMSL = masterData2.arrangedFMSLData(:,:,29);
    ULLLZ_FMSL = masterData2.arrangedFMSLData(:,:,30);
    ULPelX_FMSL = masterData2.arrangedFMSLData(:,:,31);
    ULPelY_FMSL = masterData2.arrangedFMSLData(:,:,32);
    ULPelZ_FMSL = masterData2.arrangedFMSLData(:,:,33);
    UTLabX_FMSL = masterData2.arrangedFMSLData(:,:,34);
    UTLabY_FMSL = masterData2.arrangedFMSLData(:,:,35);
    UTLabZ_FMSL = masterData2.arrangedFMSLData(:,:,36);
    UTLLX_FMSL = masterData2.arrangedFMSLData(:,:,37);
    UTLLY_FMSL = masterData2.arrangedFMSLData(:,:,38);
    UTLLZ_FMSL = masterData2.arrangedFMSLData(:,:,39);
    UTLTX_FMSL = masterData2.arrangedFMSLData(:,:,40);
    UTLTY_FMSL = masterData2.arrangedFMSLData(:,:,41);
    UTLTZ_FMSL = masterData2.arrangedFMSLData(:,:,42);
    UTPelX_FMSL = masterData2.arrangedFMSLData(:,:,43);
    UTPelY_FMSL = masterData2.arrangedFMSLData(:,:,44);
    UTPelZ_FMSL = masterData2.arrangedFMSLData(:,:,45);
    UTULX_FMSL = masterData2.arrangedFMSLData(:,:,46);
    UTULY_FMSL = masterData2.arrangedFMSLData(:,:,47);
    UTULZ_FMSL = masterData2.arrangedFMSLData(:,:,48);

    datasetLLLabX_FMSL = cell2struct(num2cell(LLLabX_FMSL, 1), compose('Subject%d', 1:size(LLLabX_FMSL, 2)), 2);
    datasetLLLabY_FMSL = cell2struct(num2cell(LLLabY_FMSL, 1), compose('Subject%d', 1:size(LLLabY_FMSL, 2)), 2);
    datasetLLLabZ_FMSL = cell2struct(num2cell(LLLabZ_FMSL, 1), compose('Subject%d', 1:size(LLLabZ_FMSL, 2)), 2);
    datasetLLPelX_FMSL = cell2struct(num2cell(LLPelX_FMSL, 1), compose('Subject%d', 1:size(LLPelX_FMSL, 2)), 2);
    datasetLLPelY_FMSL = cell2struct(num2cell(LLPelY_FMSL, 1), compose('Subject%d', 1:size(LLPelY_FMSL, 2)), 2);
    datasetLLPelZ_FMSL = cell2struct(num2cell(LLPelZ_FMSL, 1), compose('Subject%d', 1:size(LLPelZ_FMSL, 2)), 2);
    datasetLTLabX_FMSL = cell2struct(num2cell(LTLabX_FMSL, 1), compose('Subject%d', 1:size(LTLabX_FMSL, 2)), 2);
    datasetLTLabY_FMSL = cell2struct(num2cell(LTLabY_FMSL, 1), compose('Subject%d', 1:size(LTLabY_FMSL, 2)), 2);
    datasetLTLabZ_FMSL = cell2struct(num2cell(LTLabZ_FMSL, 1), compose('Subject%d', 1:size(LTLabZ_FMSL, 2)), 2);
    datasetLTLLX_FMSL = cell2struct(num2cell(LTLLX_FMSL, 1), compose('Subject%d', 1:size(LTLLX_FMSL, 2)), 2);
    datasetLTLLY_FMSL = cell2struct(num2cell(LTLLY_FMSL, 1), compose('Subject%d', 1:size(LTLLY_FMSL, 2)), 2);
    datasetLTLLZ_FMSL = cell2struct(num2cell(LTLLZ_FMSL, 1), compose('Subject%d', 1:size(LTLLZ_FMSL, 2)), 2);
    datasetLTPelX_FMSL = cell2struct(num2cell(LTPelX_FMSL, 1), compose('Subject%d', 1:size(LTPelX_FMSL, 2)), 2);
    datasetLTPelY_FMSL = cell2struct(num2cell(LTPelY_FMSL, 1), compose('Subject%d', 1:size(LTPelY_FMSL, 2)), 2);
    datasetLTPelZ_FMSL = cell2struct(num2cell(LTPelZ_FMSL, 1), compose('Subject%d', 1:size(LTPelZ_FMSL, 2)), 2);
    datasetLTULX_FMSL = cell2struct(num2cell(LTULX_FMSL, 1), compose('Subject%d', 1:size(LTULX_FMSL, 2)), 2);
    datasetLTULY_FMSL = cell2struct(num2cell(LTULY_FMSL, 1), compose('Subject%d', 1:size(LTULY_FMSL, 2)), 2);    
    datasetLTULZ_FMSL = cell2struct(num2cell(LTULZ_FMSL, 1), compose('Subject%d', 1:size(LTULZ_FMSL, 2)), 2);
    datasetPelLabX_FMSL = cell2struct(num2cell(PelLabX_FMSL, 1), compose('Subject%d', 1:size(PelLabX_FMSL, 2)), 2);
    datasetPelLabY_FMSL = cell2struct(num2cell(PelLabY_FMSL, 1), compose('Subject%d', 1:size(PelLabY_FMSL, 2)), 2);
    datasetPelLabZ_FMSL = cell2struct(num2cell(PelLabZ_FMSL, 1), compose('Subject%d', 1:size(PelLabZ_FMSL, 2)), 2);
    datasetTrunkLabX_FMSL = cell2struct(num2cell(TrunkLabX_FMSL, 1), compose('Subject%d', 1:size(TrunkLabX_FMSL, 2)), 2);    
    datasetTrunkLabY_FMSL = cell2struct(num2cell(TrunkLabY_FMSL, 1), compose('Subject%d', 1:size(TrunkLabY_FMSL, 2)), 2);
    datasetTrunkLabZ_FMSL = cell2struct(num2cell(TrunkLabZ_FMSL, 1), compose('Subject%d', 1:size(TrunkLabZ_FMSL, 2)), 2);
    datasetULLabX_FMSL = cell2struct(num2cell(ULLabX_FMSL, 1), compose('Subject%d', 1:size(ULLabX_FMSL, 2)), 2);
    datasetULLabY_FMSL = cell2struct(num2cell(ULLabY_FMSL, 1), compose('Subject%d', 1:size(ULLabY_FMSL, 2)), 2);
    datasetULLabZ_FMSL = cell2struct(num2cell(ULLabZ_FMSL, 1), compose('Subject%d', 1:size(ULLabZ_FMSL, 2)), 2);
    datasetULLLX_FMSL = cell2struct(num2cell(ULLLX_FMSL, 1), compose('Subject%d', 1:size(ULLLX_FMSL, 2)), 2);
    datasetULLLY_FMSL = cell2struct(num2cell(ULLLY_FMSL, 1), compose('Subject%d', 1:size(ULLLY_FMSL, 2)), 2);
    datasetULLLZ_FMSL = cell2struct(num2cell(ULLLZ_FMSL, 1), compose('Subject%d', 1:size(ULLLZ_FMSL, 2)), 2);
    datasetULPelX_FMSL = cell2struct(num2cell(ULPelX_FMSL, 1), compose('Subject%d', 1:size(ULPelX_FMSL, 2)), 2);
    datasetULPelY_FMSL = cell2struct(num2cell(ULPelY_FMSL, 1), compose('Subject%d', 1:size(ULPelY_FMSL, 2)), 2);
    datasetULPelZ_FMSL = cell2struct(num2cell(ULPelZ_FMSL, 1), compose('Subject%d', 1:size(ULPelZ_FMSL, 2)), 2);
    datasetUTLabX_FMSL = cell2struct(num2cell(UTLabX_FMSL, 1), compose('Subject%d', 1:size(UTLabX_FMSL, 2)), 2);
    datasetUTLabY_FMSL = cell2struct(num2cell(UTLabY_FMSL, 1), compose('Subject%d', 1:size(UTLabY_FMSL, 2)), 2);
    datasetUTLabZ_FMSL = cell2struct(num2cell(UTLabZ_FMSL, 1), compose('Subject%d', 1:size(UTLabZ_FMSL, 2)), 2);
    datasetUTLLX_FMSL = cell2struct(num2cell(UTLLX_FMSL, 1), compose('Subject%d', 1:size(UTLLX_FMSL, 2)), 2);
    datasetUTLLY_FMSL = cell2struct(num2cell(UTLLY_FMSL, 1), compose('Subject%d', 1:size(UTLLY_FMSL, 2)), 2);
    datasetUTLLZ_FMSL = cell2struct(num2cell(UTLLZ_FMSL, 1), compose('Subject%d', 1:size(UTLLZ_FMSL, 2)), 2);
    datasetUTLTX_FMSL = cell2struct(num2cell(UTLTX_FMSL, 1), compose('Subject%d', 1:size(UTLTX_FMSL, 2)), 2);
    datasetUTLTY_FMSL = cell2struct(num2cell(UTLTY_FMSL, 1), compose('Subject%d', 1:size(UTLTY_FMSL, 2)), 2);
    datasetUTLTZ_FMSL = cell2struct(num2cell(UTLTZ_FMSL, 1), compose('Subject%d', 1:size(UTLTZ_FMSL, 2)), 2);
    datasetUTPelX_FMSL = cell2struct(num2cell(UTPelX_FMSL, 1), compose('Subject%d', 1:size(UTPelX_FMSL, 2)), 2);
    datasetUTPelY_FMSL = cell2struct(num2cell(UTPelY_FMSL, 1), compose('Subject%d', 1:size(UTPelY_FMSL, 2)), 2);
    datasetUTPelZ_FMSL = cell2struct(num2cell(UTPelZ_FMSL, 1), compose('Subject%d', 1:size(UTPelZ_FMSL, 2)), 2);
    datasetUTULX_FMSL = cell2struct(num2cell(UTULX_FMSL, 1), compose('Subject%d', 1:size(UTULX_FMSL, 2)), 2);
    datasetUTULY_FMSL = cell2struct(num2cell(UTULY_FMSL, 1), compose('Subject%d', 1:size(UTULY_FMSL, 2)), 2);
    datasetUTULZ_FMSL = cell2struct(num2cell(UTULZ_FMSL, 1), compose('Subject%d', 1:size(UTULZ_FMSL, 2)), 2);
    
    masterData3 = load('arrangedFMSRData.mat','arrangedFMSRData');
    
    LLLabX_FMSR = masterData3.arrangedFMSRData(:,:,1);
    LLLabY_FMSR = masterData3.arrangedFMSRData(:,:,2);
    LLLabZ_FMSR = masterData3.arrangedFMSRData(:,:,3);
    LLPelX_FMSR = masterData3.arrangedFMSRData(:,:,4);
    LLPelY_FMSR = masterData3.arrangedFMSRData(:,:,5);
    LLPelZ_FMSR = masterData3.arrangedFMSRData(:,:,6);
    LTLabX_FMSR = masterData3.arrangedFMSRData(:,:,7);
    LTLabY_FMSR = masterData3.arrangedFMSRData(:,:,8);
    LTLabZ_FMSR = masterData3.arrangedFMSRData(:,:,9);
    LTLLX_FMSR = masterData3.arrangedFMSRData(:,:,10);
    LTLLY_FMSR = masterData3.arrangedFMSRData(:,:,11);
    LTLLZ_FMSR = masterData3.arrangedFMSRData(:,:,12);
    LTPelX_FMSR = masterData3.arrangedFMSRData(:,:,13);
    LTPelY_FMSR = masterData3.arrangedFMSRData(:,:,14);
    LTPelZ_FMSR = masterData3.arrangedFMSRData(:,:,15);
    LTULX_FMSR = masterData3.arrangedFMSRData(:,:,16);
    LTULY_FMSR = masterData3.arrangedFMSRData(:,:,17);
    LTULZ_FMSR = masterData3.arrangedFMSRData(:,:,18);
    PelLabX_FMSR = masterData3.arrangedFMSRData(:,:,19);
    PelLabY_FMSR = masterData3.arrangedFMSRData(:,:,20);
    PelLabZ_FMSR = masterData3.arrangedFMSRData(:,:,21);
    TrunkLabX_FMSR = masterData3.arrangedFMSRData(:,:,22);
    TrunkLabY_FMSR = masterData3.arrangedFMSRData(:,:,23);
    TrunkLabZ_FMSR = masterData3.arrangedFMSRData(:,:,24);
    ULLabX_FMSR = masterData3.arrangedFMSRData(:,:,25);
    ULLabY_FMSR = masterData3.arrangedFMSRData(:,:,26);
    ULLabZ_FMSR = masterData3.arrangedFMSRData(:,:,27);
    ULLLX_FMSR = masterData3.arrangedFMSRData(:,:,28);
    ULLLY_FMSR = masterData3.arrangedFMSRData(:,:,29);
    ULLLZ_FMSR = masterData3.arrangedFMSRData(:,:,30);
    ULPelX_FMSR = masterData3.arrangedFMSRData(:,:,31);
    ULPelY_FMSR = masterData3.arrangedFMSRData(:,:,32);
    ULPelZ_FMSR = masterData3.arrangedFMSRData(:,:,33);
    UTLabX_FMSR = masterData3.arrangedFMSRData(:,:,34);
    UTLabY_FMSR = masterData3.arrangedFMSRData(:,:,35);
    UTLabZ_FMSR = masterData3.arrangedFMSRData(:,:,36);
    UTLLX_FMSR = masterData3.arrangedFMSRData(:,:,37);
    UTLLY_FMSR = masterData3.arrangedFMSRData(:,:,38);
    UTLLZ_FMSR = masterData3.arrangedFMSRData(:,:,39);
    UTLTX_FMSR = masterData3.arrangedFMSRData(:,:,40);
    UTLTY_FMSR = masterData3.arrangedFMSRData(:,:,41);
    UTLTZ_FMSR = masterData3.arrangedFMSRData(:,:,42);
    UTPelX_FMSR = masterData3.arrangedFMSRData(:,:,43);
    UTPelY_FMSR = masterData3.arrangedFMSRData(:,:,44);
    UTPelZ_FMSR = masterData3.arrangedFMSRData(:,:,45);
    UTULX_FMSR = masterData3.arrangedFMSRData(:,:,46);
    UTULY_FMSR = masterData3.arrangedFMSRData(:,:,47);
    UTULZ_FMSR = masterData3.arrangedFMSRData(:,:,48);

    datasetLLLabX_FMSR = cell2struct(num2cell(LLLabX_FMSR, 1), compose('Subject%d', 1:size(LLLabX_FMSR, 2)), 2);
    datasetLLLabY_FMSR = cell2struct(num2cell(LLLabY_FMSR, 1), compose('Subject%d', 1:size(LLLabY_FMSR, 2)), 2);
    datasetLLLabZ_FMSR = cell2struct(num2cell(LLLabZ_FMSR, 1), compose('Subject%d', 1:size(LLLabZ_FMSR, 2)), 2);
    datasetLLPelX_FMSR = cell2struct(num2cell(LLPelX_FMSR, 1), compose('Subject%d', 1:size(LLPelX_FMSR, 2)), 2);
    datasetLLPelY_FMSR = cell2struct(num2cell(LLPelY_FMSR, 1), compose('Subject%d', 1:size(LLPelY_FMSR, 2)), 2);
    datasetLLPelZ_FMSR = cell2struct(num2cell(LLPelZ_FMSR, 1), compose('Subject%d', 1:size(LLPelZ_FMSR, 2)), 2);
    datasetLTLabX_FMSR = cell2struct(num2cell(LTLabX_FMSR, 1), compose('Subject%d', 1:size(LTLabX_FMSR, 2)), 2);
    datasetLTLabY_FMSR = cell2struct(num2cell(LTLabY_FMSR, 1), compose('Subject%d', 1:size(LTLabY_FMSR, 2)), 2);
    datasetLTLabZ_FMSR = cell2struct(num2cell(LTLabZ_FMSR, 1), compose('Subject%d', 1:size(LTLabZ_FMSR, 2)), 2);
    datasetLTLLX_FMSR = cell2struct(num2cell(LTLLX_FMSR, 1), compose('Subject%d', 1:size(LTLLX_FMSR, 2)), 2);
    datasetLTLLY_FMSR = cell2struct(num2cell(LTLLY_FMSR, 1), compose('Subject%d', 1:size(LTLLY_FMSR, 2)), 2);
    datasetLTLLZ_FMSR = cell2struct(num2cell(LTLLZ_FMSR, 1), compose('Subject%d', 1:size(LTLLZ_FMSR, 2)), 2);
    datasetLTPelX_FMSR = cell2struct(num2cell(LTPelX_FMSR, 1), compose('Subject%d', 1:size(LTPelX_FMSR, 2)), 2);
    datasetLTPelY_FMSR = cell2struct(num2cell(LTPelY_FMSR, 1), compose('Subject%d', 1:size(LTPelY_FMSR, 2)), 2);
    datasetLTPelZ_FMSR = cell2struct(num2cell(LTPelZ_FMSR, 1), compose('Subject%d', 1:size(LTPelZ_FMSR, 2)), 2);
    datasetLTULX_FMSR = cell2struct(num2cell(LTULX_FMSR, 1), compose('Subject%d', 1:size(LTULX_FMSR, 2)), 2);
    datasetLTULY_FMSR = cell2struct(num2cell(LTULY_FMSR, 1), compose('Subject%d', 1:size(LTULY_FMSR, 2)), 2);    
    datasetLTULZ_FMSR = cell2struct(num2cell(LTULZ_FMSR, 1), compose('Subject%d', 1:size(LTULZ_FMSR, 2)), 2);
    datasetPelLabX_FMSR = cell2struct(num2cell(PelLabX_FMSR, 1), compose('Subject%d', 1:size(PelLabX_FMSR, 2)), 2);
    datasetPelLabY_FMSR = cell2struct(num2cell(PelLabY_FMSR, 1), compose('Subject%d', 1:size(PelLabY_FMSR, 2)), 2);
    datasetPelLabZ_FMSR = cell2struct(num2cell(PelLabZ_FMSR, 1), compose('Subject%d', 1:size(PelLabZ_FMSR, 2)), 2);
    datasetTrunkLabX_FMSR = cell2struct(num2cell(TrunkLabX_FMSR, 1), compose('Subject%d', 1:size(TrunkLabX_FMSR, 2)), 2);    
    datasetTrunkLabY_FMSR = cell2struct(num2cell(TrunkLabY_FMSR, 1), compose('Subject%d', 1:size(TrunkLabY_FMSR, 2)), 2);
    datasetTrunkLabZ_FMSR = cell2struct(num2cell(TrunkLabZ_FMSR, 1), compose('Subject%d', 1:size(TrunkLabZ_FMSR, 2)), 2);
    datasetULLabX_FMSR = cell2struct(num2cell(ULLabX_FMSR, 1), compose('Subject%d', 1:size(ULLabX_FMSR, 2)), 2);
    datasetULLabY_FMSR = cell2struct(num2cell(ULLabY_FMSR, 1), compose('Subject%d', 1:size(ULLabY_FMSR, 2)), 2);
    datasetULLabZ_FMSR = cell2struct(num2cell(ULLabZ_FMSR, 1), compose('Subject%d', 1:size(ULLabZ_FMSR, 2)), 2);
    datasetULLLX_FMSR = cell2struct(num2cell(ULLLX_FMSR, 1), compose('Subject%d', 1:size(ULLLX_FMSR, 2)), 2);
    datasetULLLY_FMSR = cell2struct(num2cell(ULLLY_FMSR, 1), compose('Subject%d', 1:size(ULLLY_FMSR, 2)), 2);
    datasetULLLZ_FMSR = cell2struct(num2cell(ULLLZ_FMSR, 1), compose('Subject%d', 1:size(ULLLZ_FMSR, 2)), 2);
    datasetULPelX_FMSR = cell2struct(num2cell(ULPelX_FMSR, 1), compose('Subject%d', 1:size(ULPelX_FMSR, 2)), 2);
    datasetULPelY_FMSR = cell2struct(num2cell(ULPelY_FMSR, 1), compose('Subject%d', 1:size(ULPelY_FMSR, 2)), 2);
    datasetULPelZ_FMSR = cell2struct(num2cell(ULPelZ_FMSR, 1), compose('Subject%d', 1:size(ULPelZ_FMSR, 2)), 2);
    datasetUTLabX_FMSR = cell2struct(num2cell(UTLabX_FMSR, 1), compose('Subject%d', 1:size(UTLabX_FMSR, 2)), 2);
    datasetUTLabY_FMSR = cell2struct(num2cell(UTLabY_FMSR, 1), compose('Subject%d', 1:size(UTLabY_FMSR, 2)), 2);
    datasetUTLabZ_FMSR = cell2struct(num2cell(UTLabZ_FMSR, 1), compose('Subject%d', 1:size(UTLabZ_FMSR, 2)), 2);
    datasetUTLLX_FMSR = cell2struct(num2cell(UTLLX_FMSR, 1), compose('Subject%d', 1:size(UTLLX_FMSR, 2)), 2);
    datasetUTLLY_FMSR = cell2struct(num2cell(UTLLY_FMSR, 1), compose('Subject%d', 1:size(UTLLY_FMSR, 2)), 2);
    datasetUTLLZ_FMSR = cell2struct(num2cell(UTLLZ_FMSR, 1), compose('Subject%d', 1:size(UTLLZ_FMSR, 2)), 2);
    datasetUTLTX_FMSR = cell2struct(num2cell(UTLTX_FMSR, 1), compose('Subject%d', 1:size(UTLTX_FMSR, 2)), 2);
    datasetUTLTY_FMSR = cell2struct(num2cell(UTLTY_FMSR, 1), compose('Subject%d', 1:size(UTLTY_FMSR, 2)), 2);
    datasetUTLTZ_FMSR = cell2struct(num2cell(UTLTZ_FMSR, 1), compose('Subject%d', 1:size(UTLTZ_FMSR, 2)), 2);
    datasetUTPelX_FMSR = cell2struct(num2cell(UTPelX_FMSR, 1), compose('Subject%d', 1:size(UTPelX_FMSR, 2)), 2);
    datasetUTPelY_FMSR = cell2struct(num2cell(UTPelY_FMSR, 1), compose('Subject%d', 1:size(UTPelY_FMSR, 2)), 2);
    datasetUTPelZ_FMSR = cell2struct(num2cell(UTPelZ_FMSR, 1), compose('Subject%d', 1:size(UTPelZ_FMSR, 2)), 2);
    datasetUTULX_FMSR = cell2struct(num2cell(UTULX_FMSR, 1), compose('Subject%d', 1:size(UTULX_FMSR, 2)), 2);
    datasetUTULY_FMSR = cell2struct(num2cell(UTULY_FMSR, 1), compose('Subject%d', 1:size(UTULY_FMSR, 2)), 2);
    datasetUTULZ_FMSR = cell2struct(num2cell(UTULZ_FMSR, 1), compose('Subject%d', 1:size(UTULZ_FMSR, 2)), 2);    
    
    masterData4 = load('arrangedPasseLData.mat','arrangedPasseLData');
    
    LLLabX_PasseL = masterData4.arrangedPasseLData(:,:,1);
    LLLabY_PasseL = masterData4.arrangedPasseLData(:,:,2);
    LLLabZ_PasseL = masterData4.arrangedPasseLData(:,:,3);
    LLPelX_PasseL = masterData4.arrangedPasseLData(:,:,4);
    LLPelY_PasseL = masterData4.arrangedPasseLData(:,:,5);
    LLPelZ_PasseL = masterData4.arrangedPasseLData(:,:,6);
    LTLabX_PasseL = masterData4.arrangedPasseLData(:,:,7);
    LTLabY_PasseL = masterData4.arrangedPasseLData(:,:,8);
    LTLabZ_PasseL = masterData4.arrangedPasseLData(:,:,9);
    LTLLX_PasseL = masterData4.arrangedPasseLData(:,:,10);
    LTLLY_PasseL = masterData4.arrangedPasseLData(:,:,11);
    LTLLZ_PasseL = masterData4.arrangedPasseLData(:,:,12);
    LTPelX_PasseL = masterData4.arrangedPasseLData(:,:,13);
    LTPelY_PasseL = masterData4.arrangedPasseLData(:,:,14);
    LTPelZ_PasseL = masterData4.arrangedPasseLData(:,:,15);
    LTULX_PasseL = masterData4.arrangedPasseLData(:,:,16);
    LTULY_PasseL = masterData4.arrangedPasseLData(:,:,17);
    LTULZ_PasseL = masterData4.arrangedPasseLData(:,:,18);
    PelLabX_PasseL = masterData4.arrangedPasseLData(:,:,19);
    PelLabY_PasseL = masterData4.arrangedPasseLData(:,:,20);
    PelLabZ_PasseL = masterData4.arrangedPasseLData(:,:,21);
    TrunkLabX_PasseL = masterData4.arrangedPasseLData(:,:,22);
    TrunkLabY_PasseL = masterData4.arrangedPasseLData(:,:,23);
    TrunkLabZ_PasseL = masterData4.arrangedPasseLData(:,:,24);
    ULLabX_PasseL = masterData4.arrangedPasseLData(:,:,25);
    ULLabY_PasseL = masterData4.arrangedPasseLData(:,:,26);
    ULLabZ_PasseL = masterData4.arrangedPasseLData(:,:,27);
    ULLLX_PasseL = masterData4.arrangedPasseLData(:,:,28);
    ULLLY_PasseL = masterData4.arrangedPasseLData(:,:,29);
    ULLLZ_PasseL = masterData4.arrangedPasseLData(:,:,30);
    ULPelX_PasseL = masterData4.arrangedPasseLData(:,:,31);
    ULPelY_PasseL = masterData4.arrangedPasseLData(:,:,32);
    ULPelZ_PasseL = masterData4.arrangedPasseLData(:,:,33);
    UTLabX_PasseL = masterData4.arrangedPasseLData(:,:,34);
    UTLabY_PasseL = masterData4.arrangedPasseLData(:,:,35);
    UTLabZ_PasseL = masterData4.arrangedPasseLData(:,:,36);
    UTLLX_PasseL = masterData4.arrangedPasseLData(:,:,37);
    UTLLY_PasseL = masterData4.arrangedPasseLData(:,:,38);
    UTLLZ_PasseL = masterData4.arrangedPasseLData(:,:,39);
    UTLTX_PasseL = masterData4.arrangedPasseLData(:,:,40);
    UTLTY_PasseL = masterData4.arrangedPasseLData(:,:,41);
    UTLTZ_PasseL = masterData4.arrangedPasseLData(:,:,42);
    UTPelX_PasseL = masterData4.arrangedPasseLData(:,:,43);
    UTPelY_PasseL = masterData4.arrangedPasseLData(:,:,44);
    UTPelZ_PasseL = masterData4.arrangedPasseLData(:,:,45);
    UTULX_PasseL = masterData4.arrangedPasseLData(:,:,46);
    UTULY_PasseL = masterData4.arrangedPasseLData(:,:,47);
    UTULZ_PasseL = masterData4.arrangedPasseLData(:,:,48);

    datasetLLLabX_PasseL = cell2struct(num2cell(LLLabX_PasseL, 1), compose('Subject%d', 1:size(LLLabX_PasseL, 2)), 2);
    datasetLLLabY_PasseL = cell2struct(num2cell(LLLabY_PasseL, 1), compose('Subject%d', 1:size(LLLabY_PasseL, 2)), 2);
    datasetLLLabZ_PasseL = cell2struct(num2cell(LLLabZ_PasseL, 1), compose('Subject%d', 1:size(LLLabZ_PasseL, 2)), 2);
    datasetLLPelX_PasseL = cell2struct(num2cell(LLPelX_PasseL, 1), compose('Subject%d', 1:size(LLPelX_PasseL, 2)), 2);
    datasetLLPelY_PasseL = cell2struct(num2cell(LLPelY_PasseL, 1), compose('Subject%d', 1:size(LLPelY_PasseL, 2)), 2);
    datasetLLPelZ_PasseL = cell2struct(num2cell(LLPelZ_PasseL, 1), compose('Subject%d', 1:size(LLPelZ_PasseL, 2)), 2);
    datasetLTLabX_PasseL = cell2struct(num2cell(LTLabX_PasseL, 1), compose('Subject%d', 1:size(LTLabX_PasseL, 2)), 2);
    datasetLTLabY_PasseL = cell2struct(num2cell(LTLabY_PasseL, 1), compose('Subject%d', 1:size(LTLabY_PasseL, 2)), 2);
    datasetLTLabZ_PasseL = cell2struct(num2cell(LTLabZ_PasseL, 1), compose('Subject%d', 1:size(LTLabZ_PasseL, 2)), 2);
    datasetLTLLX_PasseL = cell2struct(num2cell(LTLLX_PasseL, 1), compose('Subject%d', 1:size(LTLLX_PasseL, 2)), 2);
    datasetLTLLY_PasseL = cell2struct(num2cell(LTLLY_PasseL, 1), compose('Subject%d', 1:size(LTLLY_PasseL, 2)), 2);
    datasetLTLLZ_PasseL = cell2struct(num2cell(LTLLZ_PasseL, 1), compose('Subject%d', 1:size(LTLLZ_PasseL, 2)), 2);
    datasetLTPelX_PasseL = cell2struct(num2cell(LTPelX_PasseL, 1), compose('Subject%d', 1:size(LTPelX_PasseL, 2)), 2);
    datasetLTPelY_PasseL = cell2struct(num2cell(LTPelY_PasseL, 1), compose('Subject%d', 1:size(LTPelY_PasseL, 2)), 2);
    datasetLTPelZ_PasseL = cell2struct(num2cell(LTPelZ_PasseL, 1), compose('Subject%d', 1:size(LTPelZ_PasseL, 2)), 2);
    datasetLTULX_PasseL = cell2struct(num2cell(LTULX_PasseL, 1), compose('Subject%d', 1:size(LTULX_PasseL, 2)), 2);
    datasetLTULY_PasseL = cell2struct(num2cell(LTULY_PasseL, 1), compose('Subject%d', 1:size(LTULY_PasseL, 2)), 2);    
    datasetLTULZ_PasseL = cell2struct(num2cell(LTULZ_PasseL, 1), compose('Subject%d', 1:size(LTULZ_PasseL, 2)), 2);
    datasetPelLabX_PasseL = cell2struct(num2cell(PelLabX_PasseL, 1), compose('Subject%d', 1:size(PelLabX_PasseL, 2)), 2);
    datasetPelLabY_PasseL = cell2struct(num2cell(PelLabY_PasseL, 1), compose('Subject%d', 1:size(PelLabY_PasseL, 2)), 2);
    datasetPelLabZ_PasseL = cell2struct(num2cell(PelLabZ_PasseL, 1), compose('Subject%d', 1:size(PelLabZ_PasseL, 2)), 2);
    datasetTrunkLabX_PasseL = cell2struct(num2cell(TrunkLabX_PasseL, 1), compose('Subject%d', 1:size(TrunkLabX_PasseL, 2)), 2);    
    datasetTrunkLabY_PasseL = cell2struct(num2cell(TrunkLabY_PasseL, 1), compose('Subject%d', 1:size(TrunkLabY_PasseL, 2)), 2);
    datasetTrunkLabZ_PasseL = cell2struct(num2cell(TrunkLabZ_PasseL, 1), compose('Subject%d', 1:size(TrunkLabZ_PasseL, 2)), 2);
    datasetULLabX_PasseL = cell2struct(num2cell(ULLabX_PasseL, 1), compose('Subject%d', 1:size(ULLabX_PasseL, 2)), 2);
    datasetULLabY_PasseL = cell2struct(num2cell(ULLabY_PasseL, 1), compose('Subject%d', 1:size(ULLabY_PasseL, 2)), 2);
    datasetULLabZ_PasseL = cell2struct(num2cell(ULLabZ_PasseL, 1), compose('Subject%d', 1:size(ULLabZ_PasseL, 2)), 2);
    datasetULLLX_PasseL = cell2struct(num2cell(ULLLX_PasseL, 1), compose('Subject%d', 1:size(ULLLX_PasseL, 2)), 2);
    datasetULLLY_PasseL = cell2struct(num2cell(ULLLY_PasseL, 1), compose('Subject%d', 1:size(ULLLY_PasseL, 2)), 2);
    datasetULLLZ_PasseL = cell2struct(num2cell(ULLLZ_PasseL, 1), compose('Subject%d', 1:size(ULLLZ_PasseL, 2)), 2);
    datasetULPelX_PasseL = cell2struct(num2cell(ULPelX_PasseL, 1), compose('Subject%d', 1:size(ULPelX_PasseL, 2)), 2);
    datasetULPelY_PasseL = cell2struct(num2cell(ULPelY_PasseL, 1), compose('Subject%d', 1:size(ULPelY_PasseL, 2)), 2);
    datasetULPelZ_PasseL = cell2struct(num2cell(ULPelZ_PasseL, 1), compose('Subject%d', 1:size(ULPelZ_PasseL, 2)), 2);
    datasetUTLabX_PasseL = cell2struct(num2cell(UTLabX_PasseL, 1), compose('Subject%d', 1:size(UTLabX_PasseL, 2)), 2);
    datasetUTLabY_PasseL = cell2struct(num2cell(UTLabY_PasseL, 1), compose('Subject%d', 1:size(UTLabY_PasseL, 2)), 2);
    datasetUTLabZ_PasseL = cell2struct(num2cell(UTLabZ_PasseL, 1), compose('Subject%d', 1:size(UTLabZ_PasseL, 2)), 2);
    datasetUTLLX_PasseL = cell2struct(num2cell(UTLLX_PasseL, 1), compose('Subject%d', 1:size(UTLLX_PasseL, 2)), 2);
    datasetUTLLY_PasseL = cell2struct(num2cell(UTLLY_PasseL, 1), compose('Subject%d', 1:size(UTLLY_PasseL, 2)), 2);
    datasetUTLLZ_PasseL = cell2struct(num2cell(UTLLZ_PasseL, 1), compose('Subject%d', 1:size(UTLLZ_PasseL, 2)), 2);
    datasetUTLTX_PasseL = cell2struct(num2cell(UTLTX_PasseL, 1), compose('Subject%d', 1:size(UTLTX_PasseL, 2)), 2);
    datasetUTLTY_PasseL = cell2struct(num2cell(UTLTY_PasseL, 1), compose('Subject%d', 1:size(UTLTY_PasseL, 2)), 2);
    datasetUTLTZ_PasseL = cell2struct(num2cell(UTLTZ_PasseL, 1), compose('Subject%d', 1:size(UTLTZ_PasseL, 2)), 2);
    datasetUTPelX_PasseL = cell2struct(num2cell(UTPelX_PasseL, 1), compose('Subject%d', 1:size(UTPelX_PasseL, 2)), 2);
    datasetUTPelY_PasseL = cell2struct(num2cell(UTPelY_PasseL, 1), compose('Subject%d', 1:size(UTPelY_PasseL, 2)), 2);
    datasetUTPelZ_PasseL = cell2struct(num2cell(UTPelZ_PasseL, 1), compose('Subject%d', 1:size(UTPelZ_PasseL, 2)), 2);
    datasetUTULX_PasseL = cell2struct(num2cell(UTULX_PasseL, 1), compose('Subject%d', 1:size(UTULX_PasseL, 2)), 2);
    datasetUTULY_PasseL = cell2struct(num2cell(UTULY_PasseL, 1), compose('Subject%d', 1:size(UTULY_PasseL, 2)), 2);
    datasetUTULZ_PasseL = cell2struct(num2cell(UTULZ_PasseL, 1), compose('Subject%d', 1:size(UTULZ_PasseL, 2)), 2);    
    
    masterData5 = load('arrangedPasseRData.mat','arrangedPasseRData');
    
    LLLabX_PasseR = masterData5.arrangedPasseRData(:,:,1);
    LLLabY_PasseR = masterData5.arrangedPasseRData(:,:,2);
    LLLabZ_PasseR = masterData5.arrangedPasseRData(:,:,3);
    LLPelX_PasseR = masterData5.arrangedPasseRData(:,:,4);
    LLPelY_PasseR = masterData5.arrangedPasseRData(:,:,5);
    LLPelZ_PasseR = masterData5.arrangedPasseRData(:,:,6);
    LTLabX_PasseR = masterData5.arrangedPasseRData(:,:,7);
    LTLabY_PasseR = masterData5.arrangedPasseRData(:,:,8);
    LTLabZ_PasseR = masterData5.arrangedPasseRData(:,:,9);
    LTLLX_PasseR = masterData5.arrangedPasseRData(:,:,10);
    LTLLY_PasseR = masterData5.arrangedPasseRData(:,:,11);
    LTLLZ_PasseR = masterData5.arrangedPasseRData(:,:,12);
    LTPelX_PasseR = masterData5.arrangedPasseRData(:,:,13);
    LTPelY_PasseR = masterData5.arrangedPasseRData(:,:,14);
    LTPelZ_PasseR = masterData5.arrangedPasseRData(:,:,15);
    LTULX_PasseR = masterData5.arrangedPasseRData(:,:,16);
    LTULY_PasseR = masterData5.arrangedPasseRData(:,:,17);
    LTULZ_PasseR = masterData5.arrangedPasseRData(:,:,18);
    PelLabX_PasseR = masterData5.arrangedPasseRData(:,:,19);
    PelLabY_PasseR = masterData5.arrangedPasseRData(:,:,20);
    PelLabZ_PasseR = masterData5.arrangedPasseRData(:,:,21);
    TrunkLabX_PasseR = masterData5.arrangedPasseRData(:,:,22);
    TrunkLabY_PasseR = masterData5.arrangedPasseRData(:,:,23);
    TrunkLabZ_PasseR = masterData5.arrangedPasseRData(:,:,24);
    ULLabX_PasseR = masterData5.arrangedPasseRData(:,:,25);
    ULLabY_PasseR = masterData5.arrangedPasseRData(:,:,26);
    ULLabZ_PasseR = masterData5.arrangedPasseRData(:,:,27);
    ULLLX_PasseR = masterData5.arrangedPasseRData(:,:,28);
    ULLLY_PasseR = masterData5.arrangedPasseRData(:,:,29);
    ULLLZ_PasseR = masterData5.arrangedPasseRData(:,:,30);
    ULPelX_PasseR = masterData5.arrangedPasseRData(:,:,31);
    ULPelY_PasseR = masterData5.arrangedPasseRData(:,:,32);
    ULPelZ_PasseR = masterData5.arrangedPasseRData(:,:,33);
    UTLabX_PasseR = masterData5.arrangedPasseRData(:,:,34);
    UTLabY_PasseR = masterData5.arrangedPasseRData(:,:,35);
    UTLabZ_PasseR = masterData5.arrangedPasseRData(:,:,36);
    UTLLX_PasseR = masterData5.arrangedPasseRData(:,:,37);
    UTLLY_PasseR = masterData5.arrangedPasseRData(:,:,38);
    UTLLZ_PasseR = masterData5.arrangedPasseRData(:,:,39);
    UTLTX_PasseR = masterData5.arrangedPasseRData(:,:,40);
    UTLTY_PasseR = masterData5.arrangedPasseRData(:,:,41);
    UTLTZ_PasseR = masterData5.arrangedPasseRData(:,:,42);
    UTPelX_PasseR = masterData5.arrangedPasseRData(:,:,43);
    UTPelY_PasseR = masterData5.arrangedPasseRData(:,:,44);
    UTPelZ_PasseR = masterData5.arrangedPasseRData(:,:,45);
    UTULX_PasseR = masterData5.arrangedPasseRData(:,:,46);
    UTULY_PasseR = masterData5.arrangedPasseRData(:,:,47);
    UTULZ_PasseR = masterData5.arrangedPasseRData(:,:,48);

    datasetLLLabX_PasseR = cell2struct(num2cell(LLLabX_PasseR, 1), compose('Subject%d', 1:size(LLLabX_PasseR, 2)), 2);
    datasetLLLabY_PasseR = cell2struct(num2cell(LLLabY_PasseR, 1), compose('Subject%d', 1:size(LLLabY_PasseR, 2)), 2);
    datasetLLLabZ_PasseR = cell2struct(num2cell(LLLabZ_PasseR, 1), compose('Subject%d', 1:size(LLLabZ_PasseR, 2)), 2);
    datasetLLPelX_PasseR = cell2struct(num2cell(LLPelX_PasseR, 1), compose('Subject%d', 1:size(LLPelX_PasseR, 2)), 2);
    datasetLLPelY_PasseR = cell2struct(num2cell(LLPelY_PasseR, 1), compose('Subject%d', 1:size(LLPelY_PasseR, 2)), 2);
    datasetLLPelZ_PasseR = cell2struct(num2cell(LLPelZ_PasseR, 1), compose('Subject%d', 1:size(LLPelZ_PasseR, 2)), 2);
    datasetLTLabX_PasseR = cell2struct(num2cell(LTLabX_PasseR, 1), compose('Subject%d', 1:size(LTLabX_PasseR, 2)), 2);
    datasetLTLabY_PasseR = cell2struct(num2cell(LTLabY_PasseR, 1), compose('Subject%d', 1:size(LTLabY_PasseR, 2)), 2);
    datasetLTLabZ_PasseR = cell2struct(num2cell(LTLabZ_PasseR, 1), compose('Subject%d', 1:size(LTLabZ_PasseR, 2)), 2);
    datasetLTLLX_PasseR = cell2struct(num2cell(LTLLX_PasseR, 1), compose('Subject%d', 1:size(LTLLX_PasseR, 2)), 2);
    datasetLTLLY_PasseR = cell2struct(num2cell(LTLLY_PasseR, 1), compose('Subject%d', 1:size(LTLLY_PasseR, 2)), 2);
    datasetLTLLZ_PasseR = cell2struct(num2cell(LTLLZ_PasseR, 1), compose('Subject%d', 1:size(LTLLZ_PasseR, 2)), 2);
    datasetLTPelX_PasseR = cell2struct(num2cell(LTPelX_PasseR, 1), compose('Subject%d', 1:size(LTPelX_PasseR, 2)), 2);
    datasetLTPelY_PasseR = cell2struct(num2cell(LTPelY_PasseR, 1), compose('Subject%d', 1:size(LTPelY_PasseR, 2)), 2);
    datasetLTPelZ_PasseR = cell2struct(num2cell(LTPelZ_PasseR, 1), compose('Subject%d', 1:size(LTPelZ_PasseR, 2)), 2);
    datasetLTULX_PasseR = cell2struct(num2cell(LTULX_PasseR, 1), compose('Subject%d', 1:size(LTULX_PasseR, 2)), 2);
    datasetLTULY_PasseR = cell2struct(num2cell(LTULY_PasseR, 1), compose('Subject%d', 1:size(LTULY_PasseR, 2)), 2);    
    datasetLTULZ_PasseR = cell2struct(num2cell(LTULZ_PasseR, 1), compose('Subject%d', 1:size(LTULZ_PasseR, 2)), 2);
    datasetPelLabX_PasseR = cell2struct(num2cell(PelLabX_PasseR, 1), compose('Subject%d', 1:size(PelLabX_PasseR, 2)), 2);
    datasetPelLabY_PasseR = cell2struct(num2cell(PelLabY_PasseR, 1), compose('Subject%d', 1:size(PelLabY_PasseR, 2)), 2);
    datasetPelLabZ_PasseR = cell2struct(num2cell(PelLabZ_PasseR, 1), compose('Subject%d', 1:size(PelLabZ_PasseR, 2)), 2);
    datasetTrunkLabX_PasseR = cell2struct(num2cell(TrunkLabX_PasseR, 1), compose('Subject%d', 1:size(TrunkLabX_PasseR, 2)), 2);    
    datasetTrunkLabY_PasseR = cell2struct(num2cell(TrunkLabY_PasseR, 1), compose('Subject%d', 1:size(TrunkLabY_PasseR, 2)), 2);
    datasetTrunkLabZ_PasseR = cell2struct(num2cell(TrunkLabZ_PasseR, 1), compose('Subject%d', 1:size(TrunkLabZ_PasseR, 2)), 2);
    datasetULLabX_PasseR = cell2struct(num2cell(ULLabX_PasseR, 1), compose('Subject%d', 1:size(ULLabX_PasseR, 2)), 2);
    datasetULLabY_PasseR = cell2struct(num2cell(ULLabY_PasseR, 1), compose('Subject%d', 1:size(ULLabY_PasseR, 2)), 2);
    datasetULLabZ_PasseR = cell2struct(num2cell(ULLabZ_PasseR, 1), compose('Subject%d', 1:size(ULLabZ_PasseR, 2)), 2);
    datasetULLLX_PasseR = cell2struct(num2cell(ULLLX_PasseR, 1), compose('Subject%d', 1:size(ULLLX_PasseR, 2)), 2);
    datasetULLLY_PasseR = cell2struct(num2cell(ULLLY_PasseR, 1), compose('Subject%d', 1:size(ULLLY_PasseR, 2)), 2);
    datasetULLLZ_PasseR = cell2struct(num2cell(ULLLZ_PasseR, 1), compose('Subject%d', 1:size(ULLLZ_PasseR, 2)), 2);
    datasetULPelX_PasseR = cell2struct(num2cell(ULPelX_PasseR, 1), compose('Subject%d', 1:size(ULPelX_PasseR, 2)), 2);
    datasetULPelY_PasseR = cell2struct(num2cell(ULPelY_PasseR, 1), compose('Subject%d', 1:size(ULPelY_PasseR, 2)), 2);
    datasetULPelZ_PasseR = cell2struct(num2cell(ULPelZ_PasseR, 1), compose('Subject%d', 1:size(ULPelZ_PasseR, 2)), 2);
    datasetUTLabX_PasseR = cell2struct(num2cell(UTLabX_PasseR, 1), compose('Subject%d', 1:size(UTLabX_PasseR, 2)), 2);
    datasetUTLabY_PasseR = cell2struct(num2cell(UTLabY_PasseR, 1), compose('Subject%d', 1:size(UTLabY_PasseR, 2)), 2);
    datasetUTLabZ_PasseR = cell2struct(num2cell(UTLabZ_PasseR, 1), compose('Subject%d', 1:size(UTLabZ_PasseR, 2)), 2);
    datasetUTLLX_PasseR = cell2struct(num2cell(UTLLX_PasseR, 1), compose('Subject%d', 1:size(UTLLX_PasseR, 2)), 2);
    datasetUTLLY_PasseR = cell2struct(num2cell(UTLLY_PasseR, 1), compose('Subject%d', 1:size(UTLLY_PasseR, 2)), 2);
    datasetUTLLZ_PasseR = cell2struct(num2cell(UTLLZ_PasseR, 1), compose('Subject%d', 1:size(UTLLZ_PasseR, 2)), 2);
    datasetUTLTX_PasseR = cell2struct(num2cell(UTLTX_PasseR, 1), compose('Subject%d', 1:size(UTLTX_PasseR, 2)), 2);
    datasetUTLTY_PasseR = cell2struct(num2cell(UTLTY_PasseR, 1), compose('Subject%d', 1:size(UTLTY_PasseR, 2)), 2);
    datasetUTLTZ_PasseR = cell2struct(num2cell(UTLTZ_PasseR, 1), compose('Subject%d', 1:size(UTLTZ_PasseR, 2)), 2);
    datasetUTPelX_PasseR = cell2struct(num2cell(UTPelX_PasseR, 1), compose('Subject%d', 1:size(UTPelX_PasseR, 2)), 2);
    datasetUTPelY_PasseR = cell2struct(num2cell(UTPelY_PasseR, 1), compose('Subject%d', 1:size(UTPelY_PasseR, 2)), 2);
    datasetUTPelZ_PasseR = cell2struct(num2cell(UTPelZ_PasseR, 1), compose('Subject%d', 1:size(UTPelZ_PasseR, 2)), 2);
    datasetUTULX_PasseR = cell2struct(num2cell(UTULX_PasseR, 1), compose('Subject%d', 1:size(UTULX_PasseR, 2)), 2);
    datasetUTULY_PasseR = cell2struct(num2cell(UTULY_PasseR, 1), compose('Subject%d', 1:size(UTULY_PasseR, 2)), 2);
    datasetUTULZ_PasseR = cell2struct(num2cell(UTULZ_PasseR, 1), compose('Subject%d', 1:size(UTULZ_PasseR, 2)), 2);    
    
    save datasetFM;

%     save datasetLLLabX_ArabL;
%     save datasetLLLabY_ArabL;
%     save datasetLLLabZ_ArabL;
%     save datasetLLPelX_ArabL;
%     save datasetLLPelY_ArabL;
%     save datasetLLPelZ_ArabL;
%     save datasetLTLabX_ArabL;
%     save datasetLTLabY_ArabL;
%     save datasetLTLabZ_ArabL;
%     save datasetLTLLX_ArabL;
%     save datasetLTLLY_ArabL;
%     save datasetLTLLZ_ArabL;
%     save datasetLTPelvisX_ArabL;
%     save datasetLTPelvisY_ArabL;
%     save datasetLTPelvisZ_ArabL;
%     save datasetLTULX_ArabL;
%     save datasetLTULY_ArabL;    
%     save datasetLTULZ_ArabL;
%     save datasetPelvisLabX_ArabL;
%     save datasetPelvisLabY_ArabL;
%     save datasetPelvisLabZ_ArabL;
%     save datasetTrunk2LABX_ArabL;    
%     save datasetTrunk2LABY_ArabL;
%     save datasetTrunk2LABZ_ArabL;
%     save datasetULLABX_ArabL;
%     save datasetULLABY_ArabL;
%     save datasetULLABZ_ArabL;
%     save datasetULLLX_ArabL;
%     save datasetULLLY_ArabL;
%     save datasetULLLZ_ArabL;
%     save datasetULPelvisX_ArabL;
%     save datasetULPelvisY_ArabL;
%     save datasetULPelvisZ_ArabL;
%     save datasetUTLABX_ArabL;
%     save datasetUTLABY_ArabL;
%     save datasetUTLABZ_ArabL;
%     save datasetUTLLX_ArabL;
%     save datasetUTLLY_ArabL;
%     save datasetUTLLZ_ArabL;
%     save datasetUTLTX_ArabL;
%     save datasetUTLTY_ArabL;
%     save datasetUTLTZ_ArabL;
%     save datasetUTPelvisX_ArabL;
%     save datasetUTPelvisY_ArabL;
%     save datasetUTPelvisZ_ArabL;
%     save datasetUTULX_ArabL;
%     save datasetUTULY_ArabL;
%     save datasetUTULZ_ArabL;


end