function prepareRotationTTests

    %8 groups SitRotateR
    masterData = load('arrangedSitRotateRVariableData.mat','arrangedSitRotateRVariableData');
    
    LLLABX_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,1);
    LLLABY_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,2);
    LLLABZ_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,3);
    LLPelvisX_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,4);
    LLPelvisY_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,5);
    LLPelvisZ_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,6);
    LTLABX_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,7);
    LTLABY_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,8);
    LTLABZ_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,9);
    LTLLX_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,10);
    LTLLY_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,11);
    LTLLZ_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,12);
    LTPelvisX_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,13);
    LTPelvisY_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,14);
    LTPelvisZ_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,15);
    LTULX_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,16);
    LTULY_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,17);
    LTULZ_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,18);
    PelvisLABX_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,19);
    PelvisLABY_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,20);
    PelvisLABZ_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,21);
    Trunk2LABX_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,22);
    Trunk2LABY_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,23);
    Trunk2LABZ_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,24);
    Trunk2LABVelX_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,25);
    Trunk2LABVelY_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,26);
    Trunk2LABVelZ_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,27);
    ULLABX_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,28);
    ULLABY_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,29);
    ULLABZ_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,30);
    ULLLX_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,31);
    ULLLY_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,32);
    ULLLZ_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,33);
    ULPelvisX_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,34);
    ULPelvisY_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,35);
    ULPelvisZ_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,36);
    UTLABX_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,37);
    UTLABY_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,38);
    UTLABZ_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,39);
    UTLLX_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,40);
    UTLLY_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,41);
    UTLLZ_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,42);
    UTLTX_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,43);
    UTLTY_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,44);
    UTLTZ_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,45);
    UTPelvisX_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,46);
    UTPelvisY_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,47);
    UTPelvisZ_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,48);
    UTULX_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,49);
    UTULY_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,50);
    UTULZ_SitRotateR = masterData.arrangedSitRotateRVariableData(:,:,51);

    datasetLLLABX_SitRotateR = cell2struct(num2cell(LLLABX_SitRotateR, 1), compose('Subject%d', 1:size(LLLABX_SitRotateR, 2)), 2);
    datasetLLLABY_SitRotateR = cell2struct(num2cell(LLLABY_SitRotateR, 1), compose('Subject%d', 1:size(LLLABY_SitRotateR, 2)), 2);
    datasetLLLABZ_SitRotateR = cell2struct(num2cell(LLLABZ_SitRotateR, 1), compose('Subject%d', 1:size(LLLABZ_SitRotateR, 2)), 2);
    datasetLLPelvisX_SitRotateR = cell2struct(num2cell(LLPelvisX_SitRotateR, 1), compose('Subject%d', 1:size(LLPelvisX_SitRotateR, 2)), 2);
    datasetLLPelvisY_SitRotateR = cell2struct(num2cell(LLPelvisY_SitRotateR, 1), compose('Subject%d', 1:size(LLPelvisY_SitRotateR, 2)), 2);
    datasetLLPelvisZ_SitRotateR = cell2struct(num2cell(LLPelvisZ_SitRotateR, 1), compose('Subject%d', 1:size(LLPelvisZ_SitRotateR, 2)), 2);
    datasetLTLABX_SitRotateR = cell2struct(num2cell(LTLABX_SitRotateR, 1), compose('Subject%d', 1:size(LTLABX_SitRotateR, 2)), 2);
    datasetLTLABY_SitRotateR = cell2struct(num2cell(LTLABY_SitRotateR, 1), compose('Subject%d', 1:size(LTLABY_SitRotateR, 2)), 2);
    datasetLTLABZ_SitRotateR = cell2struct(num2cell(LTLABZ_SitRotateR, 1), compose('Subject%d', 1:size(LTLABZ_SitRotateR, 2)), 2);
    datasetLTLLX_SitRotateR = cell2struct(num2cell(LTLLX_SitRotateR, 1), compose('Subject%d', 1:size(LTLLX_SitRotateR, 2)), 2);
    datasetLTLLY_SitRotateR = cell2struct(num2cell(LTLLY_SitRotateR, 1), compose('Subject%d', 1:size(LTLLY_SitRotateR, 2)), 2);
    datasetLTLLZ_SitRotateR = cell2struct(num2cell(LTLLZ_SitRotateR, 1), compose('Subject%d', 1:size(LTLLZ_SitRotateR, 2)), 2);
    datasetLTPelvisX_SitRotateR = cell2struct(num2cell(LTPelvisX_SitRotateR, 1), compose('Subject%d', 1:size(LTPelvisX_SitRotateR, 2)), 2);
    datasetLTPelvisY_SitRotateR = cell2struct(num2cell(LTPelvisY_SitRotateR, 1), compose('Subject%d', 1:size(LTPelvisY_SitRotateR, 2)), 2);
    datasetLTPelvisZ_SitRotateR = cell2struct(num2cell(LTPelvisZ_SitRotateR, 1), compose('Subject%d', 1:size(LTPelvisZ_SitRotateR, 2)), 2);
    datasetLTULX_SitRotateR = cell2struct(num2cell(LTULX_SitRotateR, 1), compose('Subject%d', 1:size(LTULX_SitRotateR, 2)), 2);
    datasetLTULY_SitRotateR = cell2struct(num2cell(LTULY_SitRotateR, 1), compose('Subject%d', 1:size(LTULY_SitRotateR, 2)), 2);    
    datasetLTULZ_SitRotateR = cell2struct(num2cell(LTULZ_SitRotateR, 1), compose('Subject%d', 1:size(LTULZ_SitRotateR, 2)), 2);
    datasetPelvisLABX_SitRotateR = cell2struct(num2cell(PelvisLABX_SitRotateR, 1), compose('Subject%d', 1:size(PelvisLABX_SitRotateR, 2)), 2);
    datasetPelvisLABY_SitRotateR = cell2struct(num2cell(PelvisLABY_SitRotateR, 1), compose('Subject%d', 1:size(PelvisLABY_SitRotateR, 2)), 2);
    datasetPelvisLABZ_SitRotateR = cell2struct(num2cell(PelvisLABZ_SitRotateR, 1), compose('Subject%d', 1:size(PelvisLABZ_SitRotateR, 2)), 2);
    datasetTrunk2LABX_SitRotateR = cell2struct(num2cell(Trunk2LABX_SitRotateR, 1), compose('Subject%d', 1:size(Trunk2LABX_SitRotateR, 2)), 2);    
    datasetTrunk2LABY_SitRotateR = cell2struct(num2cell(Trunk2LABY_SitRotateR, 1), compose('Subject%d', 1:size(Trunk2LABY_SitRotateR, 2)), 2);
    datasetTrunk2LABZ_SitRotateR = cell2struct(num2cell(Trunk2LABZ_SitRotateR, 1), compose('Subject%d', 1:size(Trunk2LABZ_SitRotateR, 2)), 2);
    datasetTrunk2LABVelX_SitRotateR = cell2struct(num2cell(Trunk2LABVelX_SitRotateR, 1), compose('Subject%d', 1:size(Trunk2LABVelX_SitRotateR, 2)), 2);
    datasetTrunk2LABVelY_SitRotateR = cell2struct(num2cell(Trunk2LABVelY_SitRotateR, 1), compose('Subject%d', 1:size(Trunk2LABVelY_SitRotateR, 2)), 2);
    datasetTrunk2LABVelZ_SitRotateR = cell2struct(num2cell(Trunk2LABVelZ_SitRotateR, 1), compose('Subject%d', 1:size(Trunk2LABVelZ_SitRotateR, 2)), 2);
    datasetULLABX_SitRotateR = cell2struct(num2cell(ULLABX_SitRotateR, 1), compose('Subject%d', 1:size(ULLABX_SitRotateR, 2)), 2);
    datasetULLABY_SitRotateR = cell2struct(num2cell(ULLABY_SitRotateR, 1), compose('Subject%d', 1:size(ULLABY_SitRotateR, 2)), 2);
    datasetULLABZ_SitRotateR = cell2struct(num2cell(ULLABZ_SitRotateR, 1), compose('Subject%d', 1:size(ULLABZ_SitRotateR, 2)), 2);
    datasetULLLX_SitRotateR = cell2struct(num2cell(ULLLX_SitRotateR, 1), compose('Subject%d', 1:size(ULLLX_SitRotateR, 2)), 2);
    datasetULLLY_SitRotateR = cell2struct(num2cell(ULLLY_SitRotateR, 1), compose('Subject%d', 1:size(ULLLY_SitRotateR, 2)), 2);
    datasetULLLZ_SitRotateR = cell2struct(num2cell(ULLLZ_SitRotateR, 1), compose('Subject%d', 1:size(ULLLZ_SitRotateR, 2)), 2);
    datasetULPelvisX_SitRotateR = cell2struct(num2cell(ULPelvisX_SitRotateR, 1), compose('Subject%d', 1:size(ULPelvisX_SitRotateR, 2)), 2);
    datasetULPelvisY_SitRotateR = cell2struct(num2cell(ULPelvisY_SitRotateR, 1), compose('Subject%d', 1:size(ULPelvisY_SitRotateR, 2)), 2);
    datasetULPelvisZ_SitRotateR = cell2struct(num2cell(ULPelvisZ_SitRotateR, 1), compose('Subject%d', 1:size(ULPelvisZ_SitRotateR, 2)), 2);
    datasetUTLABX_SitRotateR = cell2struct(num2cell(UTLABX_SitRotateR, 1), compose('Subject%d', 1:size(UTLABX_SitRotateR, 2)), 2);
    datasetUTLABY_SitRotateR = cell2struct(num2cell(UTLABY_SitRotateR, 1), compose('Subject%d', 1:size(UTLABY_SitRotateR, 2)), 2);
    datasetUTLABZ_SitRotateR = cell2struct(num2cell(UTLABZ_SitRotateR, 1), compose('Subject%d', 1:size(UTLABZ_SitRotateR, 2)), 2);
    datasetUTLLX_SitRotateR = cell2struct(num2cell(UTLLX_SitRotateR, 1), compose('Subject%d', 1:size(UTLLX_SitRotateR, 2)), 2);
    datasetUTLLY_SitRotateR = cell2struct(num2cell(UTLLY_SitRotateR, 1), compose('Subject%d', 1:size(UTLLY_SitRotateR, 2)), 2);
    datasetUTLLZ_SitRotateR = cell2struct(num2cell(UTLLZ_SitRotateR, 1), compose('Subject%d', 1:size(UTLLZ_SitRotateR, 2)), 2);
    datasetUTLTX_SitRotateR = cell2struct(num2cell(UTLTX_SitRotateR, 1), compose('Subject%d', 1:size(UTLTX_SitRotateR, 2)), 2);
    datasetUTLTY_SitRotateR = cell2struct(num2cell(UTLTY_SitRotateR, 1), compose('Subject%d', 1:size(UTLTY_SitRotateR, 2)), 2);
    datasetUTLTZ_SitRotateR = cell2struct(num2cell(UTLTZ_SitRotateR, 1), compose('Subject%d', 1:size(UTLTZ_SitRotateR, 2)), 2);
    datasetUTPelvisX_SitRotateR = cell2struct(num2cell(UTPelvisX_SitRotateR, 1), compose('Subject%d', 1:size(UTPelvisX_SitRotateR, 2)), 2);
    datasetUTPelvisY_SitRotateR = cell2struct(num2cell(UTPelvisY_SitRotateR, 1), compose('Subject%d', 1:size(UTPelvisY_SitRotateR, 2)), 2);
    datasetUTPelvisZ_SitRotateR = cell2struct(num2cell(UTPelvisZ_SitRotateR, 1), compose('Subject%d', 1:size(UTPelvisZ_SitRotateR, 2)), 2);
    datasetUTULX_SitRotateR = cell2struct(num2cell(UTULX_SitRotateR, 1), compose('Subject%d', 1:size(UTULX_SitRotateR, 2)), 2);
    datasetUTULY_SitRotateR = cell2struct(num2cell(UTULY_SitRotateR, 1), compose('Subject%d', 1:size(UTULY_SitRotateR, 2)), 2);
    datasetUTULZ_SitRotateR = cell2struct(num2cell(UTULZ_SitRotateR, 1), compose('Subject%d', 1:size(UTULZ_SitRotateR, 2)), 2);
    
    save datasetLLLABX_SitRotateR;
    save datasetLLLABY_SitRotateR;
    save datasetLLLABZ_SitRotateR;
    save datasetLLPelvisX_SitRotateR;
    save datasetLLPelvisY_SitRotateR;
    save datasetLLPelvisZ_SitRotateR;
    save datasetLTLABX_SitRotateR;
    save datasetLTLABY_SitRotateR;
    save datasetLTLABZ_SitRotateR;
    save datasetLTLLX_SitRotateR;
    save datasetLTLLY_SitRotateR;
    save datasetLTLLZ_SitRotateR;
    save datasetLTPelvisX_SitRotateR;
    save datasetLTPelvisY_SitRotateR;
    save datasetLTPelvisZ_SitRotateR;
    save datasetLTULX_SitRotateR;
    save datasetLTULY_SitRotateR;    
    save datasetLTULZ_SitRotateR;
    save datasetPelvisLABX_SitRotateR;
    save datasetPelvisLABY_SitRotateR;
    save datasetPelvisLABZ_SitRotateR;
    save datasetTrunk2LABX_SitRotateR;    
    save datasetTrunk2LABY_SitRotateR;
    save datasetTrunk2LABZ_SitRotateR;
    save datasetTrunk2LABVelX_SitRotateR;
    save datasetTrunk2LABVelY_SitRotateR;
    save datasetTrunk2LABVelZ_SitRotateR;
    save datasetULLABX_SitRotateR;
    save datasetULLABY_SitRotateR;
    save datasetULLABZ_SitRotateR;
    save datasetULLLX_SitRotateR;
    save datasetULLLY_SitRotateR;
    save datasetULLLZ_SitRotateR;
    save datasetULPelvisX_SitRotateR;
    save datasetULPelvisY_SitRotateR;
    save datasetULPelvisZ_SitRotateR;
    save datasetUTLABX_SitRotateR;
    save datasetUTLABY_SitRotateR;
    save datasetUTLABZ_SitRotateR;
    save datasetUTLLX_SitRotateR;
    save datasetUTLLY_SitRotateR;
    save datasetUTLLZ_SitRotateR;
    save datasetUTLTX_SitRotateR;
    save datasetUTLTY_SitRotateR;
    save datasetUTLTZ_SitRotateR;
    save datasetUTPelvisX_SitRotateR;
    save datasetUTPelvisY_SitRotateR;
    save datasetUTPelvisZ_SitRotateR;
    save datasetUTULX_SitRotateR;
    save datasetUTULY_SitRotateR;
    save datasetUTULZ_SitRotateR;


end