function prepareAverageRotationTests

    %4 groups
    masterData1 = load('arrangedRotateL1VariableData.mat','arrangedRotateL1VariableData');
    masterData2 = load('arrangedRotateL2VariableData.mat','arrangedRotateL2VariableData');
    
    LLLABX_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,1)+masterData2.arrangedRotateL2VariableData(:,:,1))/2;
    LLLABY_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,2)+masterData2.arrangedRotateL2VariableData(:,:,2))/2;
    LLLABZ_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,3)+masterData2.arrangedRotateL2VariableData(:,:,3))/2;
    LLPelvisX_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,4)+masterData2.arrangedRotateL2VariableData(:,:,4))/2;
    LLPelvisY_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,5)+masterData2.arrangedRotateL2VariableData(:,:,5))/2;
    LLPelvisZ_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,6)+masterData2.arrangedRotateL2VariableData(:,:,6))/2;
    LTLABX_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,7)+masterData2.arrangedRotateL2VariableData(:,:,7))/2;
    LTLABY_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,8)+masterData2.arrangedRotateL2VariableData(:,:,8))/2;
    LTLABZ_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,9)+masterData2.arrangedRotateL2VariableData(:,:,9))/2;
    LTLLX_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,10)+masterData2.arrangedRotateL2VariableData(:,:,10))/2;
    LTLLY_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,11)+masterData2.arrangedRotateL2VariableData(:,:,11))/2;
    LTLLZ_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,12)+masterData2.arrangedRotateL2VariableData(:,:,12))/2;
    LTPelvisX_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,13)+masterData2.arrangedRotateL2VariableData(:,:,13))/2;
    LTPelvisY_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,14)+masterData2.arrangedRotateL2VariableData(:,:,14))/2;
    LTPelvisZ_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,15)+masterData2.arrangedRotateL2VariableData(:,:,15))/2;
    LTULX_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,16)+masterData2.arrangedRotateL2VariableData(:,:,16))/2;
    LTULY_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,17)+masterData2.arrangedRotateL2VariableData(:,:,17))/2;
    LTULZ_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,18)+masterData2.arrangedRotateL2VariableData(:,:,18))/2;
    PelvisLABX_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,19)+masterData2.arrangedRotateL2VariableData(:,:,19))/2;
    PelvisLABY_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,20)+masterData2.arrangedRotateL2VariableData(:,:,20))/2;
    PelvisLABZ_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,21)+masterData2.arrangedRotateL2VariableData(:,:,21))/2;
    Trunk2LABX_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,22)+masterData2.arrangedRotateL2VariableData(:,:,22))/2;
    Trunk2LABY_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,23)+masterData2.arrangedRotateL2VariableData(:,:,23))/2;
    Trunk2LABZ_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,24)+masterData2.arrangedRotateL2VariableData(:,:,24))/2;
    Trunk2LABVelX_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,25)+masterData2.arrangedRotateL2VariableData(:,:,25))/2;
    Trunk2LABVelY_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,26)+masterData2.arrangedRotateL2VariableData(:,:,26))/2;
    Trunk2LABVelZ_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,27)+masterData2.arrangedRotateL2VariableData(:,:,27))/2;
    ULLABX_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,28)+masterData2.arrangedRotateL2VariableData(:,:,28))/2;
    ULLABY_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,29)+masterData2.arrangedRotateL2VariableData(:,:,29))/2;
    ULLABZ_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,30)+masterData2.arrangedRotateL2VariableData(:,:,30))/2;
    ULLLX_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,31)+masterData2.arrangedRotateL2VariableData(:,:,31))/2;
    ULLLY_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,32)+masterData2.arrangedRotateL2VariableData(:,:,32))/2;
    ULLLZ_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,33)+masterData2.arrangedRotateL2VariableData(:,:,33))/2;
    ULPelvisX_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,34)+masterData2.arrangedRotateL2VariableData(:,:,34))/2;
    ULPelvisY_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,35)+masterData2.arrangedRotateL2VariableData(:,:,35))/2;
    ULPelvisZ_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,36)+masterData2.arrangedRotateL2VariableData(:,:,36))/2;
    UTLABX_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,37)+masterData2.arrangedRotateL2VariableData(:,:,37))/2;
    UTLABY_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,38)+masterData2.arrangedRotateL2VariableData(:,:,38))/2;
    UTLABZ_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,39)+masterData2.arrangedRotateL2VariableData(:,:,39))/2;
    UTLLX_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,40)+masterData2.arrangedRotateL2VariableData(:,:,40))/2;
    UTLLY_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,41)+masterData2.arrangedRotateL2VariableData(:,:,41))/2;
    UTLLZ_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,42)+masterData2.arrangedRotateL2VariableData(:,:,42))/2;
    UTLTX_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,43)+masterData2.arrangedRotateL2VariableData(:,:,43))/2;
    UTLTY_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,44)+masterData2.arrangedRotateL2VariableData(:,:,44))/2;
    UTLTZ_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,45)+masterData2.arrangedRotateL2VariableData(:,:,45))/2;
    UTPelvisX_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,46)+masterData2.arrangedRotateL2VariableData(:,:,46))/2;
    UTPelvisY_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,47)+masterData2.arrangedRotateL2VariableData(:,:,47))/2;
    UTPelvisZ_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,48)+masterData2.arrangedRotateL2VariableData(:,:,48))/2;
    UTULX_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,49)+masterData2.arrangedRotateL2VariableData(:,:,49))/2;
    UTULY_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,50)+masterData2.arrangedRotateL2VariableData(:,:,50))/2;
    UTULZ_RotateL = (masterData1.arrangedRotateL1VariableData(:,:,51)+masterData2.arrangedRotateL2VariableData(:,:,51))/2;

    datasetLLLABX_RotateL = cell2struct(num2cell(LLLABX_RotateL, 1), compose('Subject%d', 1:size(LLLABX_RotateL, 2)), 2);
    datasetLLLABY_RotateL = cell2struct(num2cell(LLLABY_RotateL, 1), compose('Subject%d', 1:size(LLLABY_RotateL, 2)), 2);
    datasetLLLABZ_RotateL = cell2struct(num2cell(LLLABZ_RotateL, 1), compose('Subject%d', 1:size(LLLABZ_RotateL, 2)), 2);
    datasetLLPelvisX_RotateL = cell2struct(num2cell(LLPelvisX_RotateL, 1), compose('Subject%d', 1:size(LLPelvisX_RotateL, 2)), 2);
    datasetLLPelvisY_RotateL = cell2struct(num2cell(LLPelvisY_RotateL, 1), compose('Subject%d', 1:size(LLPelvisY_RotateL, 2)), 2);
    datasetLLPelvisZ_RotateL = cell2struct(num2cell(LLPelvisZ_RotateL, 1), compose('Subject%d', 1:size(LLPelvisZ_RotateL, 2)), 2);
    datasetLTLABX_RotateL = cell2struct(num2cell(LTLABX_RotateL, 1), compose('Subject%d', 1:size(LTLABX_RotateL, 2)), 2);
    datasetLTLABY_RotateL = cell2struct(num2cell(LTLABY_RotateL, 1), compose('Subject%d', 1:size(LTLABY_RotateL, 2)), 2);
    datasetLTLABZ_RotateL = cell2struct(num2cell(LTLABZ_RotateL, 1), compose('Subject%d', 1:size(LTLABZ_RotateL, 2)), 2);
    datasetLTLLX_RotateL = cell2struct(num2cell(LTLLX_RotateL, 1), compose('Subject%d', 1:size(LTLLX_RotateL, 2)), 2);
    datasetLTLLY_RotateL = cell2struct(num2cell(LTLLY_RotateL, 1), compose('Subject%d', 1:size(LTLLY_RotateL, 2)), 2);
    datasetLTLLZ_RotateL = cell2struct(num2cell(LTLLZ_RotateL, 1), compose('Subject%d', 1:size(LTLLZ_RotateL, 2)), 2);
    datasetLTPelvisX_RotateL = cell2struct(num2cell(LTPelvisX_RotateL, 1), compose('Subject%d', 1:size(LTPelvisX_RotateL, 2)), 2);
    datasetLTPelvisY_RotateL = cell2struct(num2cell(LTPelvisY_RotateL, 1), compose('Subject%d', 1:size(LTPelvisY_RotateL, 2)), 2);
    datasetLTPelvisZ_RotateL = cell2struct(num2cell(LTPelvisZ_RotateL, 1), compose('Subject%d', 1:size(LTPelvisZ_RotateL, 2)), 2);
    datasetLTULX_RotateL = cell2struct(num2cell(LTULX_RotateL, 1), compose('Subject%d', 1:size(LTULX_RotateL, 2)), 2);
    datasetLTULY_RotateL = cell2struct(num2cell(LTULY_RotateL, 1), compose('Subject%d', 1:size(LTULY_RotateL, 2)), 2);    
    datasetLTULZ_RotateL = cell2struct(num2cell(LTULZ_RotateL, 1), compose('Subject%d', 1:size(LTULZ_RotateL, 2)), 2);
    datasetPelvisLABX_RotateL = cell2struct(num2cell(PelvisLABX_RotateL, 1), compose('Subject%d', 1:size(PelvisLABX_RotateL, 2)), 2);
    datasetPelvisLABY_RotateL = cell2struct(num2cell(PelvisLABY_RotateL, 1), compose('Subject%d', 1:size(PelvisLABY_RotateL, 2)), 2);
    datasetPelvisLABZ_RotateL = cell2struct(num2cell(PelvisLABZ_RotateL, 1), compose('Subject%d', 1:size(PelvisLABZ_RotateL, 2)), 2);
    datasetTrunk2LABX_RotateL = cell2struct(num2cell(Trunk2LABX_RotateL, 1), compose('Subject%d', 1:size(Trunk2LABX_RotateL, 2)), 2);    
    datasetTrunk2LABY_RotateL = cell2struct(num2cell(Trunk2LABY_RotateL, 1), compose('Subject%d', 1:size(Trunk2LABY_RotateL, 2)), 2);
    datasetTrunk2LABZ_RotateL = cell2struct(num2cell(Trunk2LABZ_RotateL, 1), compose('Subject%d', 1:size(Trunk2LABZ_RotateL, 2)), 2);
    datasetTrunk2LABVelX_RotateL = cell2struct(num2cell(Trunk2LABVelX_RotateL, 1), compose('Subject%d', 1:size(Trunk2LABVelX_RotateL, 2)), 2);
    datasetTrunk2LABVelY_RotateL = cell2struct(num2cell(Trunk2LABVelY_RotateL, 1), compose('Subject%d', 1:size(Trunk2LABVelY_RotateL, 2)), 2);
    datasetTrunk2LABVelZ_RotateL = cell2struct(num2cell(Trunk2LABVelZ_RotateL, 1), compose('Subject%d', 1:size(Trunk2LABVelZ_RotateL, 2)), 2);
    datasetULLABX_RotateL = cell2struct(num2cell(ULLABX_RotateL, 1), compose('Subject%d', 1:size(ULLABX_RotateL, 2)), 2);
    datasetULLABY_RotateL = cell2struct(num2cell(ULLABY_RotateL, 1), compose('Subject%d', 1:size(ULLABY_RotateL, 2)), 2);
    datasetULLABZ_RotateL = cell2struct(num2cell(ULLABZ_RotateL, 1), compose('Subject%d', 1:size(ULLABZ_RotateL, 2)), 2);
    datasetULLLX_RotateL = cell2struct(num2cell(ULLLX_RotateL, 1), compose('Subject%d', 1:size(ULLLX_RotateL, 2)), 2);
    datasetULLLY_RotateL = cell2struct(num2cell(ULLLY_RotateL, 1), compose('Subject%d', 1:size(ULLLY_RotateL, 2)), 2);
    datasetULLLZ_RotateL = cell2struct(num2cell(ULLLZ_RotateL, 1), compose('Subject%d', 1:size(ULLLZ_RotateL, 2)), 2);
    datasetULPelvisX_RotateL = cell2struct(num2cell(ULPelvisX_RotateL, 1), compose('Subject%d', 1:size(ULPelvisX_RotateL, 2)), 2);
    datasetULPelvisY_RotateL = cell2struct(num2cell(ULPelvisY_RotateL, 1), compose('Subject%d', 1:size(ULPelvisY_RotateL, 2)), 2);
    datasetULPelvisZ_RotateL = cell2struct(num2cell(ULPelvisZ_RotateL, 1), compose('Subject%d', 1:size(ULPelvisZ_RotateL, 2)), 2);
    datasetUTLABX_RotateL = cell2struct(num2cell(UTLABX_RotateL, 1), compose('Subject%d', 1:size(UTLABX_RotateL, 2)), 2);
    datasetUTLABY_RotateL = cell2struct(num2cell(UTLABY_RotateL, 1), compose('Subject%d', 1:size(UTLABY_RotateL, 2)), 2);
    datasetUTLABZ_RotateL = cell2struct(num2cell(UTLABZ_RotateL, 1), compose('Subject%d', 1:size(UTLABZ_RotateL, 2)), 2);
    datasetUTLLX_RotateL = cell2struct(num2cell(UTLLX_RotateL, 1), compose('Subject%d', 1:size(UTLLX_RotateL, 2)), 2);
    datasetUTLLY_RotateL = cell2struct(num2cell(UTLLY_RotateL, 1), compose('Subject%d', 1:size(UTLLY_RotateL, 2)), 2);
    datasetUTLLZ_RotateL = cell2struct(num2cell(UTLLZ_RotateL, 1), compose('Subject%d', 1:size(UTLLZ_RotateL, 2)), 2);
    datasetUTLTX_RotateL = cell2struct(num2cell(UTLTX_RotateL, 1), compose('Subject%d', 1:size(UTLTX_RotateL, 2)), 2);
    datasetUTLTY_RotateL = cell2struct(num2cell(UTLTY_RotateL, 1), compose('Subject%d', 1:size(UTLTY_RotateL, 2)), 2);
    datasetUTLTZ_RotateL = cell2struct(num2cell(UTLTZ_RotateL, 1), compose('Subject%d', 1:size(UTLTZ_RotateL, 2)), 2);
    datasetUTPelvisX_RotateL = cell2struct(num2cell(UTPelvisX_RotateL, 1), compose('Subject%d', 1:size(UTPelvisX_RotateL, 2)), 2);
    datasetUTPelvisY_RotateL = cell2struct(num2cell(UTPelvisY_RotateL, 1), compose('Subject%d', 1:size(UTPelvisY_RotateL, 2)), 2);
    datasetUTPelvisZ_RotateL = cell2struct(num2cell(UTPelvisZ_RotateL, 1), compose('Subject%d', 1:size(UTPelvisZ_RotateL, 2)), 2);
    datasetUTULX_RotateL = cell2struct(num2cell(UTULX_RotateL, 1), compose('Subject%d', 1:size(UTULX_RotateL, 2)), 2);
    datasetUTULY_RotateL = cell2struct(num2cell(UTULY_RotateL, 1), compose('Subject%d', 1:size(UTULY_RotateL, 2)), 2);
    datasetUTULZ_RotateL = cell2struct(num2cell(UTULZ_RotateL, 1), compose('Subject%d', 1:size(UTULZ_RotateL, 2)), 2);
    
    save datasetLLLABX_RotateL;
    save datasetLLLABY_RotateL;
    save datasetLLLABZ_RotateL;
    save datasetLLPelvisX_RotateL;
    save datasetLLPelvisY_RotateL;
    save datasetLLPelvisZ_RotateL;
    save datasetLTLABX_RotateL;
    save datasetLTLABY_RotateL;
    save datasetLTLABZ_RotateL;
    save datasetLTLLX_RotateL;
    save datasetLTLLY_RotateL;
    save datasetLTLLZ_RotateL;
    save datasetLTPelvisX_RotateL;
    save datasetLTPelvisY_RotateL;
    save datasetLTPelvisZ_RotateL;
    save datasetLTULX_RotateL;
    save datasetLTULY_RotateL;    
    save datasetLTULZ_RotateL;
    save datasetPelvisLABX_RotateL;
    save datasetPelvisLABY_RotateL;
    save datasetPelvisLABZ_RotateL;
    save datasetTrunk2LABX_RotateL;    
    save datasetTrunk2LABY_RotateL;
    save datasetTrunk2LABZ_RotateL;
    save datasetTrunk2LABVelX_RotateL;
    save datasetTrunk2LABVelY_RotateL;
    save datasetTrunk2LABVelZ_RotateL;
    save datasetULLABX_RotateL;
    save datasetULLABY_RotateL;
    save datasetULLABZ_RotateL;
    save datasetULLLX_RotateL;
    save datasetULLLY_RotateL;
    save datasetULLLZ_RotateL;
    save datasetULPelvisX_RotateL;
    save datasetULPelvisY_RotateL;
    save datasetULPelvisZ_RotateL;
    save datasetUTLABX_RotateL;
    save datasetUTLABY_RotateL;
    save datasetUTLABZ_RotateL;
    save datasetUTLLX_RotateL;
    save datasetUTLLY_RotateL;
    save datasetUTLLZ_RotateL;
    save datasetUTLTX_RotateL;
    save datasetUTLTY_RotateL;
    save datasetUTLTZ_RotateL;
    save datasetUTPelvisX_RotateL;
    save datasetUTPelvisY_RotateL;
    save datasetUTPelvisZ_RotateL;
    save datasetUTULX_RotateL;
    save datasetUTULY_RotateL;
    save datasetUTULZ_RotateL;

end