function statTestRotationCombined
    
    %UTUL
    
    %RotateRightF
    data = load('datasetUTULX_RotateR.mat','datasetUTULX_RotateR');
    [YP,YNP] = deal([data.datasetUTULX_RotateR.Subject4 data.datasetUTULX_RotateR.Subject7 ...
        data.datasetUTULX_RotateR.Subject8 data.datasetUTULX_RotateR.Subject9 ...
        data.datasetUTULX_RotateR.Subject10 data.datasetUTULX_RotateR.Subject11 ...
        data.datasetUTULX_RotateR.Subject18 data.datasetUTULX_RotateR.Subject19 ...
        data.datasetUTULX_RotateR.Subject20 data.datasetUTULX_RotateR.Subject21 ...
        data.datasetUTULX_RotateR.Subject24 data.datasetUTULX_RotateR.Subject25 ...
        data.datasetUTULX_RotateR.Subject28 data.datasetUTULX_RotateR.Subject30 ...
        data.datasetUTULX_RotateR.Subject32 data.datasetUTULX_RotateR.Subject34 ...
        data.datasetUTULX_RotateR.Subject35 data.datasetUTULX_RotateR.Subject36 ...
        data.datasetUTULX_RotateR.Subject37 data.datasetUTULX_RotateR.Subject39 ...
        data.datasetUTULX_RotateR.Subject42 data.datasetUTULX_RotateR.Subject43 ...
        data.datasetUTULX_RotateR.Subject44 data.datasetUTULX_RotateR.Subject46 ...
        data.datasetUTULX_RotateR.Subject47 data.datasetUTULX_RotateR.Subject48 ...
        data.datasetUTULX_RotateR.Subject50 ], ...
        [data.datasetUTULX_RotateR.Subject2 data.datasetUTULX_RotateR.Subject3 ...
        data.datasetUTULX_RotateR.Subject6 data.datasetUTULX_RotateR.Subject12 ...
        data.datasetUTULX_RotateR.Subject15 data.datasetUTULX_RotateR.Subject16 ...
        data.datasetUTULX_RotateR.Subject22 data.datasetUTULX_RotateR.Subject23 ...
        data.datasetUTULX_RotateR.Subject26 data.datasetUTULX_RotateR.Subject31 ...
        data.datasetUTULX_RotateR.Subject33 data.datasetUTULX_RotateR.Subject38 ...
        data.datasetUTULX_RotateR.Subject40 data.datasetUTULX_RotateR.Subject41 ...
        data.datasetUTULX_RotateR.Subject45 data.datasetUTULX_RotateR.Subject51 ...
        data.datasetUTULX_RotateR.Subject52 data.datasetUTULX_RotateR.Subject55 ...
        data.datasetUTULX_RotateR.Subject56 data.datasetUTULX_RotateR.Subject57 ...
        data.datasetUTULX_RotateR.Subject58 ]);
    spm       = spm1d.stats.ttest2(YP', YNP');
    spmi      = spm.inference(0.05, 'two_tailed', true, 'interp',true);
    disp(spmi);
    close all
    subplot(1,2,1);
    spmi.plot();
    title('Two-Sample T-Test');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Variance','FontSize',12,'FontWeight','bold');
    spmi.plot_threshold_label();
    spmi.plot_p_values();  
    subplot(1,2,2);
    YPmean = mean (YP');
    YPstd = std (YP');
    numYPPts = length (YPmean);
    YNPmean = mean (YNP');
    YNPstd = std (YNP');
    numYNPPts = length (YNPmean);
    p1 = plot (1:numYPPts, YPmean, 'b','LineWidth',2);
    hold on
	plot (1:numYPPts, YPmean + YPstd, 'b--');
	plot (1:numYPPts, YPmean - YPstd, 'b--');
    p2 = plot (1:numYNPPts, YNPmean, 'r','LineWidth',2);
	plot (1:numYNPPts, YNPmean + YNPstd, 'r--');
    plot (1:numYNPPts, YNPmean - YNPstd, 'r--');
    xlim ([1 numYPPts]);
    legend([p1 p2],'Pain','No Pain', 'Location','northwest')
    title('Mean and SD');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Angle','FontSize',12,'FontWeight','bold');    
    savefig('UTULX_RotateR_Females');
    saveas(gcf,'UTULX_RotateR_Females.png');
    
    %RotateLeftF
    data = load('datasetUTULX_RotateL.mat','datasetUTULX_RotateL');
    [YP,YNP] = deal([data.datasetUTULX_RotateL.Subject4 data.datasetUTULX_RotateL.Subject7 ...
        data.datasetUTULX_RotateL.Subject8 data.datasetUTULX_RotateL.Subject9 ...
        data.datasetUTULX_RotateL.Subject10 data.datasetUTULX_RotateL.Subject11 ...
        data.datasetUTULX_RotateL.Subject18 data.datasetUTULX_RotateL.Subject19 ...
        data.datasetUTULX_RotateL.Subject20 data.datasetUTULX_RotateL.Subject21 ...
        data.datasetUTULX_RotateL.Subject24 data.datasetUTULX_RotateL.Subject25 ...
        data.datasetUTULX_RotateL.Subject28 data.datasetUTULX_RotateL.Subject30 ...
        data.datasetUTULX_RotateL.Subject32 data.datasetUTULX_RotateL.Subject34 ...
        data.datasetUTULX_RotateL.Subject35 data.datasetUTULX_RotateL.Subject36 ...
        data.datasetUTULX_RotateL.Subject37 data.datasetUTULX_RotateL.Subject39 ...
        data.datasetUTULX_RotateL.Subject42 data.datasetUTULX_RotateL.Subject43 ...
        data.datasetUTULX_RotateL.Subject44 data.datasetUTULX_RotateL.Subject46 ...
        data.datasetUTULX_RotateL.Subject47 data.datasetUTULX_RotateL.Subject48 ...
        data.datasetUTULX_RotateL.Subject50 ], ...
        [data.datasetUTULX_RotateL.Subject2 data.datasetUTULX_RotateL.Subject3 ...
        data.datasetUTULX_RotateL.Subject6 data.datasetUTULX_RotateL.Subject12 ...
        data.datasetUTULX_RotateL.Subject15 data.datasetUTULX_RotateL.Subject16 ...
        data.datasetUTULX_RotateL.Subject22 data.datasetUTULX_RotateL.Subject23 ...
        data.datasetUTULX_RotateL.Subject26 data.datasetUTULX_RotateL.Subject31 ...
        data.datasetUTULX_RotateL.Subject33 data.datasetUTULX_RotateL.Subject38 ...
        data.datasetUTULX_RotateL.Subject40 data.datasetUTULX_RotateL.Subject41 ...
        data.datasetUTULX_RotateL.Subject45 data.datasetUTULX_RotateL.Subject51 ...
        data.datasetUTULX_RotateL.Subject52 data.datasetUTULX_RotateL.Subject55 ...
        data.datasetUTULX_RotateL.Subject56 data.datasetUTULX_RotateL.Subject57 ...
        data.datasetUTULX_RotateL.Subject58 ]);
    spm       = spm1d.stats.ttest2(YP', YNP');
    spmi      = spm.inference(0.05, 'two_tailed', true, 'interp',true);
    disp(spmi);
    close all
    subplot(1,2,1);
    spmi.plot();
    title('Two-Sample T-Test');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Variance','FontSize',12,'FontWeight','bold');
    spmi.plot_threshold_label();
    spmi.plot_p_values();   
    subplot(1,2,2);
    YPmean = mean (YP');
    YPstd = std (YP');
    numYPPts = length (YPmean);
    YNPmean = mean (YNP');
    YNPstd = std (YNP');
    numYNPPts = length (YNPmean);
    p1 = plot (1:numYPPts, YPmean, 'b','LineWidth',2);
    hold on
	plot (1:numYPPts, YPmean + YPstd, 'b--');
	plot (1:numYPPts, YPmean - YPstd, 'b--');
    p2 = plot (1:numYNPPts, YNPmean, 'r','LineWidth',2);
	plot (1:numYNPPts, YNPmean + YNPstd, 'r--');
    plot (1:numYNPPts, YNPmean - YNPstd, 'r--');
    xlim ([1 numYPPts]);
    legend([p1 p2],'Pain','No Pain', 'Location','northwest')
    title('Mean and SD');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Angle','FontSize',12,'FontWeight','bold');   
    savefig('UTULX_RotateL_Females');
    saveas(gcf,'UTULX_RotateL_Females.png');

    %SitRotateLeftF
    data = load('datasetUTULX_SitRotateL.mat','datasetUTULX_SitRotateL');
    [YP,YNP] = deal([data.datasetUTULX_SitRotateL.Subject4 data.datasetUTULX_SitRotateL.Subject6 ...
        data.datasetUTULX_SitRotateL.Subject7 data.datasetUTULX_SitRotateL.Subject8 ...
        data.datasetUTULX_SitRotateL.Subject9 data.datasetUTULX_SitRotateL.Subject10 ...
        data.datasetUTULX_SitRotateL.Subject16 data.datasetUTULX_SitRotateL.Subject17 ...
        data.datasetUTULX_SitRotateL.Subject18 data.datasetUTULX_SitRotateL.Subject19 ...
        data.datasetUTULX_SitRotateL.Subject22 data.datasetUTULX_SitRotateL.Subject23 ...
        data.datasetUTULX_SitRotateL.Subject26 data.datasetUTULX_SitRotateL.Subject28 ...
        data.datasetUTULX_SitRotateL.Subject30 data.datasetUTULX_SitRotateL.Subject32 ...
        data.datasetUTULX_SitRotateL.Subject33 data.datasetUTULX_SitRotateL.Subject34 ...
        data.datasetUTULX_SitRotateL.Subject35 data.datasetUTULX_SitRotateL.Subject37 ...
        data.datasetUTULX_SitRotateL.Subject40 data.datasetUTULX_SitRotateL.Subject41 ...
        data.datasetUTULX_SitRotateL.Subject42 data.datasetUTULX_SitRotateL.Subject44 ...
        data.datasetUTULX_SitRotateL.Subject45 data.datasetUTULX_SitRotateL.Subject46 ...
        data.datasetUTULX_SitRotateL.Subject48 ], ...
        [data.datasetUTULX_SitRotateL.Subject2 data.datasetUTULX_SitRotateL.Subject3 ...
        data.datasetUTULX_SitRotateL.Subject5 data.datasetUTULX_SitRotateL.Subject11 ...
        data.datasetUTULX_SitRotateL.Subject14 ...
        data.datasetUTULX_SitRotateL.Subject20 data.datasetUTULX_SitRotateL.Subject21 ...
        data.datasetUTULX_SitRotateL.Subject24 data.datasetUTULX_SitRotateL.Subject29 ...
        data.datasetUTULX_SitRotateL.Subject31 data.datasetUTULX_SitRotateL.Subject36 ...
        data.datasetUTULX_SitRotateL.Subject38 data.datasetUTULX_SitRotateL.Subject39 ...
        data.datasetUTULX_SitRotateL.Subject43 data.datasetUTULX_SitRotateL.Subject49 ...
        data.datasetUTULX_SitRotateL.Subject50 data.datasetUTULX_SitRotateL.Subject53 ...
        data.datasetUTULX_SitRotateL.Subject54 data.datasetUTULX_SitRotateL.Subject55 ...
        data.datasetUTULX_SitRotateL.Subject56 ]);
    spm       = spm1d.stats.ttest2(YP', YNP');
    spmi      = spm.inference(0.05, 'two_tailed', true, 'interp',true);
    disp(spmi);
    close all
    subplot(1,2,1);
    spmi.plot();
    title('Two-Sample T-Test');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Variance','FontSize',12,'FontWeight','bold');
    spmi.plot_threshold_label();
    spmi.plot_p_values();    
    subplot(1,2,2);
    YPmean = mean (YP');
    YPstd = std (YP');
    numYPPts = length (YPmean);
    YNPmean = mean (YNP');
    YNPstd = std (YNP');
    numYNPPts = length (YNPmean);
    p1 = plot (1:numYPPts, YPmean, 'b','LineWidth',2);
    hold on
	plot (1:numYPPts, YPmean + YPstd, 'b--');
	plot (1:numYPPts, YPmean - YPstd, 'b--');
    p2 = plot (1:numYNPPts, YNPmean, 'r','LineWidth',2);
	plot (1:numYNPPts, YNPmean + YNPstd, 'r--');
    plot (1:numYNPPts, YNPmean - YNPstd, 'r--');
    xlim ([1 numYPPts]);
    legend([p1 p2],'Pain','No Pain', 'Location','northwest')
    title('Mean and SD');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Angle','FontSize',12,'FontWeight','bold');    
    savefig('UTULX_SitRotateL_Females');
    saveas(gcf,'UTULX_SitRotateL_Females.png');
    
    %SitRotateRightF
    data = load('datasetUTULX_SitRotateR.mat','datasetUTULX_SitRotateR');
    [YP,YNP] = deal([data.datasetUTULX_SitRotateR.Subject4 data.datasetUTULX_SitRotateR.Subject6 ...
        data.datasetUTULX_SitRotateR.Subject7 data.datasetUTULX_SitRotateR.Subject8 ...
        data.datasetUTULX_SitRotateR.Subject9 data.datasetUTULX_SitRotateR.Subject10 ...
        data.datasetUTULX_SitRotateR.Subject16 ...
        data.datasetUTULX_SitRotateR.Subject17 data.datasetUTULX_SitRotateR.Subject18 ...
        data.datasetUTULX_SitRotateR.Subject21 data.datasetUTULX_SitRotateR.Subject22 ...
        data.datasetUTULX_SitRotateR.Subject25 data.datasetUTULX_SitRotateR.Subject27 ...
        data.datasetUTULX_SitRotateR.Subject29 data.datasetUTULX_SitRotateR.Subject31 ...
        data.datasetUTULX_SitRotateR.Subject32 data.datasetUTULX_SitRotateR.Subject33 ...
        data.datasetUTULX_SitRotateR.Subject34 data.datasetUTULX_SitRotateR.Subject36 ...
        data.datasetUTULX_SitRotateR.Subject39 ...
        data.datasetUTULX_SitRotateR.Subject40 data.datasetUTULX_SitRotateR.Subject42 ...
        data.datasetUTULX_SitRotateR.Subject43 data.datasetUTULX_SitRotateR.Subject44 ...
        data.datasetUTULX_SitRotateR.Subject46 ], ...
        [data.datasetUTULX_SitRotateR.Subject2 data.datasetUTULX_SitRotateR.Subject3 ...
        data.datasetUTULX_SitRotateR.Subject5 data.datasetUTULX_SitRotateR.Subject11 ...
        data.datasetUTULX_SitRotateR.Subject14 ...
        data.datasetUTULX_SitRotateR.Subject19 data.datasetUTULX_SitRotateR.Subject20 ...
        data.datasetUTULX_SitRotateR.Subject23 data.datasetUTULX_SitRotateR.Subject28 ...
        data.datasetUTULX_SitRotateR.Subject30 data.datasetUTULX_SitRotateR.Subject35 ...
        data.datasetUTULX_SitRotateR.Subject37 data.datasetUTULX_SitRotateR.Subject38 ...
        data.datasetUTULX_SitRotateR.Subject41 data.datasetUTULX_SitRotateR.Subject47 ...
        data.datasetUTULX_SitRotateR.Subject48 data.datasetUTULX_SitRotateR.Subject51 ...
        data.datasetUTULX_SitRotateR.Subject52 data.datasetUTULX_SitRotateR.Subject53 ...
        data.datasetUTULX_SitRotateR.Subject54 ]);
    spm       = spm1d.stats.ttest2(YP', YNP');
    spmi      = spm.inference(0.05, 'two_tailed', true, 'interp',true);
    disp(spmi);
    close all
    subplot(1,2,1);
    spmi.plot();
    title('Two-Sample T-Test');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Variance','FontSize',12,'FontWeight','bold');
    spmi.plot_threshold_label();
    spmi.plot_p_values();
    subplot(1,2,2);
    YPmean = mean (YP');
    YPstd = std (YP');
    numYPPts = length (YPmean);
    YNPmean = mean (YNP');
    YNPstd = std (YNP');
    numYNPPts = length (YNPmean);
    p1 = plot (1:numYPPts, YPmean, 'b','LineWidth',2);
    hold on
    plot (1:numYPPts, YPmean + YPstd, 'b--');
    plot (1:numYPPts, YPmean - YPstd, 'b--');
    p2 = plot (1:numYNPPts, YNPmean, 'r','LineWidth',2);
    plot (1:numYNPPts, YNPmean + YNPstd, 'r--');
    plot (1:numYNPPts, YNPmean - YNPstd, 'r--');
    xlim ([1 numYPPts]);
    legend([p1 p2],'Pain','No Pain', 'Location','northwest')
    title('Mean and SD');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Angle','FontSize',12,'FontWeight','bold');
    savefig('UTULX_SitRotateR_Females');
    saveas(gcf,'UTULX_SitRotateR_Females.png');
    
    %RotateRightAll
    data = load('datasetUTULX_RotateR.mat','datasetUTULX_RotateR');
    [YP,YNP] = deal([data.datasetUTULX_RotateR.Subject1 ...
        data.datasetUTULX_RotateR.Subject4 data.datasetUTULX_RotateR.Subject5 ...
        data.datasetUTULX_RotateR.Subject7 ...
        data.datasetUTULX_RotateR.Subject8 data.datasetUTULX_RotateR.Subject9 ...
        data.datasetUTULX_RotateR.Subject10 data.datasetUTULX_RotateR.Subject11 ...
        data.datasetUTULX_RotateR.Subject13 data.datasetUTULX_RotateR.Subject14 ...
        data.datasetUTULX_RotateR.Subject17 ...
        data.datasetUTULX_RotateR.Subject18 data.datasetUTULX_RotateR.Subject19 ...
        data.datasetUTULX_RotateR.Subject20 data.datasetUTULX_RotateR.Subject21 ...
        data.datasetUTULX_RotateR.Subject24 data.datasetUTULX_RotateR.Subject25 ...
        data.datasetUTULX_RotateR.Subject27 ...
        data.datasetUTULX_RotateR.Subject28 data.datasetUTULX_RotateR.Subject29 ...
        data.datasetUTULX_RotateR.Subject30 ...
        data.datasetUTULX_RotateR.Subject32 data.datasetUTULX_RotateR.Subject34 ...
        data.datasetUTULX_RotateR.Subject35 data.datasetUTULX_RotateR.Subject36 ...
        data.datasetUTULX_RotateR.Subject37 data.datasetUTULX_RotateR.Subject39 ...
        data.datasetUTULX_RotateR.Subject42 data.datasetUTULX_RotateR.Subject43 ...
        data.datasetUTULX_RotateR.Subject44 data.datasetUTULX_RotateR.Subject46 ...
        data.datasetUTULX_RotateR.Subject47 data.datasetUTULX_RotateR.Subject48 ...
        data.datasetUTULX_RotateR.Subject49 ...
        data.datasetUTULX_RotateR.Subject50 data.datasetUTULX_RotateR.Subject54], ...
        [data.datasetUTULX_RotateR.Subject2 data.datasetUTULX_RotateR.Subject3 ...
        data.datasetUTULX_RotateR.Subject6 data.datasetUTULX_RotateR.Subject12 ...
        data.datasetUTULX_RotateR.Subject15 data.datasetUTULX_RotateR.Subject16 ...
        data.datasetUTULX_RotateR.Subject22 data.datasetUTULX_RotateR.Subject23 ...
        data.datasetUTULX_RotateR.Subject26 data.datasetUTULX_RotateR.Subject31 ...
        data.datasetUTULX_RotateR.Subject33 data.datasetUTULX_RotateR.Subject38 ...
        data.datasetUTULX_RotateR.Subject40 data.datasetUTULX_RotateR.Subject41 ...
        data.datasetUTULX_RotateR.Subject45 data.datasetUTULX_RotateR.Subject51 ...
        data.datasetUTULX_RotateR.Subject52 data.datasetUTULX_RotateR.Subject53 ...
        data.datasetUTULX_RotateR.Subject55 ...
        data.datasetUTULX_RotateR.Subject56 data.datasetUTULX_RotateR.Subject57 ...
        data.datasetUTULX_RotateR.Subject58 data.datasetUTULX_RotateR.Subject59 ...
        data.datasetUTULX_RotateR.Subject60 ]);
    spm       = spm1d.stats.ttest2(YP', YNP');
    spmi      = spm.inference(0.05, 'two_tailed', true, 'interp',true);
    disp(spmi);
    close all
    subplot(1,2,1);
    spmi.plot();
    title('Two-Sample T-Test');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Variance','FontSize',12,'FontWeight','bold');
    spmi.plot_threshold_label();
    spmi.plot_p_values();    
    subplot(1,2,2);
    YPmean = mean (YP');
    YPstd = std (YP');
    numYPPts = length (YPmean);
    YNPmean = mean (YNP');
    YNPstd = std (YNP');
    numYNPPts = length (YNPmean);
    p1 = plot (1:numYPPts, YPmean, 'b','LineWidth',2);
    hold on
	plot (1:numYPPts, YPmean + YPstd, 'b--');
	plot (1:numYPPts, YPmean - YPstd, 'b--');
    p2 = plot (1:numYNPPts, YNPmean, 'r','LineWidth',2);
	plot (1:numYNPPts, YNPmean + YNPstd, 'r--');
    plot (1:numYNPPts, YNPmean - YNPstd, 'r--');
    xlim ([1 numYPPts]);
    legend([p1 p2],'Pain','No Pain', 'Location','northwest')
    title('Mean and SD');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Angle','FontSize',12,'FontWeight','bold');   
    savefig('UTULX_RotateR_AllSubjects');
    saveas(gcf,'UTULX_RotateR_AllSubjects.png');
    
    %RotateLeftAll
    data = load('datasetUTULX_RotateL.mat','datasetUTULX_RotateL');
    [YP,YNP] = deal([data.datasetUTULX_RotateL.Subject1 ...
        data.datasetUTULX_RotateL.Subject4 data.datasetUTULX_RotateL.Subject5 ...
        data.datasetUTULX_RotateL.Subject7 ...
        data.datasetUTULX_RotateL.Subject8 data.datasetUTULX_RotateL.Subject9 ...
        data.datasetUTULX_RotateL.Subject10 data.datasetUTULX_RotateL.Subject11 ...
        data.datasetUTULX_RotateL.Subject13 data.datasetUTULX_RotateL.Subject14 ...
        data.datasetUTULX_RotateL.Subject17 ...
        data.datasetUTULX_RotateL.Subject18 data.datasetUTULX_RotateL.Subject19 ...
        data.datasetUTULX_RotateL.Subject20 data.datasetUTULX_RotateL.Subject21 ...
        data.datasetUTULX_RotateL.Subject24 data.datasetUTULX_RotateL.Subject25 ...
        data.datasetUTULX_RotateL.Subject27 ...
        data.datasetUTULX_RotateL.Subject28 data.datasetUTULX_RotateL.Subject29 ...
        data.datasetUTULX_RotateL.Subject30 ...
        data.datasetUTULX_RotateL.Subject32 data.datasetUTULX_RotateL.Subject34 ...
        data.datasetUTULX_RotateL.Subject35 data.datasetUTULX_RotateL.Subject36 ...
        data.datasetUTULX_RotateL.Subject37 data.datasetUTULX_RotateL.Subject39 ...
        data.datasetUTULX_RotateL.Subject42 data.datasetUTULX_RotateL.Subject43 ...
        data.datasetUTULX_RotateL.Subject44 data.datasetUTULX_RotateL.Subject46 ...
        data.datasetUTULX_RotateL.Subject47 data.datasetUTULX_RotateL.Subject48 ...
        data.datasetUTULX_RotateL.Subject49 ...
        data.datasetUTULX_RotateL.Subject50 data.datasetUTULX_RotateL.Subject54], ...
        [data.datasetUTULX_RotateL.Subject2 data.datasetUTULX_RotateL.Subject3 ...
        data.datasetUTULX_RotateL.Subject6 data.datasetUTULX_RotateL.Subject12 ...
        data.datasetUTULX_RotateL.Subject15 data.datasetUTULX_RotateL.Subject16 ...
        data.datasetUTULX_RotateL.Subject22 data.datasetUTULX_RotateL.Subject23 ...
        data.datasetUTULX_RotateL.Subject26 data.datasetUTULX_RotateL.Subject31 ...
        data.datasetUTULX_RotateL.Subject33 data.datasetUTULX_RotateL.Subject38 ...
        data.datasetUTULX_RotateL.Subject40 data.datasetUTULX_RotateL.Subject41 ...
        data.datasetUTULX_RotateL.Subject45 data.datasetUTULX_RotateL.Subject51 ...
        data.datasetUTULX_RotateL.Subject52 data.datasetUTULX_RotateL.Subject53 ...
        data.datasetUTULX_RotateL.Subject55 ...
        data.datasetUTULX_RotateL.Subject56 data.datasetUTULX_RotateL.Subject57 ...
        data.datasetUTULX_RotateL.Subject58 data.datasetUTULX_RotateL.Subject59 ...
        data.datasetUTULX_RotateL.Subject60 ]);
    spm       = spm1d.stats.ttest2(YP', YNP');
    spmi      = spm.inference(0.05, 'two_tailed', true, 'interp',true);
    disp(spmi);
    close all
    subplot(1,2,1);
    spmi.plot();
    title('Two-Sample T-Test');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Variance','FontSize',12,'FontWeight','bold');
    spmi.plot_threshold_label();
    spmi.plot_p_values();    
    subplot(1,2,2);
    YPmean = mean (YP');
    YPstd = std (YP');
    numYPPts = length (YPmean);
    YNPmean = mean (YNP');
    YNPstd = std (YNP');
    numYNPPts = length (YNPmean);
    p1 = plot (1:numYPPts, YPmean, 'b','LineWidth',2);
    hold on
	plot (1:numYPPts, YPmean + YPstd, 'b--');
	plot (1:numYPPts, YPmean - YPstd, 'b--');
    p2 = plot (1:numYNPPts, YNPmean, 'r','LineWidth',2);
	plot (1:numYNPPts, YNPmean + YNPstd, 'r--');
    plot (1:numYNPPts, YNPmean - YNPstd, 'r--');
    xlim ([1 numYPPts]);
    legend([p1 p2],'Pain','No Pain', 'Location','northwest')
    title('Mean and SD');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Angle','FontSize',12,'FontWeight','bold');    
    savefig('UTULX_RotateL_AllSubjects');
    saveas(gcf,'UTULX_RotateL_AllSubjects.png');
    
    %SitRotateLeftAll
    data = load('datasetUTULX_SitRotateL.mat','datasetUTULX_SitRotateL');
    [YP,YNP] = deal([data.datasetUTULX_SitRotateL.Subject1 ...
        data.datasetUTULX_SitRotateL.Subject4 data.datasetUTULX_SitRotateL.Subject6 ...
        data.datasetUTULX_SitRotateL.Subject7 data.datasetUTULX_SitRotateL.Subject8 ...
        data.datasetUTULX_SitRotateL.Subject9 data.datasetUTULX_SitRotateL.Subject10 ...
        data.datasetUTULX_SitRotateL.Subject11 data.datasetUTULX_SitRotateL.Subject13 ...
        data.datasetUTULX_SitRotateL.Subject15 ...
        data.datasetUTULX_SitRotateL.Subject16 data.datasetUTULX_SitRotateL.Subject17 ...
        data.datasetUTULX_SitRotateL.Subject18 data.datasetUTULX_SitRotateL.Subject19 ...
        data.datasetUTULX_SitRotateL.Subject22 data.datasetUTULX_SitRotateL.Subject23 ...
        data.datasetUTULX_SitRotateL.Subject25 ...
        data.datasetUTULX_SitRotateL.Subject26 data.datasetUTULX_SitRotateL.Subject27 ...
        data.datasetUTULX_SitRotateL.Subject28 ...
        data.datasetUTULX_SitRotateL.Subject30 data.datasetUTULX_SitRotateL.Subject32 ...
        data.datasetUTULX_SitRotateL.Subject33 data.datasetUTULX_SitRotateL.Subject34 ...
        data.datasetUTULX_SitRotateL.Subject35 data.datasetUTULX_SitRotateL.Subject37 ...
        data.datasetUTULX_SitRotateL.Subject40 data.datasetUTULX_SitRotateL.Subject41 ...
        data.datasetUTULX_SitRotateL.Subject42 data.datasetUTULX_SitRotateL.Subject44 ...
        data.datasetUTULX_SitRotateL.Subject45 data.datasetUTULX_SitRotateL.Subject46 ...
        data.datasetUTULX_SitRotateL.Subject47 ...
        data.datasetUTULX_SitRotateL.Subject48 data.datasetUTULX_SitRotateL.Subject52 ], ...
        [data.datasetUTULX_SitRotateL.Subject2 data.datasetUTULX_SitRotateL.Subject3 ...
        data.datasetUTULX_SitRotateL.Subject5 data.datasetUTULX_SitRotateL.Subject11 ...
        data.datasetUTULX_SitRotateL.Subject14 ...
        data.datasetUTULX_SitRotateL.Subject20 data.datasetUTULX_SitRotateL.Subject21 ...
        data.datasetUTULX_SitRotateL.Subject24 data.datasetUTULX_SitRotateL.Subject29 ...
        data.datasetUTULX_SitRotateL.Subject31 data.datasetUTULX_SitRotateL.Subject36 ...
        data.datasetUTULX_SitRotateL.Subject38 data.datasetUTULX_SitRotateL.Subject39 ...
        data.datasetUTULX_SitRotateL.Subject43 data.datasetUTULX_SitRotateL.Subject49 ...
        data.datasetUTULX_SitRotateL.Subject50 data.datasetUTULX_SitRotateL.Subject51 ...
        data.datasetUTULX_SitRotateL.Subject53 ...
        data.datasetUTULX_SitRotateL.Subject54 data.datasetUTULX_SitRotateL.Subject55 ...
        data.datasetUTULX_SitRotateL.Subject56 data.datasetUTULX_SitRotateL.Subject57 ...
        data.datasetUTULX_SitRotateL.Subject58 ]);
    spm       = spm1d.stats.ttest2(YP', YNP');
    spmi      = spm.inference(0.05, 'two_tailed', true, 'interp',true);
    disp(spmi);
    close all
    subplot(1,2,1);
    spmi.plot();
    title('Two-Sample T-Test');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Variance','FontSize',12,'FontWeight','bold');
    spmi.plot_threshold_label();
    spmi.plot_p_values();    
    subplot(1,2,2);
    YPmean = mean (YP');
    YPstd = std (YP');
    numYPPts = length (YPmean);
    YNPmean = mean (YNP');
    YNPstd = std (YNP');
    numYNPPts = length (YNPmean);
    p1 = plot (1:numYPPts, YPmean, 'b','LineWidth',2);
    hold on
	plot (1:numYPPts, YPmean + YPstd, 'b--');
	plot (1:numYPPts, YPmean - YPstd, 'b--');
    p2 = plot (1:numYNPPts, YNPmean, 'r','LineWidth',2);
	plot (1:numYNPPts, YNPmean + YNPstd, 'r--');
    plot (1:numYNPPts, YNPmean - YNPstd, 'r--');
    xlim ([1 numYPPts]);
    legend([p1 p2],'Pain','No Pain', 'Location','northwest')
    title('Mean and SD');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Angle','FontSize',12,'FontWeight','bold');    
    savefig('UTULX_SitRotateL_AllSubjects');
    saveas(gcf,'UTULX_SitRotateL_AllSubjects.png');
    
     %RotateRightF
    data = load('datasetUTULY_RotateR.mat','datasetUTULY_RotateR');
    [YP,YNP] = deal([data.datasetUTULY_RotateR.Subject4 data.datasetUTULY_RotateR.Subject7 ...
        data.datasetUTULY_RotateR.Subject8 data.datasetUTULY_RotateR.Subject9 ...
        data.datasetUTULY_RotateR.Subject10 data.datasetUTULY_RotateR.Subject11 ...
        data.datasetUTULY_RotateR.Subject18 data.datasetUTULY_RotateR.Subject19 ...
        data.datasetUTULY_RotateR.Subject20 data.datasetUTULY_RotateR.Subject21 ...
        data.datasetUTULY_RotateR.Subject24 data.datasetUTULY_RotateR.Subject25 ...
        data.datasetUTULY_RotateR.Subject28 data.datasetUTULY_RotateR.Subject30 ...
        data.datasetUTULY_RotateR.Subject32 data.datasetUTULY_RotateR.Subject34 ...
        data.datasetUTULY_RotateR.Subject35 data.datasetUTULY_RotateR.Subject36 ...
        data.datasetUTULY_RotateR.Subject37 data.datasetUTULY_RotateR.Subject39 ...
        data.datasetUTULY_RotateR.Subject42 data.datasetUTULY_RotateR.Subject43 ...
        data.datasetUTULY_RotateR.Subject44 data.datasetUTULY_RotateR.Subject46 ...
        data.datasetUTULY_RotateR.Subject47 data.datasetUTULY_RotateR.Subject48 ...
        data.datasetUTULY_RotateR.Subject50 ], ...
        [data.datasetUTULY_RotateR.Subject2 data.datasetUTULY_RotateR.Subject3 ...
        data.datasetUTULY_RotateR.Subject6 data.datasetUTULY_RotateR.Subject12 ...
        data.datasetUTULY_RotateR.Subject15 data.datasetUTULY_RotateR.Subject16 ...
        data.datasetUTULY_RotateR.Subject22 data.datasetUTULY_RotateR.Subject23 ...
        data.datasetUTULY_RotateR.Subject26 data.datasetUTULY_RotateR.Subject31 ...
        data.datasetUTULY_RotateR.Subject33 data.datasetUTULY_RotateR.Subject38 ...
        data.datasetUTULY_RotateR.Subject40 data.datasetUTULY_RotateR.Subject41 ...
        data.datasetUTULY_RotateR.Subject45 data.datasetUTULY_RotateR.Subject51 ...
        data.datasetUTULY_RotateR.Subject52 data.datasetUTULY_RotateR.Subject55 ...
        data.datasetUTULY_RotateR.Subject56 data.datasetUTULY_RotateR.Subject57 ...
        data.datasetUTULY_RotateR.Subject58 ]);
    spm       = spm1d.stats.ttest2(YP', YNP');
    spmi      = spm.inference(0.05, 'two_tailed', true, 'interp',true);
    disp(spmi);
    close all
    subplot(1,2,1);
    spmi.plot();
    title('Two-Sample T-Test');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Variance','FontSize',12,'FontWeight','bold');
    spmi.plot_threshold_label();
    spmi.plot_p_values();  
    subplot(1,2,2);
    YPmean = mean (YP');
    YPstd = std (YP');
    numYPPts = length (YPmean);
    YNPmean = mean (YNP');
    YNPstd = std (YNP');
    numYNPPts = length (YNPmean);
    p1 = plot (1:numYPPts, YPmean, 'b','LineWidth',2);
    hold on
	plot (1:numYPPts, YPmean + YPstd, 'b--');
	plot (1:numYPPts, YPmean - YPstd, 'b--');
    p2 = plot (1:numYNPPts, YNPmean, 'r','LineWidth',2);
	plot (1:numYNPPts, YNPmean + YNPstd, 'r--');
    plot (1:numYNPPts, YNPmean - YNPstd, 'r--');
    xlim ([1 numYPPts]);
    legend([p1 p2],'Pain','No Pain', 'Location','northwest')
    title('Mean and SD');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Angle','FontSize',12,'FontWeight','bold');    
    savefig('UTULY_RotateR_Females');
    saveas(gcf,'UTULY_RotateR_Females.png');
    
    %RotateLeftF
    data = load('datasetUTULY_RotateL.mat','datasetUTULY_RotateL');
    [YP,YNP] = deal([data.datasetUTULY_RotateL.Subject4 data.datasetUTULY_RotateL.Subject7 ...
        data.datasetUTULY_RotateL.Subject8 data.datasetUTULY_RotateL.Subject9 ...
        data.datasetUTULY_RotateL.Subject10 data.datasetUTULY_RotateL.Subject11 ...
        data.datasetUTULY_RotateL.Subject18 data.datasetUTULY_RotateL.Subject19 ...
        data.datasetUTULY_RotateL.Subject20 data.datasetUTULY_RotateL.Subject21 ...
        data.datasetUTULY_RotateL.Subject24 data.datasetUTULY_RotateL.Subject25 ...
        data.datasetUTULY_RotateL.Subject28 data.datasetUTULY_RotateL.Subject30 ...
        data.datasetUTULY_RotateL.Subject32 data.datasetUTULY_RotateL.Subject34 ...
        data.datasetUTULY_RotateL.Subject35 data.datasetUTULY_RotateL.Subject36 ...
        data.datasetUTULY_RotateL.Subject37 data.datasetUTULY_RotateL.Subject39 ...
        data.datasetUTULY_RotateL.Subject42 data.datasetUTULY_RotateL.Subject43 ...
        data.datasetUTULY_RotateL.Subject44 data.datasetUTULY_RotateL.Subject46 ...
        data.datasetUTULY_RotateL.Subject47 data.datasetUTULY_RotateL.Subject48 ...
        data.datasetUTULY_RotateL.Subject50 ], ...
        [data.datasetUTULY_RotateL.Subject2 data.datasetUTULY_RotateL.Subject3 ...
        data.datasetUTULY_RotateL.Subject6 data.datasetUTULY_RotateL.Subject12 ...
        data.datasetUTULY_RotateL.Subject15 data.datasetUTULY_RotateL.Subject16 ...
        data.datasetUTULY_RotateL.Subject22 data.datasetUTULY_RotateL.Subject23 ...
        data.datasetUTULY_RotateL.Subject26 data.datasetUTULY_RotateL.Subject31 ...
        data.datasetUTULY_RotateL.Subject33 data.datasetUTULY_RotateL.Subject38 ...
        data.datasetUTULY_RotateL.Subject40 data.datasetUTULY_RotateL.Subject41 ...
        data.datasetUTULY_RotateL.Subject45 data.datasetUTULY_RotateL.Subject51 ...
        data.datasetUTULY_RotateL.Subject52 data.datasetUTULY_RotateL.Subject55 ...
        data.datasetUTULY_RotateL.Subject56 data.datasetUTULY_RotateL.Subject57 ...
        data.datasetUTULY_RotateL.Subject58 ]);
    spm       = spm1d.stats.ttest2(YP', YNP');
    spmi      = spm.inference(0.05, 'two_tailed', true, 'interp',true);
    disp(spmi);
    close all
    subplot(1,2,1);
    spmi.plot();
    title('Two-Sample T-Test');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Variance','FontSize',12,'FontWeight','bold');
    spmi.plot_threshold_label();
    spmi.plot_p_values();   
    subplot(1,2,2);
    YPmean = mean (YP');
    YPstd = std (YP');
    numYPPts = length (YPmean);
    YNPmean = mean (YNP');
    YNPstd = std (YNP');
    numYNPPts = length (YNPmean);
    p1 = plot (1:numYPPts, YPmean, 'b','LineWidth',2);
    hold on
	plot (1:numYPPts, YPmean + YPstd, 'b--');
	plot (1:numYPPts, YPmean - YPstd, 'b--');
    p2 = plot (1:numYNPPts, YNPmean, 'r','LineWidth',2);
	plot (1:numYNPPts, YNPmean + YNPstd, 'r--');
    plot (1:numYNPPts, YNPmean - YNPstd, 'r--');
    xlim ([1 numYPPts]);
    legend([p1 p2],'Pain','No Pain', 'Location','northwest')
    title('Mean and SD');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Angle','FontSize',12,'FontWeight','bold');   
    savefig('UTULY_RotateL_Females');
    saveas(gcf,'UTULY_RotateL_Females.png');

    %SitRotateLeftF
    data = load('datasetUTULY_SitRotateL.mat','datasetUTULY_SitRotateL');
    [YP,YNP] = deal([data.datasetUTULY_SitRotateL.Subject4 data.datasetUTULY_SitRotateL.Subject6 ...
        data.datasetUTULY_SitRotateL.Subject7 data.datasetUTULY_SitRotateL.Subject8 ...
        data.datasetUTULY_SitRotateL.Subject9 data.datasetUTULY_SitRotateL.Subject10 ...
        data.datasetUTULY_SitRotateL.Subject16 data.datasetUTULY_SitRotateL.Subject17 ...
        data.datasetUTULY_SitRotateL.Subject18 data.datasetUTULY_SitRotateL.Subject19 ...
        data.datasetUTULY_SitRotateL.Subject22 data.datasetUTULY_SitRotateL.Subject23 ...
        data.datasetUTULY_SitRotateL.Subject26 data.datasetUTULY_SitRotateL.Subject28 ...
        data.datasetUTULY_SitRotateL.Subject30 data.datasetUTULY_SitRotateL.Subject32 ...
        data.datasetUTULY_SitRotateL.Subject33 data.datasetUTULY_SitRotateL.Subject34 ...
        data.datasetUTULY_SitRotateL.Subject35 data.datasetUTULY_SitRotateL.Subject37 ...
        data.datasetUTULY_SitRotateL.Subject40 data.datasetUTULY_SitRotateL.Subject41 ...
        data.datasetUTULY_SitRotateL.Subject42 data.datasetUTULY_SitRotateL.Subject44 ...
        data.datasetUTULY_SitRotateL.Subject45 data.datasetUTULY_SitRotateL.Subject46 ...
        data.datasetUTULY_SitRotateL.Subject48 ], ...
        [data.datasetUTULY_SitRotateL.Subject2 data.datasetUTULY_SitRotateL.Subject3 ...
        data.datasetUTULY_SitRotateL.Subject5 data.datasetUTULY_SitRotateL.Subject11 ...
        data.datasetUTULY_SitRotateL.Subject14 ...
        data.datasetUTULY_SitRotateL.Subject20 data.datasetUTULY_SitRotateL.Subject21 ...
        data.datasetUTULY_SitRotateL.Subject24 data.datasetUTULY_SitRotateL.Subject29 ...
        data.datasetUTULY_SitRotateL.Subject31 data.datasetUTULY_SitRotateL.Subject36 ...
        data.datasetUTULY_SitRotateL.Subject38 data.datasetUTULY_SitRotateL.Subject39 ...
        data.datasetUTULY_SitRotateL.Subject43 data.datasetUTULY_SitRotateL.Subject49 ...
        data.datasetUTULY_SitRotateL.Subject50 data.datasetUTULY_SitRotateL.Subject53 ...
        data.datasetUTULY_SitRotateL.Subject54 data.datasetUTULY_SitRotateL.Subject55 ...
        data.datasetUTULY_SitRotateL.Subject56 ]);
    spm       = spm1d.stats.ttest2(YP', YNP');
    spmi      = spm.inference(0.05, 'two_tailed', true, 'interp',true);
    disp(spmi);
    close all
    subplot(1,2,1);
    spmi.plot();
    title('Two-Sample T-Test');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Variance','FontSize',12,'FontWeight','bold');
    spmi.plot_threshold_label();
    spmi.plot_p_values();    
    subplot(1,2,2);
    YPmean = mean (YP');
    YPstd = std (YP');
    numYPPts = length (YPmean);
    YNPmean = mean (YNP');
    YNPstd = std (YNP');
    numYNPPts = length (YNPmean);
    p1 = plot (1:numYPPts, YPmean, 'b','LineWidth',2);
    hold on
	plot (1:numYPPts, YPmean + YPstd, 'b--');
	plot (1:numYPPts, YPmean - YPstd, 'b--');
    p2 = plot (1:numYNPPts, YNPmean, 'r','LineWidth',2);
	plot (1:numYNPPts, YNPmean + YNPstd, 'r--');
    plot (1:numYNPPts, YNPmean - YNPstd, 'r--');
    xlim ([1 numYPPts]);
    legend([p1 p2],'Pain','No Pain', 'Location','northwest')
    title('Mean and SD');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Angle','FontSize',12,'FontWeight','bold');    
    savefig('UTULY_SitRotateL_Females');
    saveas(gcf,'UTULY_SitRotateL_Females.png');
    
    %SitRotateRightF
    data = load('datasetUTULY_SitRotateR.mat','datasetUTULY_SitRotateR');
    [YP,YNP] = deal([data.datasetUTULY_SitRotateR.Subject4 data.datasetUTULY_SitRotateR.Subject6 ...
        data.datasetUTULY_SitRotateR.Subject7 data.datasetUTULY_SitRotateR.Subject8 ...
        data.datasetUTULY_SitRotateR.Subject9 data.datasetUTULY_SitRotateR.Subject10 ...
        data.datasetUTULY_SitRotateR.Subject16 ...
        data.datasetUTULY_SitRotateR.Subject17 data.datasetUTULY_SitRotateR.Subject18 ...
        data.datasetUTULY_SitRotateR.Subject21 data.datasetUTULY_SitRotateR.Subject22 ...
        data.datasetUTULY_SitRotateR.Subject25 data.datasetUTULY_SitRotateR.Subject27 ...
        data.datasetUTULY_SitRotateR.Subject29 data.datasetUTULY_SitRotateR.Subject31 ...
        data.datasetUTULY_SitRotateR.Subject32 data.datasetUTULY_SitRotateR.Subject33 ...
        data.datasetUTULY_SitRotateR.Subject34 data.datasetUTULY_SitRotateR.Subject36 ...
        data.datasetUTULY_SitRotateR.Subject39 ...
        data.datasetUTULY_SitRotateR.Subject40 data.datasetUTULY_SitRotateR.Subject42 ...
        data.datasetUTULY_SitRotateR.Subject43 data.datasetUTULY_SitRotateR.Subject44 ...
        data.datasetUTULY_SitRotateR.Subject46 ], ...
        [data.datasetUTULY_SitRotateR.Subject2 data.datasetUTULY_SitRotateR.Subject3 ...
        data.datasetUTULY_SitRotateR.Subject5 data.datasetUTULY_SitRotateR.Subject11 ...
        data.datasetUTULY_SitRotateR.Subject14 ...
        data.datasetUTULY_SitRotateR.Subject19 data.datasetUTULY_SitRotateR.Subject20 ...
        data.datasetUTULY_SitRotateR.Subject23 data.datasetUTULY_SitRotateR.Subject28 ...
        data.datasetUTULY_SitRotateR.Subject30 data.datasetUTULY_SitRotateR.Subject35 ...
        data.datasetUTULY_SitRotateR.Subject37 data.datasetUTULY_SitRotateR.Subject38 ...
        data.datasetUTULY_SitRotateR.Subject41 data.datasetUTULY_SitRotateR.Subject47 ...
        data.datasetUTULY_SitRotateR.Subject48 data.datasetUTULY_SitRotateR.Subject51 ...
        data.datasetUTULY_SitRotateR.Subject52 data.datasetUTULY_SitRotateR.Subject53 ...
        data.datasetUTULY_SitRotateR.Subject54 ]);
    spm       = spm1d.stats.ttest2(YP', YNP');
    spmi      = spm.inference(0.05, 'two_tailed', true, 'interp',true);
    disp(spmi);
    close all
    subplot(1,2,1);
    spmi.plot();
    title('Two-Sample T-Test');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Variance','FontSize',12,'FontWeight','bold');
    spmi.plot_threshold_label();
    spmi.plot_p_values();
    subplot(1,2,2);
    YPmean = mean (YP');
    YPstd = std (YP');
    numYPPts = length (YPmean);
    YNPmean = mean (YNP');
    YNPstd = std (YNP');
    numYNPPts = length (YNPmean);
    p1 = plot (1:numYPPts, YPmean, 'b','LineWidth',2);
    hold on
    plot (1:numYPPts, YPmean + YPstd, 'b--');
    plot (1:numYPPts, YPmean - YPstd, 'b--');
    p2 = plot (1:numYNPPts, YNPmean, 'r','LineWidth',2);
    plot (1:numYNPPts, YNPmean + YNPstd, 'r--');
    plot (1:numYNPPts, YNPmean - YNPstd, 'r--');
    xlim ([1 numYPPts]);
    legend([p1 p2],'Pain','No Pain', 'Location','northwest')
    title('Mean and SD');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Angle','FontSize',12,'FontWeight','bold');
    savefig('UTULY_SitRotateR_Females');
    saveas(gcf,'UTULY_SitRotateR_Females.png');
    
    %RotateRightAll
    data = load('datasetUTULY_RotateR.mat','datasetUTULY_RotateR');
    [YP,YNP] = deal([data.datasetUTULY_RotateR.Subject1 ...
        data.datasetUTULY_RotateR.Subject4 data.datasetUTULY_RotateR.Subject5 ...
        data.datasetUTULY_RotateR.Subject7 ...
        data.datasetUTULY_RotateR.Subject8 data.datasetUTULY_RotateR.Subject9 ...
        data.datasetUTULY_RotateR.Subject10 data.datasetUTULY_RotateR.Subject11 ...
        data.datasetUTULY_RotateR.Subject13 data.datasetUTULY_RotateR.Subject14 ...
        data.datasetUTULY_RotateR.Subject17 ...
        data.datasetUTULY_RotateR.Subject18 data.datasetUTULY_RotateR.Subject19 ...
        data.datasetUTULY_RotateR.Subject20 data.datasetUTULY_RotateR.Subject21 ...
        data.datasetUTULY_RotateR.Subject24 data.datasetUTULY_RotateR.Subject25 ...
        data.datasetUTULY_RotateR.Subject27 ...
        data.datasetUTULY_RotateR.Subject28 data.datasetUTULY_RotateR.Subject29 ...
        data.datasetUTULY_RotateR.Subject30 ...
        data.datasetUTULY_RotateR.Subject32 data.datasetUTULY_RotateR.Subject34 ...
        data.datasetUTULY_RotateR.Subject35 data.datasetUTULY_RotateR.Subject36 ...
        data.datasetUTULY_RotateR.Subject37 data.datasetUTULY_RotateR.Subject39 ...
        data.datasetUTULY_RotateR.Subject42 data.datasetUTULY_RotateR.Subject43 ...
        data.datasetUTULY_RotateR.Subject44 data.datasetUTULY_RotateR.Subject46 ...
        data.datasetUTULY_RotateR.Subject47 data.datasetUTULY_RotateR.Subject48 ...
        data.datasetUTULY_RotateR.Subject49 ...
        data.datasetUTULY_RotateR.Subject50 data.datasetUTULY_RotateR.Subject54], ...
        [data.datasetUTULY_RotateR.Subject2 data.datasetUTULY_RotateR.Subject3 ...
        data.datasetUTULY_RotateR.Subject6 data.datasetUTULY_RotateR.Subject12 ...
        data.datasetUTULY_RotateR.Subject15 data.datasetUTULY_RotateR.Subject16 ...
        data.datasetUTULY_RotateR.Subject22 data.datasetUTULY_RotateR.Subject23 ...
        data.datasetUTULY_RotateR.Subject26 data.datasetUTULY_RotateR.Subject31 ...
        data.datasetUTULY_RotateR.Subject33 data.datasetUTULY_RotateR.Subject38 ...
        data.datasetUTULY_RotateR.Subject40 data.datasetUTULY_RotateR.Subject41 ...
        data.datasetUTULY_RotateR.Subject45 data.datasetUTULY_RotateR.Subject51 ...
        data.datasetUTULY_RotateR.Subject52 data.datasetUTULY_RotateR.Subject53 ...
        data.datasetUTULY_RotateR.Subject55 ...
        data.datasetUTULY_RotateR.Subject56 data.datasetUTULY_RotateR.Subject57 ...
        data.datasetUTULY_RotateR.Subject58 data.datasetUTULY_RotateR.Subject59 ...
        data.datasetUTULY_RotateR.Subject60 ]);
    spm       = spm1d.stats.ttest2(YP', YNP');
    spmi      = spm.inference(0.05, 'two_tailed', true, 'interp',true);
    disp(spmi);
    close all
    subplot(1,2,1);
    spmi.plot();
    title('Two-Sample T-Test');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Variance','FontSize',12,'FontWeight','bold');
    spmi.plot_threshold_label();
    spmi.plot_p_values();    
    subplot(1,2,2);
    YPmean = mean (YP');
    YPstd = std (YP');
    numYPPts = length (YPmean);
    YNPmean = mean (YNP');
    YNPstd = std (YNP');
    numYNPPts = length (YNPmean);
    p1 = plot (1:numYPPts, YPmean, 'b','LineWidth',2);
    hold on
	plot (1:numYPPts, YPmean + YPstd, 'b--');
	plot (1:numYPPts, YPmean - YPstd, 'b--');
    p2 = plot (1:numYNPPts, YNPmean, 'r','LineWidth',2);
	plot (1:numYNPPts, YNPmean + YNPstd, 'r--');
    plot (1:numYNPPts, YNPmean - YNPstd, 'r--');
    xlim ([1 numYPPts]);
    legend([p1 p2],'Pain','No Pain', 'Location','northwest')
    title('Mean and SD');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Angle','FontSize',12,'FontWeight','bold');   
    savefig('UTULY_RotateR_AllSubjects');
    saveas(gcf,'UTULY_RotateR_AllSubjects.png');
    
    %RotateLeftAll
    data = load('datasetUTULY_RotateL.mat','datasetUTULY_RotateL');
    [YP,YNP] = deal([data.datasetUTULY_RotateL.Subject1 ...
        data.datasetUTULY_RotateL.Subject4 data.datasetUTULY_RotateL.Subject5 ...
        data.datasetUTULY_RotateL.Subject7 ...
        data.datasetUTULY_RotateL.Subject8 data.datasetUTULY_RotateL.Subject9 ...
        data.datasetUTULY_RotateL.Subject10 data.datasetUTULY_RotateL.Subject11 ...
        data.datasetUTULY_RotateL.Subject13 data.datasetUTULY_RotateL.Subject14 ...
        data.datasetUTULY_RotateL.Subject17 ...
        data.datasetUTULY_RotateL.Subject18 data.datasetUTULY_RotateL.Subject19 ...
        data.datasetUTULY_RotateL.Subject20 data.datasetUTULY_RotateL.Subject21 ...
        data.datasetUTULY_RotateL.Subject24 data.datasetUTULY_RotateL.Subject25 ...
        data.datasetUTULY_RotateL.Subject27 ...
        data.datasetUTULY_RotateL.Subject28 data.datasetUTULY_RotateL.Subject29 ...
        data.datasetUTULY_RotateL.Subject30 ...
        data.datasetUTULY_RotateL.Subject32 data.datasetUTULY_RotateL.Subject34 ...
        data.datasetUTULY_RotateL.Subject35 data.datasetUTULY_RotateL.Subject36 ...
        data.datasetUTULY_RotateL.Subject37 data.datasetUTULY_RotateL.Subject39 ...
        data.datasetUTULY_RotateL.Subject42 data.datasetUTULY_RotateL.Subject43 ...
        data.datasetUTULY_RotateL.Subject44 data.datasetUTULY_RotateL.Subject46 ...
        data.datasetUTULY_RotateL.Subject47 data.datasetUTULY_RotateL.Subject48 ...
        data.datasetUTULY_RotateL.Subject49 ...
        data.datasetUTULY_RotateL.Subject50 data.datasetUTULY_RotateL.Subject54], ...
        [data.datasetUTULY_RotateL.Subject2 data.datasetUTULY_RotateL.Subject3 ...
        data.datasetUTULY_RotateL.Subject6 data.datasetUTULY_RotateL.Subject12 ...
        data.datasetUTULY_RotateL.Subject15 data.datasetUTULY_RotateL.Subject16 ...
        data.datasetUTULY_RotateL.Subject22 data.datasetUTULY_RotateL.Subject23 ...
        data.datasetUTULY_RotateL.Subject26 data.datasetUTULY_RotateL.Subject31 ...
        data.datasetUTULY_RotateL.Subject33 data.datasetUTULY_RotateL.Subject38 ...
        data.datasetUTULY_RotateL.Subject40 data.datasetUTULY_RotateL.Subject41 ...
        data.datasetUTULY_RotateL.Subject45 data.datasetUTULY_RotateL.Subject51 ...
        data.datasetUTULY_RotateL.Subject52 data.datasetUTULY_RotateL.Subject53 ...
        data.datasetUTULY_RotateL.Subject55 ...
        data.datasetUTULY_RotateL.Subject56 data.datasetUTULY_RotateL.Subject57 ...
        data.datasetUTULY_RotateL.Subject58 data.datasetUTULY_RotateL.Subject59 ...
        data.datasetUTULY_RotateL.Subject60 ]);
    spm       = spm1d.stats.ttest2(YP', YNP');
    spmi      = spm.inference(0.05, 'two_tailed', true, 'interp',true);
    disp(spmi);
    close all
    subplot(1,2,1);
    spmi.plot();
    title('Two-Sample T-Test');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Variance','FontSize',12,'FontWeight','bold');
    spmi.plot_threshold_label();
    spmi.plot_p_values();    
    subplot(1,2,2);
    YPmean = mean (YP');
    YPstd = std (YP');
    numYPPts = length (YPmean);
    YNPmean = mean (YNP');
    YNPstd = std (YNP');
    numYNPPts = length (YNPmean);
    p1 = plot (1:numYPPts, YPmean, 'b','LineWidth',2);
    hold on
	plot (1:numYPPts, YPmean + YPstd, 'b--');
	plot (1:numYPPts, YPmean - YPstd, 'b--');
    p2 = plot (1:numYNPPts, YNPmean, 'r','LineWidth',2);
	plot (1:numYNPPts, YNPmean + YNPstd, 'r--');
    plot (1:numYNPPts, YNPmean - YNPstd, 'r--');
    xlim ([1 numYPPts]);
    legend([p1 p2],'Pain','No Pain', 'Location','northwest')
    title('Mean and SD');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Angle','FontSize',12,'FontWeight','bold');    
    savefig('UTULY_RotateL_AllSubjects');
    saveas(gcf,'UTULY_RotateL_AllSubjects.png');
    
    %SitRotateLeftAll
    data = load('datasetUTULY_SitRotateL.mat','datasetUTULY_SitRotateL');
    [YP,YNP] = deal([data.datasetUTULY_SitRotateL.Subject1 ...
        data.datasetUTULY_SitRotateL.Subject4 data.datasetUTULY_SitRotateL.Subject6 ...
        data.datasetUTULY_SitRotateL.Subject7 data.datasetUTULY_SitRotateL.Subject8 ...
        data.datasetUTULY_SitRotateL.Subject9 data.datasetUTULY_SitRotateL.Subject10 ...
        data.datasetUTULY_SitRotateL.Subject11 data.datasetUTULY_SitRotateL.Subject13 ...
        data.datasetUTULY_SitRotateL.Subject15 ...
        data.datasetUTULY_SitRotateL.Subject16 data.datasetUTULY_SitRotateL.Subject17 ...
        data.datasetUTULY_SitRotateL.Subject18 data.datasetUTULY_SitRotateL.Subject19 ...
        data.datasetUTULY_SitRotateL.Subject22 data.datasetUTULY_SitRotateL.Subject23 ...
        data.datasetUTULY_SitRotateL.Subject25 ...
        data.datasetUTULY_SitRotateL.Subject26 data.datasetUTULY_SitRotateL.Subject27 ...
        data.datasetUTULY_SitRotateL.Subject28 ...
        data.datasetUTULY_SitRotateL.Subject30 data.datasetUTULY_SitRotateL.Subject32 ...
        data.datasetUTULY_SitRotateL.Subject33 data.datasetUTULY_SitRotateL.Subject34 ...
        data.datasetUTULY_SitRotateL.Subject35 data.datasetUTULY_SitRotateL.Subject37 ...
        data.datasetUTULY_SitRotateL.Subject40 data.datasetUTULY_SitRotateL.Subject41 ...
        data.datasetUTULY_SitRotateL.Subject42 data.datasetUTULY_SitRotateL.Subject44 ...
        data.datasetUTULY_SitRotateL.Subject45 data.datasetUTULY_SitRotateL.Subject46 ...
        data.datasetUTULY_SitRotateL.Subject47 ...
        data.datasetUTULY_SitRotateL.Subject48 data.datasetUTULY_SitRotateL.Subject52 ], ...
        [data.datasetUTULY_SitRotateL.Subject2 data.datasetUTULY_SitRotateL.Subject3 ...
        data.datasetUTULY_SitRotateL.Subject5 data.datasetUTULY_SitRotateL.Subject11 ...
        data.datasetUTULY_SitRotateL.Subject14 ...
        data.datasetUTULY_SitRotateL.Subject20 data.datasetUTULY_SitRotateL.Subject21 ...
        data.datasetUTULY_SitRotateL.Subject24 data.datasetUTULY_SitRotateL.Subject29 ...
        data.datasetUTULY_SitRotateL.Subject31 data.datasetUTULY_SitRotateL.Subject36 ...
        data.datasetUTULY_SitRotateL.Subject38 data.datasetUTULY_SitRotateL.Subject39 ...
        data.datasetUTULY_SitRotateL.Subject43 data.datasetUTULY_SitRotateL.Subject49 ...
        data.datasetUTULY_SitRotateL.Subject50 data.datasetUTULY_SitRotateL.Subject51 ...
        data.datasetUTULY_SitRotateL.Subject53 ...
        data.datasetUTULY_SitRotateL.Subject54 data.datasetUTULY_SitRotateL.Subject55 ...
        data.datasetUTULY_SitRotateL.Subject56 data.datasetUTULY_SitRotateL.Subject57 ...
        data.datasetUTULY_SitRotateL.Subject58 ]);
    spm       = spm1d.stats.ttest2(YP', YNP');
    spmi      = spm.inference(0.05, 'two_tailed', true, 'interp',true);
    disp(spmi);
    close all
    subplot(1,2,1);
    spmi.plot();
    title('Two-Sample T-Test');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Variance','FontSize',12,'FontWeight','bold');
    spmi.plot_threshold_label();
    spmi.plot_p_values();    
    subplot(1,2,2);
    YPmean = mean (YP');
    YPstd = std (YP');
    numYPPts = length (YPmean);
    YNPmean = mean (YNP');
    YNPstd = std (YNP');
    numYNPPts = length (YNPmean);
    p1 = plot (1:numYPPts, YPmean, 'b','LineWidth',2);
    hold on
	plot (1:numYPPts, YPmean + YPstd, 'b--');
	plot (1:numYPPts, YPmean - YPstd, 'b--');
    p2 = plot (1:numYNPPts, YNPmean, 'r','LineWidth',2);
	plot (1:numYNPPts, YNPmean + YNPstd, 'r--');
    plot (1:numYNPPts, YNPmean - YNPstd, 'r--');
    xlim ([1 numYPPts]);
    legend([p1 p2],'Pain','No Pain', 'Location','northwest')
    title('Mean and SD');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Angle','FontSize',12,'FontWeight','bold');    
    savefig('UTULY_SitRotateL_AllSubjects');
    saveas(gcf,'UTULY_SitRotateL_AllSubjects.png');   
    
        %RotateRightF
    data = load('datasetUTULZ_RotateR.mat','datasetUTULZ_RotateR');
    [YP,YNP] = deal([data.datasetUTULZ_RotateR.Subject4 data.datasetUTULZ_RotateR.Subject7 ...
        data.datasetUTULZ_RotateR.Subject8 data.datasetUTULZ_RotateR.Subject9 ...
        data.datasetUTULZ_RotateR.Subject10 data.datasetUTULZ_RotateR.Subject11 ...
        data.datasetUTULZ_RotateR.Subject18 data.datasetUTULZ_RotateR.Subject19 ...
        data.datasetUTULZ_RotateR.Subject20 data.datasetUTULZ_RotateR.Subject21 ...
        data.datasetUTULZ_RotateR.Subject24 data.datasetUTULZ_RotateR.Subject25 ...
        data.datasetUTULZ_RotateR.Subject28 data.datasetUTULZ_RotateR.Subject30 ...
        data.datasetUTULZ_RotateR.Subject32 data.datasetUTULZ_RotateR.Subject34 ...
        data.datasetUTULZ_RotateR.Subject35 data.datasetUTULZ_RotateR.Subject36 ...
        data.datasetUTULZ_RotateR.Subject37 data.datasetUTULZ_RotateR.Subject39 ...
        data.datasetUTULZ_RotateR.Subject42 data.datasetUTULZ_RotateR.Subject43 ...
        data.datasetUTULZ_RotateR.Subject44 data.datasetUTULZ_RotateR.Subject46 ...
        data.datasetUTULZ_RotateR.Subject47 data.datasetUTULZ_RotateR.Subject48 ...
        data.datasetUTULZ_RotateR.Subject50 ], ...
        [data.datasetUTULZ_RotateR.Subject2 data.datasetUTULZ_RotateR.Subject3 ...
        data.datasetUTULZ_RotateR.Subject6 data.datasetUTULZ_RotateR.Subject12 ...
        data.datasetUTULZ_RotateR.Subject15 data.datasetUTULZ_RotateR.Subject16 ...
        data.datasetUTULZ_RotateR.Subject22 data.datasetUTULZ_RotateR.Subject23 ...
        data.datasetUTULZ_RotateR.Subject26 data.datasetUTULZ_RotateR.Subject31 ...
        data.datasetUTULZ_RotateR.Subject33 data.datasetUTULZ_RotateR.Subject38 ...
        data.datasetUTULZ_RotateR.Subject40 data.datasetUTULZ_RotateR.Subject41 ...
        data.datasetUTULZ_RotateR.Subject45 data.datasetUTULZ_RotateR.Subject51 ...
        data.datasetUTULZ_RotateR.Subject52 data.datasetUTULZ_RotateR.Subject55 ...
        data.datasetUTULZ_RotateR.Subject56 data.datasetUTULZ_RotateR.Subject57 ...
        data.datasetUTULZ_RotateR.Subject58 ]);
    spm       = spm1d.stats.ttest2(YP', YNP');
    spmi      = spm.inference(0.05, 'two_tailed', true, 'interp',true);
    disp(spmi);
    close all
    subplot(1,2,1);
    spmi.plot();
    title('Two-Sample T-Test');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Variance','FontSize',12,'FontWeight','bold');
    spmi.plot_threshold_label();
    spmi.plot_p_values();  
    subplot(1,2,2);
    YPmean = mean (YP');
    YPstd = std (YP');
    numYPPts = length (YPmean);
    YNPmean = mean (YNP');
    YNPstd = std (YNP');
    numYNPPts = length (YNPmean);
    p1 = plot (1:numYPPts, YPmean, 'b','LineWidth',2);
    hold on
	plot (1:numYPPts, YPmean + YPstd, 'b--');
	plot (1:numYPPts, YPmean - YPstd, 'b--');
    p2 = plot (1:numYNPPts, YNPmean, 'r','LineWidth',2);
	plot (1:numYNPPts, YNPmean + YNPstd, 'r--');
    plot (1:numYNPPts, YNPmean - YNPstd, 'r--');
    xlim ([1 numYPPts]);
    legend([p1 p2],'Pain','No Pain', 'Location','northwest')
    title('Mean and SD');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Angle','FontSize',12,'FontWeight','bold');    
    savefig('UTULZ_RotateR_Females');
    saveas(gcf,'UTULZ_RotateR_Females.png');
    
    %RotateLeftF
    data = load('datasetUTULZ_RotateL.mat','datasetUTULZ_RotateL');
    [YP,YNP] = deal([data.datasetUTULZ_RotateL.Subject4 data.datasetUTULZ_RotateL.Subject7 ...
        data.datasetUTULZ_RotateL.Subject8 data.datasetUTULZ_RotateL.Subject9 ...
        data.datasetUTULZ_RotateL.Subject10 data.datasetUTULZ_RotateL.Subject11 ...
        data.datasetUTULZ_RotateL.Subject18 data.datasetUTULZ_RotateL.Subject19 ...
        data.datasetUTULZ_RotateL.Subject20 data.datasetUTULZ_RotateL.Subject21 ...
        data.datasetUTULZ_RotateL.Subject24 data.datasetUTULZ_RotateL.Subject25 ...
        data.datasetUTULZ_RotateL.Subject28 data.datasetUTULZ_RotateL.Subject30 ...
        data.datasetUTULZ_RotateL.Subject32 data.datasetUTULZ_RotateL.Subject34 ...
        data.datasetUTULZ_RotateL.Subject35 data.datasetUTULZ_RotateL.Subject36 ...
        data.datasetUTULZ_RotateL.Subject37 data.datasetUTULZ_RotateL.Subject39 ...
        data.datasetUTULZ_RotateL.Subject42 data.datasetUTULZ_RotateL.Subject43 ...
        data.datasetUTULZ_RotateL.Subject44 data.datasetUTULZ_RotateL.Subject46 ...
        data.datasetUTULZ_RotateL.Subject47 data.datasetUTULZ_RotateL.Subject48 ...
        data.datasetUTULZ_RotateL.Subject50 ], ...
        [data.datasetUTULZ_RotateL.Subject2 data.datasetUTULZ_RotateL.Subject3 ...
        data.datasetUTULZ_RotateL.Subject6 data.datasetUTULZ_RotateL.Subject12 ...
        data.datasetUTULZ_RotateL.Subject15 data.datasetUTULZ_RotateL.Subject16 ...
        data.datasetUTULZ_RotateL.Subject22 data.datasetUTULZ_RotateL.Subject23 ...
        data.datasetUTULZ_RotateL.Subject26 data.datasetUTULZ_RotateL.Subject31 ...
        data.datasetUTULZ_RotateL.Subject33 data.datasetUTULZ_RotateL.Subject38 ...
        data.datasetUTULZ_RotateL.Subject40 data.datasetUTULZ_RotateL.Subject41 ...
        data.datasetUTULZ_RotateL.Subject45 data.datasetUTULZ_RotateL.Subject51 ...
        data.datasetUTULZ_RotateL.Subject52 data.datasetUTULZ_RotateL.Subject55 ...
        data.datasetUTULZ_RotateL.Subject56 data.datasetUTULZ_RotateL.Subject57 ...
        data.datasetUTULZ_RotateL.Subject58 ]);
    spm       = spm1d.stats.ttest2(YP', YNP');
    spmi      = spm.inference(0.05, 'two_tailed', true, 'interp',true);
    disp(spmi);
    close all
    subplot(1,2,1);
    spmi.plot();
    title('Two-Sample T-Test');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Variance','FontSize',12,'FontWeight','bold');
    spmi.plot_threshold_label();
    spmi.plot_p_values();   
    subplot(1,2,2);
    YPmean = mean (YP');
    YPstd = std (YP');
    numYPPts = length (YPmean);
    YNPmean = mean (YNP');
    YNPstd = std (YNP');
    numYNPPts = length (YNPmean);
    p1 = plot (1:numYPPts, YPmean, 'b','LineWidth',2);
    hold on
	plot (1:numYPPts, YPmean + YPstd, 'b--');
	plot (1:numYPPts, YPmean - YPstd, 'b--');
    p2 = plot (1:numYNPPts, YNPmean, 'r','LineWidth',2);
	plot (1:numYNPPts, YNPmean + YNPstd, 'r--');
    plot (1:numYNPPts, YNPmean - YNPstd, 'r--');
    xlim ([1 numYPPts]);
    legend([p1 p2],'Pain','No Pain', 'Location','northwest')
    title('Mean and SD');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Angle','FontSize',12,'FontWeight','bold');   
    savefig('UTULZ_RotateL_Females');
    saveas(gcf,'UTULZ_RotateL_Females.png');

    %SitRotateLeftF
    data = load('datasetUTULZ_SitRotateL.mat','datasetUTULZ_SitRotateL');
    [YP,YNP] = deal([data.datasetUTULZ_SitRotateL.Subject4 data.datasetUTULZ_SitRotateL.Subject6 ...
        data.datasetUTULZ_SitRotateL.Subject7 data.datasetUTULZ_SitRotateL.Subject8 ...
        data.datasetUTULZ_SitRotateL.Subject9 data.datasetUTULZ_SitRotateL.Subject10 ...
        data.datasetUTULZ_SitRotateL.Subject16 data.datasetUTULZ_SitRotateL.Subject17 ...
        data.datasetUTULZ_SitRotateL.Subject18 data.datasetUTULZ_SitRotateL.Subject19 ...
        data.datasetUTULZ_SitRotateL.Subject22 data.datasetUTULZ_SitRotateL.Subject23 ...
        data.datasetUTULZ_SitRotateL.Subject26 data.datasetUTULZ_SitRotateL.Subject28 ...
        data.datasetUTULZ_SitRotateL.Subject30 data.datasetUTULZ_SitRotateL.Subject32 ...
        data.datasetUTULZ_SitRotateL.Subject33 data.datasetUTULZ_SitRotateL.Subject34 ...
        data.datasetUTULZ_SitRotateL.Subject35 data.datasetUTULZ_SitRotateL.Subject37 ...
        data.datasetUTULZ_SitRotateL.Subject40 data.datasetUTULZ_SitRotateL.Subject41 ...
        data.datasetUTULZ_SitRotateL.Subject42 data.datasetUTULZ_SitRotateL.Subject44 ...
        data.datasetUTULZ_SitRotateL.Subject45 data.datasetUTULZ_SitRotateL.Subject46 ...
        data.datasetUTULZ_SitRotateL.Subject48 ], ...
        [data.datasetUTULZ_SitRotateL.Subject2 data.datasetUTULZ_SitRotateL.Subject3 ...
        data.datasetUTULZ_SitRotateL.Subject5 data.datasetUTULZ_SitRotateL.Subject11 ...
        data.datasetUTULZ_SitRotateL.Subject14 ...
        data.datasetUTULZ_SitRotateL.Subject20 data.datasetUTULZ_SitRotateL.Subject21 ...
        data.datasetUTULZ_SitRotateL.Subject24 data.datasetUTULZ_SitRotateL.Subject29 ...
        data.datasetUTULZ_SitRotateL.Subject31 data.datasetUTULZ_SitRotateL.Subject36 ...
        data.datasetUTULZ_SitRotateL.Subject38 data.datasetUTULZ_SitRotateL.Subject39 ...
        data.datasetUTULZ_SitRotateL.Subject43 data.datasetUTULZ_SitRotateL.Subject49 ...
        data.datasetUTULZ_SitRotateL.Subject50 data.datasetUTULZ_SitRotateL.Subject53 ...
        data.datasetUTULZ_SitRotateL.Subject54 data.datasetUTULZ_SitRotateL.Subject55 ...
        data.datasetUTULZ_SitRotateL.Subject56 ]);
    spm       = spm1d.stats.ttest2(YP', YNP');
    spmi      = spm.inference(0.05, 'two_tailed', true, 'interp',true);
    disp(spmi);
    close all
    subplot(1,2,1);
    spmi.plot();
    title('Two-Sample T-Test');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Variance','FontSize',12,'FontWeight','bold');
    spmi.plot_threshold_label();
    spmi.plot_p_values();    
    subplot(1,2,2);
    YPmean = mean (YP');
    YPstd = std (YP');
    numYPPts = length (YPmean);
    YNPmean = mean (YNP');
    YNPstd = std (YNP');
    numYNPPts = length (YNPmean);
    p1 = plot (1:numYPPts, YPmean, 'b','LineWidth',2);
    hold on
	plot (1:numYPPts, YPmean + YPstd, 'b--');
	plot (1:numYPPts, YPmean - YPstd, 'b--');
    p2 = plot (1:numYNPPts, YNPmean, 'r','LineWidth',2);
	plot (1:numYNPPts, YNPmean + YNPstd, 'r--');
    plot (1:numYNPPts, YNPmean - YNPstd, 'r--');
    xlim ([1 numYPPts]);
    legend([p1 p2],'Pain','No Pain', 'Location','northwest')
    title('Mean and SD');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Angle','FontSize',12,'FontWeight','bold');    
    savefig('UTULZ_SitRotateL_Females');
    saveas(gcf,'UTULZ_SitRotateL_Females.png');
    
    %SitRotateRightF
    data = load('datasetUTULZ_SitRotateR.mat','datasetUTULZ_SitRotateR');
    [YP,YNP] = deal([data.datasetUTULZ_SitRotateR.Subject4 data.datasetUTULZ_SitRotateR.Subject6 ...
        data.datasetUTULZ_SitRotateR.Subject7 data.datasetUTULZ_SitRotateR.Subject8 ...
        data.datasetUTULZ_SitRotateR.Subject9 data.datasetUTULZ_SitRotateR.Subject10 ...
        data.datasetUTULZ_SitRotateR.Subject16 ...
        data.datasetUTULZ_SitRotateR.Subject17 data.datasetUTULZ_SitRotateR.Subject18 ...
        data.datasetUTULZ_SitRotateR.Subject21 data.datasetUTULZ_SitRotateR.Subject22 ...
        data.datasetUTULZ_SitRotateR.Subject25 data.datasetUTULZ_SitRotateR.Subject27 ...
        data.datasetUTULZ_SitRotateR.Subject29 data.datasetUTULZ_SitRotateR.Subject31 ...
        data.datasetUTULZ_SitRotateR.Subject32 data.datasetUTULZ_SitRotateR.Subject33 ...
        data.datasetUTULZ_SitRotateR.Subject34 data.datasetUTULZ_SitRotateR.Subject36 ...
        data.datasetUTULZ_SitRotateR.Subject39 ...
        data.datasetUTULZ_SitRotateR.Subject40 data.datasetUTULZ_SitRotateR.Subject42 ...
        data.datasetUTULZ_SitRotateR.Subject43 data.datasetUTULZ_SitRotateR.Subject44 ...
        data.datasetUTULZ_SitRotateR.Subject46 ], ...
        [data.datasetUTULZ_SitRotateR.Subject2 data.datasetUTULZ_SitRotateR.Subject3 ...
        data.datasetUTULZ_SitRotateR.Subject5 data.datasetUTULZ_SitRotateR.Subject11 ...
        data.datasetUTULZ_SitRotateR.Subject14 ...
        data.datasetUTULZ_SitRotateR.Subject19 data.datasetUTULZ_SitRotateR.Subject20 ...
        data.datasetUTULZ_SitRotateR.Subject23 data.datasetUTULZ_SitRotateR.Subject28 ...
        data.datasetUTULZ_SitRotateR.Subject30 data.datasetUTULZ_SitRotateR.Subject35 ...
        data.datasetUTULZ_SitRotateR.Subject37 data.datasetUTULZ_SitRotateR.Subject38 ...
        data.datasetUTULZ_SitRotateR.Subject41 data.datasetUTULZ_SitRotateR.Subject47 ...
        data.datasetUTULZ_SitRotateR.Subject48 data.datasetUTULZ_SitRotateR.Subject51 ...
        data.datasetUTULZ_SitRotateR.Subject52 data.datasetUTULZ_SitRotateR.Subject53 ...
        data.datasetUTULZ_SitRotateR.Subject54 ]);
    spm       = spm1d.stats.ttest2(YP', YNP');
    spmi      = spm.inference(0.05, 'two_tailed', true, 'interp',true);
    disp(spmi);
    close all
    subplot(1,2,1);
    spmi.plot();
    title('Two-Sample T-Test');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Variance','FontSize',12,'FontWeight','bold');
    spmi.plot_threshold_label();
    spmi.plot_p_values();
    subplot(1,2,2);
    YPmean = mean (YP');
    YPstd = std (YP');
    numYPPts = length (YPmean);
    YNPmean = mean (YNP');
    YNPstd = std (YNP');
    numYNPPts = length (YNPmean);
    p1 = plot (1:numYPPts, YPmean, 'b','LineWidth',2);
    hold on
    plot (1:numYPPts, YPmean + YPstd, 'b--');
    plot (1:numYPPts, YPmean - YPstd, 'b--');
    p2 = plot (1:numYNPPts, YNPmean, 'r','LineWidth',2);
    plot (1:numYNPPts, YNPmean + YNPstd, 'r--');
    plot (1:numYNPPts, YNPmean - YNPstd, 'r--');
    xlim ([1 numYPPts]);
    legend([p1 p2],'Pain','No Pain', 'Location','northwest')
    title('Mean and SD');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Angle','FontSize',12,'FontWeight','bold');
    savefig('UTULZ_SitRotateR_Females');
    saveas(gcf,'UTULZ_SitRotateR_Females.png');
    
    %RotateRightAll
    data = load('datasetUTULZ_RotateR.mat','datasetUTULZ_RotateR');
    [YP,YNP] = deal([data.datasetUTULZ_RotateR.Subject1 ...
        data.datasetUTULZ_RotateR.Subject4 data.datasetUTULZ_RotateR.Subject5 ...
        data.datasetUTULZ_RotateR.Subject7 ...
        data.datasetUTULZ_RotateR.Subject8 data.datasetUTULZ_RotateR.Subject9 ...
        data.datasetUTULZ_RotateR.Subject10 data.datasetUTULZ_RotateR.Subject11 ...
        data.datasetUTULZ_RotateR.Subject13 data.datasetUTULZ_RotateR.Subject14 ...
        data.datasetUTULZ_RotateR.Subject17 ...
        data.datasetUTULZ_RotateR.Subject18 data.datasetUTULZ_RotateR.Subject19 ...
        data.datasetUTULZ_RotateR.Subject20 data.datasetUTULZ_RotateR.Subject21 ...
        data.datasetUTULZ_RotateR.Subject24 data.datasetUTULZ_RotateR.Subject25 ...
        data.datasetUTULZ_RotateR.Subject27 ...
        data.datasetUTULZ_RotateR.Subject28 data.datasetUTULZ_RotateR.Subject29 ...
        data.datasetUTULZ_RotateR.Subject30 ...
        data.datasetUTULZ_RotateR.Subject32 data.datasetUTULZ_RotateR.Subject34 ...
        data.datasetUTULZ_RotateR.Subject35 data.datasetUTULZ_RotateR.Subject36 ...
        data.datasetUTULZ_RotateR.Subject37 data.datasetUTULZ_RotateR.Subject39 ...
        data.datasetUTULZ_RotateR.Subject42 data.datasetUTULZ_RotateR.Subject43 ...
        data.datasetUTULZ_RotateR.Subject44 data.datasetUTULZ_RotateR.Subject46 ...
        data.datasetUTULZ_RotateR.Subject47 data.datasetUTULZ_RotateR.Subject48 ...
        data.datasetUTULZ_RotateR.Subject49 ...
        data.datasetUTULZ_RotateR.Subject50 data.datasetUTULZ_RotateR.Subject54], ...
        [data.datasetUTULZ_RotateR.Subject2 data.datasetUTULZ_RotateR.Subject3 ...
        data.datasetUTULZ_RotateR.Subject6 data.datasetUTULZ_RotateR.Subject12 ...
        data.datasetUTULZ_RotateR.Subject15 data.datasetUTULZ_RotateR.Subject16 ...
        data.datasetUTULZ_RotateR.Subject22 data.datasetUTULZ_RotateR.Subject23 ...
        data.datasetUTULZ_RotateR.Subject26 data.datasetUTULZ_RotateR.Subject31 ...
        data.datasetUTULZ_RotateR.Subject33 data.datasetUTULZ_RotateR.Subject38 ...
        data.datasetUTULZ_RotateR.Subject40 data.datasetUTULZ_RotateR.Subject41 ...
        data.datasetUTULZ_RotateR.Subject45 data.datasetUTULZ_RotateR.Subject51 ...
        data.datasetUTULZ_RotateR.Subject52 data.datasetUTULZ_RotateR.Subject53 ...
        data.datasetUTULZ_RotateR.Subject55 ...
        data.datasetUTULZ_RotateR.Subject56 data.datasetUTULZ_RotateR.Subject57 ...
        data.datasetUTULZ_RotateR.Subject58 data.datasetUTULZ_RotateR.Subject59 ...
        data.datasetUTULZ_RotateR.Subject60 ]);
    spm       = spm1d.stats.ttest2(YP', YNP');
    spmi      = spm.inference(0.05, 'two_tailed', true, 'interp',true);
    disp(spmi);
    close all
    subplot(1,2,1);
    spmi.plot();
    title('Two-Sample T-Test');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Variance','FontSize',12,'FontWeight','bold');
    spmi.plot_threshold_label();
    spmi.plot_p_values();    
    subplot(1,2,2);
    YPmean = mean (YP');
    YPstd = std (YP');
    numYPPts = length (YPmean);
    YNPmean = mean (YNP');
    YNPstd = std (YNP');
    numYNPPts = length (YNPmean);
    p1 = plot (1:numYPPts, YPmean, 'b','LineWidth',2);
    hold on
	plot (1:numYPPts, YPmean + YPstd, 'b--');
	plot (1:numYPPts, YPmean - YPstd, 'b--');
    p2 = plot (1:numYNPPts, YNPmean, 'r','LineWidth',2);
	plot (1:numYNPPts, YNPmean + YNPstd, 'r--');
    plot (1:numYNPPts, YNPmean - YNPstd, 'r--');
    xlim ([1 numYPPts]);
    legend([p1 p2],'Pain','No Pain', 'Location','northwest')
    title('Mean and SD');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Angle','FontSize',12,'FontWeight','bold');   
    savefig('UTULZ_RotateR_AllSubjects');
    saveas(gcf,'UTULZ_RotateR_AllSubjects.png');
    
    %RotateLeftAll
    data = load('datasetUTULZ_RotateL.mat','datasetUTULZ_RotateL');
    [YP,YNP] = deal([data.datasetUTULZ_RotateL.Subject1 ...
        data.datasetUTULZ_RotateL.Subject4 data.datasetUTULZ_RotateL.Subject5 ...
        data.datasetUTULZ_RotateL.Subject7 ...
        data.datasetUTULZ_RotateL.Subject8 data.datasetUTULZ_RotateL.Subject9 ...
        data.datasetUTULZ_RotateL.Subject10 data.datasetUTULZ_RotateL.Subject11 ...
        data.datasetUTULZ_RotateL.Subject13 data.datasetUTULZ_RotateL.Subject14 ...
        data.datasetUTULZ_RotateL.Subject17 ...
        data.datasetUTULZ_RotateL.Subject18 data.datasetUTULZ_RotateL.Subject19 ...
        data.datasetUTULZ_RotateL.Subject20 data.datasetUTULZ_RotateL.Subject21 ...
        data.datasetUTULZ_RotateL.Subject24 data.datasetUTULZ_RotateL.Subject25 ...
        data.datasetUTULZ_RotateL.Subject27 ...
        data.datasetUTULZ_RotateL.Subject28 data.datasetUTULZ_RotateL.Subject29 ...
        data.datasetUTULZ_RotateL.Subject30 ...
        data.datasetUTULZ_RotateL.Subject32 data.datasetUTULZ_RotateL.Subject34 ...
        data.datasetUTULZ_RotateL.Subject35 data.datasetUTULZ_RotateL.Subject36 ...
        data.datasetUTULZ_RotateL.Subject37 data.datasetUTULZ_RotateL.Subject39 ...
        data.datasetUTULZ_RotateL.Subject42 data.datasetUTULZ_RotateL.Subject43 ...
        data.datasetUTULZ_RotateL.Subject44 data.datasetUTULZ_RotateL.Subject46 ...
        data.datasetUTULZ_RotateL.Subject47 data.datasetUTULZ_RotateL.Subject48 ...
        data.datasetUTULZ_RotateL.Subject49 ...
        data.datasetUTULZ_RotateL.Subject50 data.datasetUTULZ_RotateL.Subject54], ...
        [data.datasetUTULZ_RotateL.Subject2 data.datasetUTULZ_RotateL.Subject3 ...
        data.datasetUTULZ_RotateL.Subject6 data.datasetUTULZ_RotateL.Subject12 ...
        data.datasetUTULZ_RotateL.Subject15 data.datasetUTULZ_RotateL.Subject16 ...
        data.datasetUTULZ_RotateL.Subject22 data.datasetUTULZ_RotateL.Subject23 ...
        data.datasetUTULZ_RotateL.Subject26 data.datasetUTULZ_RotateL.Subject31 ...
        data.datasetUTULZ_RotateL.Subject33 data.datasetUTULZ_RotateL.Subject38 ...
        data.datasetUTULZ_RotateL.Subject40 data.datasetUTULZ_RotateL.Subject41 ...
        data.datasetUTULZ_RotateL.Subject45 data.datasetUTULZ_RotateL.Subject51 ...
        data.datasetUTULZ_RotateL.Subject52 data.datasetUTULZ_RotateL.Subject53 ...
        data.datasetUTULZ_RotateL.Subject55 ...
        data.datasetUTULZ_RotateL.Subject56 data.datasetUTULZ_RotateL.Subject57 ...
        data.datasetUTULZ_RotateL.Subject58 data.datasetUTULZ_RotateL.Subject59 ...
        data.datasetUTULZ_RotateL.Subject60 ]);
    spm       = spm1d.stats.ttest2(YP', YNP');
    spmi      = spm.inference(0.05, 'two_tailed', true, 'interp',true);
    disp(spmi);
    close all
    subplot(1,2,1);
    spmi.plot();
    title('Two-Sample T-Test');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Variance','FontSize',12,'FontWeight','bold');
    spmi.plot_threshold_label();
    spmi.plot_p_values();    
    subplot(1,2,2);
    YPmean = mean (YP');
    YPstd = std (YP');
    numYPPts = length (YPmean);
    YNPmean = mean (YNP');
    YNPstd = std (YNP');
    numYNPPts = length (YNPmean);
    p1 = plot (1:numYPPts, YPmean, 'b','LineWidth',2);
    hold on
	plot (1:numYPPts, YPmean + YPstd, 'b--');
	plot (1:numYPPts, YPmean - YPstd, 'b--');
    p2 = plot (1:numYNPPts, YNPmean, 'r','LineWidth',2);
	plot (1:numYNPPts, YNPmean + YNPstd, 'r--');
    plot (1:numYNPPts, YNPmean - YNPstd, 'r--');
    xlim ([1 numYPPts]);
    legend([p1 p2],'Pain','No Pain', 'Location','northwest')
    title('Mean and SD');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Angle','FontSize',12,'FontWeight','bold');    
    savefig('UTULZ_RotateL_AllSubjects');
    saveas(gcf,'UTULZ_RotateL_AllSubjects.png');
    
    %SitRotateLeftAll
    data = load('datasetUTULZ_SitRotateL.mat','datasetUTULZ_SitRotateL');
    [YP,YNP] = deal([data.datasetUTULZ_SitRotateL.Subject1 ...
        data.datasetUTULZ_SitRotateL.Subject4 data.datasetUTULZ_SitRotateL.Subject6 ...
        data.datasetUTULZ_SitRotateL.Subject7 data.datasetUTULZ_SitRotateL.Subject8 ...
        data.datasetUTULZ_SitRotateL.Subject9 data.datasetUTULZ_SitRotateL.Subject10 ...
        data.datasetUTULZ_SitRotateL.Subject11 data.datasetUTULZ_SitRotateL.Subject13 ...
        data.datasetUTULZ_SitRotateL.Subject15 ...
        data.datasetUTULZ_SitRotateL.Subject16 data.datasetUTULZ_SitRotateL.Subject17 ...
        data.datasetUTULZ_SitRotateL.Subject18 data.datasetUTULZ_SitRotateL.Subject19 ...
        data.datasetUTULZ_SitRotateL.Subject22 data.datasetUTULZ_SitRotateL.Subject23 ...
        data.datasetUTULZ_SitRotateL.Subject25 ...
        data.datasetUTULZ_SitRotateL.Subject26 data.datasetUTULZ_SitRotateL.Subject27 ...
        data.datasetUTULZ_SitRotateL.Subject28 ...
        data.datasetUTULZ_SitRotateL.Subject30 data.datasetUTULZ_SitRotateL.Subject32 ...
        data.datasetUTULZ_SitRotateL.Subject33 data.datasetUTULZ_SitRotateL.Subject34 ...
        data.datasetUTULZ_SitRotateL.Subject35 data.datasetUTULZ_SitRotateL.Subject37 ...
        data.datasetUTULZ_SitRotateL.Subject40 data.datasetUTULZ_SitRotateL.Subject41 ...
        data.datasetUTULZ_SitRotateL.Subject42 data.datasetUTULZ_SitRotateL.Subject44 ...
        data.datasetUTULZ_SitRotateL.Subject45 data.datasetUTULZ_SitRotateL.Subject46 ...
        data.datasetUTULZ_SitRotateL.Subject47 ...
        data.datasetUTULZ_SitRotateL.Subject48 data.datasetUTULZ_SitRotateL.Subject52 ], ...
        [data.datasetUTULZ_SitRotateL.Subject2 data.datasetUTULZ_SitRotateL.Subject3 ...
        data.datasetUTULZ_SitRotateL.Subject5 data.datasetUTULZ_SitRotateL.Subject11 ...
        data.datasetUTULZ_SitRotateL.Subject14 ...
        data.datasetUTULZ_SitRotateL.Subject20 data.datasetUTULZ_SitRotateL.Subject21 ...
        data.datasetUTULZ_SitRotateL.Subject24 data.datasetUTULZ_SitRotateL.Subject29 ...
        data.datasetUTULZ_SitRotateL.Subject31 data.datasetUTULZ_SitRotateL.Subject36 ...
        data.datasetUTULZ_SitRotateL.Subject38 data.datasetUTULZ_SitRotateL.Subject39 ...
        data.datasetUTULZ_SitRotateL.Subject43 data.datasetUTULZ_SitRotateL.Subject49 ...
        data.datasetUTULZ_SitRotateL.Subject50 data.datasetUTULZ_SitRotateL.Subject51 ...
        data.datasetUTULZ_SitRotateL.Subject53 ...
        data.datasetUTULZ_SitRotateL.Subject54 data.datasetUTULZ_SitRotateL.Subject55 ...
        data.datasetUTULZ_SitRotateL.Subject56 data.datasetUTULZ_SitRotateL.Subject57 ...
        data.datasetUTULZ_SitRotateL.Subject58 ]);
    spm       = spm1d.stats.ttest2(YP', YNP');
    spmi      = spm.inference(0.05, 'two_tailed', true, 'interp',true);
    disp(spmi);
    close all
    subplot(1,2,1);
    spmi.plot();
    title('Two-Sample T-Test');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Variance','FontSize',12,'FontWeight','bold');
    spmi.plot_threshold_label();
    spmi.plot_p_values();    
    subplot(1,2,2);
    YPmean = mean (YP');
    YPstd = std (YP');
    numYPPts = length (YPmean);
    YNPmean = mean (YNP');
    YNPstd = std (YNP');
    numYNPPts = length (YNPmean);
    p1 = plot (1:numYPPts, YPmean, 'b','LineWidth',2);
    hold on
	plot (1:numYPPts, YPmean + YPstd, 'b--');
	plot (1:numYPPts, YPmean - YPstd, 'b--');
    p2 = plot (1:numYNPPts, YNPmean, 'r','LineWidth',2);
	plot (1:numYNPPts, YNPmean + YNPstd, 'r--');
    plot (1:numYNPPts, YNPmean - YNPstd, 'r--');
    xlim ([1 numYPPts]);
    legend([p1 p2],'Pain','No Pain', 'Location','northwest')
    title('Mean and SD');
    xlabel('Time (%)','FontSize',12,'FontWeight','bold');
    ylabel('Angle','FontSize',12,'FontWeight','bold');    
    savefig('UTULZ_SitRotateL_AllSubjects');
    saveas(gcf,'UTULZ_SitRotateL_AllSubjects.png');
    
end